const path = require('path');
const initSqlJs = require('sql.js');
const fs = require('fs');
const DB_PATH = path.join(__dirname, 'words.db');

const words = [
["habitual","odatiy, doimiy","regular, customary, routine","His habitual lateness annoyed everyone."],
["haggle","savdolashmoq, muzokaraga kirishmoq","bargain, negotiate, barter","She haggled over the price at the market."],
["hallmark","ajralib turadigan belgi","trademark, symbol, sign","Innovation is the hallmark of the company."],
["halt","to'xtatmoq, to'xtamoq","stop, cease, pause","Production was halted temporarily."],
["hamper","to'sqinlik qilmoq, savat","hinder, obstruct, impede","Bad weather hampered the rescue operation."],
["haphazard","tartibsiz, tasodifiy","random, chaotic, disorganized","The work was done in a haphazard manner."],
["harbor","bandargoh, panoh bermoq","port, shelter, conceal","The city has a natural harbor."],
["hardship","qiyinchilik, mashaqqat","difficulty, suffering, adversity","They endured many hardships."],
["harmony","uyg'unlik, hamjihatlik","accord, peace, unity","The community lives in harmony."],
["harness","jilovlamoq, boshqarmoq","utilize, control, exploit","We must harness solar energy."],
["harsh","qattiq, shafqatsiz","severe, strict, cruel","The punishment was too harsh."],
["harvest","hosil yig'ish, natija","crop, yield, reap","The harvest was plentiful this year."],
["haven","boshpana, xavfsiz joy","refuge, shelter, sanctuary","The island is a haven for wildlife."],
["havoc","vayronagarchilik, tartibsizlik","chaos, destruction, devastation","The virus wreaked havoc on the economy."],
["hazard","xavf, xatar","danger, risk, threat","Smoking is a health hazard."],
["hectic","shoshilinch, gavjum","busy, frantic, chaotic","She had a hectic schedule."],
["heed","e'tibor bermoq, tinglamoq","attention, notice, listen","Heed the doctor's advice."],
["heinous","dahshatli, yovuz","atrocious, terrible, wicked","The heinous crime shocked the nation."],
["herald","xabar bermoq, boshlanishini bildirmoq","announce, signal, proclaim","Spring heralded warmer weather."],
["heresy","bid'at, diniy gunoh","blasphemy, sacrilege, dissent","His ideas were considered heresy."],
["heritage","meros, madaniy boylik","legacy, tradition, inheritance","We must protect our cultural heritage."],
["hermit","yolg'iz yashovchi, tarkidunyochi","recluse, loner, isolate","The hermit lived alone in the mountains."],
["hesitant","ikkilanuvchi, shubhali","uncertain, reluctant, indecisive","She was hesitant to accept the offer."],
["heuristic","evristik, tajribaga asoslangan","practical, exploratory, trial-and-error","Heuristic methods help solve complex problems."],
["hiatus","tanaffus, uzilish","break, gap, pause","The band went on a two-year hiatus."],
["hierarchy","ierarxiya, bosqichli tuzilma","ranking, order, structure","The military has a strict hierarchy."],
["highlight","ta'kidlamoq, ajratib ko'rsatmoq","emphasize, stress, showcase","The report highlights key findings."],
["hinder","to'sqinlik qilmoq","obstruct, impede, hamper","Red tape hinders business growth."],
["hoard","yashirin zaxira, to'plamoq","stockpile, stash, accumulate","People hoarded food during the crisis."],
["holistic","yaxlit, umumiy","comprehensive, whole, integrated","A holistic approach to health considers mind and body."],
["homage","hurmat, e'tiborь","tribute, respect, honor","The ceremony paid homage to the founder."],
["homogeneous","bir xil, bir jinsli","uniform, similar, identical","The group was relatively homogeneous."],
["horizon","ufq, istiqbol","skyline, vista, future","The ship appeared on the horizon."],
["hostile","dushmanona, xavfli","aggressive, unfriendly, antagonistic","The crowd became hostile."],
["hover","parvoz qilmoq, o'ralib yurmoq","float, hang, linger","The helicopter hovered overhead."],
["humanitarian","insonparvarlik, xayriya","charitable, compassionate, altruistic","Humanitarian aid reached the victims."],
["humble","kamtar, sodda","modest, meek, unassuming","He has humble origins."],
["humiliate","sharmanda qilmoq","embarrass, disgrace, shame","She was humiliated in front of everyone."],
["hybrid","gibrid, aralash","crossbreed, mixture, blend","The hybrid car uses both electricity and fuel."],
["hypocrisy","ikkiyuzlamachilik, munofiqlik","insincerity, duplicity, pretense","Political hypocrisy angers voters."],
["hypothetical","faraziy, nazariy","theoretical, supposed, imaginary","Consider a hypothetical situation."],
["identical","bir xil, aynan o'xshash","same, matching, alike","The twin sisters look identical."],
["identify","aniqlash, tanib olmoq","recognize, detect, determine","Scientists identified a new species."],
["ignite","yoqmoq, qo'zg'atmoq","light, spark, kindle","The speech ignited a revolution."],
["illuminate","yoritmoq, tushuntirmoq","light up, clarify, explain","The discovery illuminated the mystery."],
["illusion","illyuziya, xayol","fantasy, mirage, deception","Freedom without responsibility is an illusion."],
["illustrate","tasvirlamoq, ko'rsatmoq","demonstrate, show, depict","Examples illustrate the concept."],
["immaculate","beg'ubor, toza","spotless, perfect, flawless","The room was immaculate."],
["immerse","cho'mmoq, singib ketmoq","submerge, absorb, engross","She immersed herself in the work."],
["imminent","yaqinlashayotgan, bo'lajak","impending, approaching, near","Danger was imminent."],
["immune","immunitetli, himoyalangan","resistant, protected, safe","Vaccination makes you immune."],
["impact","ta'sir, zarba","effect, influence, consequence","Technology has a huge impact."],
["impair","buzmoq, zaiflashtirmoq","damage, weaken, diminish","Alcohol impairs judgment."],
["impartial","xolis, betaraf","fair, neutral, unbiased","The judge must be impartial."],
["impasse","boshi berk ko'cha, chiqish yo'q","deadlock, stalemate, standstill","Negotiations reached an impasse."],
["impeach","javobgarlikka tortmoq","accuse, charge, indict","The president was impeached."],
["impeccable","benuqson, mukammal","flawless, perfect, faultless","Her record is impeccable."],
["impede","to'sqinlik qilmoq","hinder, obstruct, block","Bureaucracy impedes progress."],
["imperative","zarur, shart","essential, vital, crucial","Immediate action is imperative."],
["impetus","turtki, kuch","stimulus, motivation, momentum","The discovery gave impetus to further research."],
["implausible","ishonarsiz, haqiqatga o'xshamagan","unlikely, unbelievable, doubtful","The story seemed implausible."],
["implement","amalga oshirmoq, qo'llamoq","execute, apply, introduce","The plan was implemented successfully."],
["implication","oqibat, yashirin ma'no","consequence, inference, suggestion","The implications are far-reaching."],
["implicit","yashirin, anglab olinadigan","implied, tacit, understood","There was an implicit agreement."],
["implore","yolvormoq, iltimos qilmoq","beg, plead, entreat","She implored them to help."],
["impose","yuklash, majbur qilmoq","enforce, inflict, dictate","New taxes were imposed."],
["impostor","firibgar, o'zini boshqa qilib ko'rsatuvchi","fraud, pretender, fake","The impostor was exposed."],
["impoverish","qashshoqlashmoq, kambag'allashmoq","deprive, bankrupt, ruin","War impoverished the nation."],
["imprecise","noaniq, taxminiy","vague, inaccurate, approximate","The measurements were imprecise."],
["improvise","badihа qilmoq, tayyor bo'lmasdan","ad-lib, extemporize, wing it","He had to improvise when his notes were lost."],
["impunity","jazosizlik","exemption, immunity, freedom","He acted with impunity."],
["inaugurate","tantanali ochish, rasman boshlamoq","open, launch, initiate","The mayor inaugurated the new park."],
["incapacitate","ishga yaroqsiz qilmoq","disable, debilitate, immobilize","The injury incapacitated him."],
["incentive","rag'bat, turtki","motivation, reward, encouragement","Bonuses serve as incentives."],
["inception","boshlanish, tashkil etilish","beginning, start, origin","Since its inception, the company has grown."],
["incessant","to'xtovsiz, uzluksiz","continuous, constant, unending","The incessant rain caused flooding."],
["incidence","hodisalar soni, chastota","rate, frequency, occurrence","The incidence of crime dropped."],
["incidental","tasodifiy, ikkinchi darajali","minor, secondary, accidental","The finding was incidental to the main study."],
["incite","qo'zg'atmoq, gijgijlamoq","provoke, instigate, stir up","The speech incited violence."],
["inclusive","qamrab oluvchi, hamma uchun","comprehensive, broad, all-embracing","The price is inclusive of tax."],
["incompatible","mos kelmaydigan","conflicting, contradictory, unsuitable","Their views were incompatible."],
["inconclusive","yakuniy bo'lmagan, noaniq","uncertain, indefinite, undecided","The results were inconclusive."],
["incur","duch kelmoq, ko'rmoq","suffer, sustain, experience","The company incurred heavy losses."],
["indelible","o'chmaydigan, unutilmas","permanent, lasting, unforgettable","She left an indelible mark on history."],
["indemnity","tovon, kafolat","compensation, insurance, protection","The contract includes an indemnity clause."],
["indicate","ko'rsatmoq, bildirmoq","show, suggest, signal","The results indicate improvement."],
["indigenous","tub joy, mahalliy","native, aboriginal, local","Indigenous peoples have unique cultures."],
["indispensable","zarur, kerakli","essential, vital, necessary","Clean water is indispensable for life."],
["induce","sabab bo'lmoq, undamoq","cause, prompt, trigger","Stress can induce headaches."],
["indulge","erkalatmoq, ruxsat bermoq","pamper, gratify, spoil","She indulged in a slice of cake."],
["inert","harakatsiz, faoliyatsiz","inactive, dormant, passive","The inert gas does not react."],
["inevitable","muqarrar, bo'ladigan","unavoidable, certain, inescapable","Change is inevitable."],
["infamous","yomon mashhur","notorious, disreputable, scandalous","The infamous criminal was captured."],
["infancy","go'daklik, boshlang'ich davr","babyhood, early stage, beginning","The technology is still in its infancy."],
["infectious","yuqumli","contagious, communicable, spreading","Her laughter was infectious."],
["inferior","past, quyi sifatli","lower, lesser, subordinate","The product was of inferior quality."],
["infinite","cheksiz, tugamaydigan","limitless, endless, boundless","The possibilities are infinite."],
["inflame","yondirmoq, qo'zg'atmoq","provoke, aggravate, incite","His words inflamed the crowd."],
["inflation","inflyatsiya, narx oshishi","price increase, devaluation","Inflation is at a 10-year high."],
["inflexible","egilmaydigan, qattiq","rigid, strict, unyielding","The manager was inflexible about deadlines."],
["influence","ta'sir, ta'sir o'tkazmoq","impact, effect, sway","Teachers influence students' lives."],
["influx","oqib kelish, kirib kelish","inflow, arrival, surge","The influx of tourists boosts the economy."],
["inform","xabar bermoq, ma'lumot bermoq","tell, notify, advise","Please inform us of any changes."],
["infrastructure","infratuzilma, asosiy tuzilmalar","facilities, framework, systems","Roads are part of the infrastructure."],
["infringe","buzmoq, huquqni poymol qilmoq","violate, breach, transgress","The law infringes on personal freedom."],
["ingenious","topqir, zukko","clever, inventive, creative","An ingenious solution was found."],
["inhabit","yashamoq, istiqomat qilmoq","live in, reside, occupy","Polar bears inhabit the Arctic."],
["inherent","tabiiy, o'ziga xos","intrinsic, innate, built-in","Risk is inherent in business."],
["inhibit","to'siq qo'ymoq, oldini olmoq","prevent, hinder, restrain","Fear inhibits creativity."],
["initiate","boshlamoq, tashabbuskor bo'lmoq","begin, start, launch","She initiated the project."],
["injunction","sud buyrug'i, taqiq","order, directive, command","The court issued an injunction."],
["innovate","yangilik yaratmoq, ixtiro qilmoq","create, invent, pioneer","The company continues to innovate."],
["inoculate","emlash, em qilmoq","vaccinate, immunize, inject","Children should be inoculated early."],
["inquiry","so'rov, tekshiruv","investigation, question, study","A public inquiry was launched."],
["insatiable","to'ymaydigan, qoniqmaydigan","unquenchable, greedy, voracious","He had an insatiable appetite for knowledge."],
["inscribe","yozmoq, o'yib yozmoq","engrave, write, carve","His name was inscribed on the trophy."],
["insidious","yashirin xavfli, xiyla","treacherous, deceptive, cunning","The insidious disease spread slowly."],
["insinuate","ishora qilmoq, piching qilmoq","imply, suggest, hint","She insinuated that he was dishonest."],
["insipid","mazasiz, zerikarli","bland, dull, tasteless","The food was insipid."],
["insolvent","to'lovga qodir emas","bankrupt, broke, ruined","The company became insolvent."],
["instigate","qo'zg'amoq, boshlamoq","provoke, incite, initiate","He instigated the rebellion."],
["institute","ta'sis etmoq, institut","establish, create, organization","The institute conducts research."],
["instruct","o'rgatmoq, ko'rsatma bermoq","teach, direct, guide","She instructed the students carefully."],
["insulate","izolyatsiya qilmoq, himoyalamoq","protect, shield, isolate","The walls are well insulated."],
["insurgent","qo'zg'olonchi, isyonchi","rebel, revolutionary, guerrilla","Insurgents attacked the military base."],
["intact","butun, buzilmagan","whole, undamaged, complete","The building remained intact after the storm."],
["integral","ajralmas, muhim","essential, fundamental, key","Technology is integral to modern life."],
["integrate","birlashtirmoq, moslashtirmoq","combine, merge, incorporate","The school integrates technology into teaching."],
["integrity","halollik, butunlik","honesty, wholeness, ethics","Academic integrity is essential."],
["intellect","aql, zehn","mind, intelligence, reason","She has a sharp intellect."],
["intelligent","aqlli, zehni o'tkir","smart, clever, brilliant","Dolphins are very intelligent animals."],
["intensify","kuchaymoq, kuchaytirmoq","increase, escalate, deepen","The storm intensified overnight."],
["intent","niyat, maqsad","purpose, aim, determination","His intent was clear."],
["intercede","vositachilik qilmoq","mediate, intervene, arbitrate","She interceded on his behalf."],
["interim","vaqtinchalik, oraliq","temporary, provisional, stopgap","An interim solution was found."],
["intermittent","uzuq-yuluq, vaqti-vaqti bilan","sporadic, occasional, irregular","Intermittent showers are expected."],
["interpolate","oraliq qiymat topmoq, kiritmoq","insert, introduce, estimate","The data was interpolated."],
["interrogate","so'roq qilmoq","question, examine, grill","Police interrogated the suspect."],
["intervene","aralashmoq, to'xtatmoq","interfere, mediate, step in","The government intervened in the crisis."],
["intimate","yaqin, shaxsiy, ishora qilmoq","close, personal, hint","They are intimate friends."],
["intimidate","qo'rqitmoq","threaten, bully, frighten","He tried to intimidate witnesses."],
["intoxicate","mast qilmoq, zaharlamoq","poison, inebriate, drug","The fumes intoxicated the workers."],
["intrepid","qo'rqmas, jasur","brave, fearless, bold","The intrepid explorer crossed the desert."],
["intricate","murakkab, chigal","complex, elaborate, detailed","The design is very intricate."],
["intrigue","qiziqtirmoq, fitna","fascinate, plot, conspire","The mystery intrigued everyone."],
["intrinsic","ichki, tabiiy","inherent, natural, essential","The gem has great intrinsic value."],
["introspection","ichki mushohada, o'z-o'zini tahlil","self-examination, reflection","Introspection helps personal growth."],
["intrude","kirib kelmoq, aralashmoq","trespass, interfere, invade","Sorry to intrude on your privacy."],
["intuitive","sezgi bilan, intuitiv","instinctive, natural, innate","The design is intuitive and easy to use."],
["inundate","suv bosmoq, ko'p bermoq","flood, overwhelm, swamp","We were inundated with requests."],
["invalidate","bekor qilmoq, kuchini yo'qotmoq","nullify, cancel, annul","The new evidence invalidated the theory."],
["invariably","doimo, har doim","always, consistently, without exception","She invariably arrives on time."],
["inventory","inventar, zaxira","stock, supplies, list","The store conducted an inventory check."],
["invert","teskari aylantirmoq","reverse, flip, turn over","Invert the fraction to divide."],
["invoke","murojaat qilmoq, chaqirmoq","cite, appeal to, call upon","She invoked her constitutional rights."],
["irate","g'azablangan, jahldor","angry, furious, livid","The irate customer demanded a refund."],
["ironic","kinoyali, paradoksal","sarcastic, paradoxical, satirical","It was ironic that the lifeguard couldn't swim."],
["irreconcilable","yarashib bo'lmaydigan","incompatible, conflicting","Their differences were irreconcilable."],
["irrelevant","aloqasiz, tegishli emas","unrelated, inapplicable, immaterial","The comment was irrelevant to the topic."],
["irreparable","tuzatib bo'lmaydigan","permanent, irremediable, unrecoverable","The damage was irreparable."],
["irreversible","qaytarib bo'lmaydigan","permanent, unalterable, final","Climate change may be irreversible."],
["irrigate","sug'ormoq","water, moisten, hydrate","Farmers irrigate the fields."],
["isolate","ajratmoq, izolyatsiya qilmoq","separate, segregate, quarantine","The virus was isolated in the lab."],
["issue","masala, nashr qilmoq","matter, topic, publish","The magazine issues monthly."],
["jeopardize","xavf ostiga qo'ymoq","endanger, risk, threaten","Carelessness jeopardizes safety."],
["jubilant","xursand, xushhal","joyful, triumphant, elated","The jubilant crowd celebrated the victory."],
["judicious","oqilona, donolik bilan","wise, prudent, sensible","A judicious decision was made."],
["juxtapose","yonma-yon qo'ymoq, solishtirmoq","compare, contrast, place alongside","The exhibit juxtaposes old and new art."],
["keen","ishtiyoqli, o'tkir","eager, enthusiastic, sharp","She has a keen interest in science."],
["kindle","yoqmoq, qo'zg'atmoq","ignite, spark, arouse","The speech kindled hope in the audience."],
["kinetic","kinetik, harakаtdagi","moving, active, dynamic","Kinetic energy increases with speed."],
["knack","mahorat, udda","skill, talent, ability","She has a knack for languages."],
["labyrinth","labirint, chigal joy","maze, tangle, complex","The old city is a labyrinth of streets."],
["lackluster","xira, ta'sirsiz","dull, uninspired, mediocre","The performance was lackluster."],
["lament","qayg'urmoq, afsuslash","mourn, grieve, regret","He lamented the loss of tradition."],
["landmark","muhim voqea, ko'zga ko'ringan joy","milestone, turning point, monument","The decision was a landmark in legal history."],
["lapse","xato, vaqt o'tishi","error, slip, interval","A lapse in concentration caused the accident."],
["latent","yashirin, namoyon bo'lmagan","hidden, dormant, potential","She has latent talent for art."],
["latitude","erkinlik, kenglik","freedom, scope, leeway","Teachers have some latitude in choosing materials."],
["lavish","dabdabali, isrofgar","extravagant, luxurious, generous","The wedding was lavish."],
["legacy","meros, qoldiq","heritage, inheritance, bequest","His legacy lives on through his work."],
["legitimate","qonuniy, haqli","legal, valid, lawful","She has a legitimate complaint."],
["lenient","yumshoq, kechimli","mild, tolerant, forgiving","The teacher was lenient with grades."],
["lethal","o'ldiruvchi, halokatli","deadly, fatal, mortal","The disease can be lethal."],
["leverage","vosita, ta'sir kuchi","influence, power, advantage","Use technology as leverage for growth."],
["liable","javobgar, xavf ostida","responsible, accountable, prone","The company is liable for damages."],
["liaison","aloqa, bog'lovchi","connection, link, contact","She serves as a liaison between departments."],
["liberate","ozod qilmoq, erkin qilmoq","free, release, emancipate","The prisoners were liberated."],
["linger","qolmoq, sekin ketmoq","remain, stay, persist","Doubts lingered in his mind."],
["litigation","sudlov, sud jarayoni","lawsuit, legal case, prosecution","The litigation lasted three years."],
["livelihood","tirikchilik, kun ko'rish","living, income, sustenance","Farming is their main livelihood."],
["lobby","lobbi qilmoq, ta'sir ko'rsatmoq","campaign, advocate, influence","Groups lobbied for stricter gun laws."],
];

async function seed() {
    const SQL = await initSqlJs();
    let db;
    if (fs.existsSync(DB_PATH)) {
        const buffer = fs.readFileSync(DB_PATH);
        db = new SQL.Database(buffer);
    } else {
        db = new SQL.Database();
        db.run(`CREATE TABLE IF NOT EXISTS words (id INTEGER PRIMARY KEY AUTOINCREMENT, english TEXT NOT NULL, uzbek TEXT NOT NULL, synonyms TEXT DEFAULT '', example TEXT DEFAULT '', score INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
    }
    const existing = new Set();
    const rows = db.exec('SELECT english FROM words');
    if (rows.length > 0) rows[0].values.forEach(r => existing.add(r[0].toLowerCase()));
    let added = 0;
    const stmt = db.prepare('INSERT INTO words (english, uzbek, synonyms, example) VALUES (?, ?, ?, ?)');
    for (const [eng, uzb, syn, ex] of words) {
        if (!existing.has(eng.toLowerCase())) {
            stmt.run([eng, uzb, syn || '', ex || '']);
            existing.add(eng.toLowerCase());
            added++;
        }
    }
    stmt.free();
    const data = db.export();
    fs.writeFileSync(DB_PATH, Buffer.from(data));
    const total = db.exec('SELECT COUNT(*) FROM words');
    console.log(`${added} ta yangi so'z qo'shildi. Jami: ${total[0].values[0][0]} ta so'z.`);
    db.close();
}
seed().catch(console.error);
