const path = require('path');
const initSqlJs = require('sql.js');
const fs = require('fs');
const DB_PATH = path.join(__dirname, 'words.db');

const words = [
["lodging","turar joy, yotoqxona","accommodation, housing, shelter","The hotel provides comfortable lodging."],
["logistics","logistika, tashkiliy ishlar","planning, organization, coordination","The logistics of the event were complex."],
["longevity","uzoq umr ko'rish","long life, durability, endurance","A healthy diet promotes longevity."],
["loom","paydo bo'lmoq, tahdid solmoq","emerge, threaten, approach","Danger loomed on the horizon."],
["lucid","ravshan, aniq, hushyor","clear, coherent, rational","She gave a lucid account of events."],
["luminous","yorug', porlayotgan","bright, radiant, glowing","The luminous moon lit the sky."],
["lure","jalb qilmoq, vasvasaga solmoq","attract, entice, tempt","Low prices lure customers."],
["magnate","magnate, katta sarmoyador","tycoon, mogul, baron","The media magnate owns several newspapers."],
["magnificent","ajoyib, muhtasham","splendid, grand, superb","The view was magnificent."],
["mainstream","asosiy oqim, ommaviy","popular, conventional, dominant","The idea became mainstream."],
["malfunction","buzilish, nosozlik","breakdown, defect, failure","A malfunction caused the power outage."],
["manifest","namoyon qilmoq, ro'yxat","display, show, reveal","Her anxiety manifested as insomnia."],
["manipulate","manipulyatsiya qilmoq, boshqarmoq","control, influence, exploit","Data should not be manipulated."],
["manuscript","qo'lyozma, asl nusxa","document, script, original","The manuscript was found in the attic."],
["marginalize","chetga surib qo'ymoq","exclude, sideline, ostracize","Minority voices are often marginalized."],
["maritime","dengiz bilan bog'liq","naval, marine, nautical","Maritime trade drives the economy."],
["massacre","qirg'in, ommaviy qatl","slaughter, carnage, bloodbath","The massacre shocked the world."],
["meadow","o'tloq, yaylov","field, grassland, pasture","Flowers bloom in the meadow."],
["mediate","vositachilik qilmoq","negotiate, arbitrate, intervene","A mediator was called to help."],
["memoir","xotiralar kitobi","autobiography, journal, reminiscence","Her memoir was a bestseller."],
["menace","tahdid, xavf","threat, danger, hazard","Pollution is a menace to health."],
["mentor","ustoz, yo'l ko'rsatuvchi","guide, advisor, teacher","She became his mentor and friend."],
["merciful","rahmdil, shafqatli","compassionate, forgiving, lenient","The judge was merciful."],
["meritocracy","meritokratiya, iste'dod bo'yicha","merit-based system, fairness","Education promotes meritocracy."],
["metaphorical","majoziy, ko'chma","figurative, symbolic, allegorical","The story has metaphorical meaning."],
["methodology","metodologiya, usullar tizimi","approach, system, technique","The research methodology was rigorous."],
["meticulous","sinchkov, puxta","careful, thorough, precise","She keeps meticulous records."],
["microcosm","kichik dunyo, namuna","miniature, small-scale model","The school is a microcosm of society."],
["milestone","muhim bosqich, yutuq","landmark, achievement, turning point","Graduation is an important milestone."],
["militant","jangari, kurashchi","aggressive, combative, radical","Militant groups threatened peace."],
["mimic","taqlid qilmoq","imitate, copy, simulate","Parrots can mimic human speech."],
["minimize","kamaymoq, eng kam darajaga tushirmoq","reduce, decrease, diminish","Steps were taken to minimize risk."],
["minute","kichik, batafsil","tiny, detailed, precise","She examined every minute detail."],
["misconception","noto'g'ri tushuncha","misunderstanding, fallacy, error","It is a common misconception."],
["mitigate","yumshatmoq, kamaytirmoq","alleviate, lessen, reduce","Trees help mitigate climate change."],
["mobilize","safarbar qilmoq, harakatga keltirmoq","organize, rally, activate","The community mobilized to help."],
["moderate","o'rtacha, me'yoriy","average, reasonable, mild","Moderate exercise is recommended."],
["modify","o'zgartirmoq, tuzatmoq","change, alter, adapt","The plan was modified slightly."],
["monetary","pul bilan bog'liq","financial, fiscal, economic","Monetary policy controls inflation."],
["monitor","kuzatmoq, nazorat qilmoq","watch, observe, track","Cameras monitor the premises."],
["monopolize","monopollashtirmoq, egallamoq","dominate, control, corner","One company monopolized the market."],
["moratorium","muddatli taqiq, to'xtatish","ban, suspension, freeze","A moratorium on fishing was declared."],
["morbid","kasallikka oid, qo'rqinchli","unhealthy, gruesome, macabre","He had a morbid fascination with death."],
["mortgage","ipoteka, garovga qo'ymoq","home loan, pledge, security","They took out a mortgage."],
["motivate","rag'batlantirmoq, undamoq","inspire, encourage, drive","Good leaders motivate their teams."],
["mundane","oddiy, zerikarli","ordinary, routine, boring","She was tired of mundane tasks."],
["municipal","shahar, munitsipal","civic, local, urban","Municipal services include waste collection."],
["muster","to'plamoq, yig'moq","gather, assemble, summon","She mustered the courage to speak."],
["myriad","son-sanoqsiz, ko'p","countless, numerous, many","There are myriad options available."],
["naive","sodda, ishonuvchan","innocent, gullible, unsophisticated","She was naive about politics."],
["narrative","hikoya, rivoyat","story, account, tale","The narrative is compelling."],
["nascent","yangi paydo bo'layotgan","emerging, developing, budding","The nascent democracy faces challenges."],
["navigate","yo'l topmoq, boshqarmoq","steer, direct, guide","She navigated the ship safely."],
["necessitate","zarur qilmoq, talab qilmoq","require, demand, compel","The situation necessitated immediate action."],
["negate","bekor qilmoq, inkor qilmoq","cancel, deny, invalidate","One mistake negated all his efforts."],
["negligence","e'tiborsizlik, beparvolik","carelessness, neglect, laxity","Medical negligence can be fatal."],
["negotiate","muzokara olib bormoq","discuss, bargain, mediate","The two sides negotiated a deal."],
["nepotism","tanish-bilishchilik","favoritism, cronyism, bias","Nepotism undermines fair hiring practices."],
["niche","o'z joyi, tor soha","specialty, market segment","She found her niche in technology."],
["nocturnal","tungi, kechasi faol","nighttime, night-active","Owls are nocturnal creatures."],
["nomadic","ko'chmanchi","wandering, roaming, traveling","Nomadic tribes move with the seasons."],
["nominal","nominal, ahamiyatsiz","token, minimal, symbolic","He paid a nominal fee."],
["nonchalant","befarq, xotirjam","casual, indifferent, calm","She appeared nonchalant about the news."],
["norm","me'yor, standart","standard, rule, benchmark","Cultural norms vary by country."],
["nostalgia","sog'inch, o'tmishni sog'inish","longing, wistfulness, yearning","She felt nostalgia for her childhood."],
["notable","e'tiborli, taniqli","remarkable, significant, famous","Several notable figures attended."],
["notorious","yomon nom chiqargan","infamous, disreputable","The criminal is notorious for violence."],
["novel","yangi, noodatiy, roman","new, original, innovative","The approach was novel and effective."],
["novice","yangi boshlovchi","beginner, newcomer, amateur","She is a novice in programming."],
["nuance","noziklik, ingichkalik","subtlety, shade, distinction","Every nuance of the language matters."],
["nullify","bekor qilmoq, haqiqiy emas deb topmoq","invalidate, cancel, annul","The decision was nullified."],
["nurture","parvarish qilmoq, tarbiyalamoq","raise, foster, cultivate","Education nurtures young minds."],
["obedient","itoatkor, so'z oluvchi","compliant, dutiful, submissive","The dog is very obedient."],
["objective","maqsad, xolis","goal, aim, unbiased","Remain objective in your analysis."],
["obligatory","majburiy, shart","compulsory, mandatory, required","Attendance is obligatory."],
["oblige","majburlamoq, minnatdor qilmoq","compel, force, accommodate","I am obliged to report the incident."],
["oblique","qiyshiq, yashirin","indirect, slanting, evasive","She made an oblique reference."],
["obscure","noaniq, kam tanilgan","unclear, unknown, vague","The artist remained obscure."],
["obsolete","eskirgan, foydalanilmaydigan","outdated, defunct, antiquated","The technology is now obsolete."],
["obstacle","to'siq, g'ov","barrier, hindrance, impediment","Poverty is an obstacle to education."],
["obstinate","qaysar, o'jar","stubborn, persistent, headstrong","He was obstinate about his views."],
["obtain","olmoq, ega bo'lmoq","get, acquire, gain","She obtained a degree in law."],
["obvious","aniq, ravshan","clear, evident, apparent","The answer is obvious."],
["occupy","egallamoq, band bo'lmoq","inhabit, fill, engage","The army occupied the territory."],
["occur","sodir bo'lmoq, yuz bermoq","happen, take place, arise","Accidents occur more frequently at night."],
["omission","tushirib qoldirish, kamchilik","exclusion, oversight, gap","The omission was unintentional."],
["onerous","og'ir, mashaqqatli","burdensome, demanding, difficult","The task was onerous."],
["onset","boshlanish, paydo bo'lish","start, beginning, commencement","The onset of winter was early."],
["opaque","noshaffof, tushunarsiz","cloudy, unclear, obscure","The glass was opaque."],
["operate","ishlamoq, boshqarmoq","run, function, manage","The machine operates automatically."],
["opponent","raqib, dushman","rival, adversary, competitor","She defeated her opponent easily."],
["opportune","qulay, o'z vaqtida","timely, favorable, appropriate","It was an opportune moment to act."],
["optimal","eng yaxshi, ideal","best, perfect, ideal","Find the optimal solution."],
["opulent","dabdabali, hashamatli","luxurious, lavish, rich","The opulent palace amazed visitors."],
["orbit","orbita, aylanish","path, circuit, revolution","The satellite orbits the earth."],
["ordain","tayinlamoq, buyurmoq","decree, command, appoint","The law was ordained by the king."],
["originate","kelib chiqmoq, paydo bo'lmoq","begin, start, emerge","The tradition originated centuries ago."],
["ornate","bezatilgan, dabdabali","decorated, elaborate, fancy","The ornate ceiling was impressive."],
["orthodox","an'anaviy, qabul qilingan","traditional, conventional, standard","He holds orthodox religious views."],
["oscillate","tebranmoq, o'zgarib turmoq","swing, fluctuate, vary","Prices oscillate throughout the year."],
["ostensible","ko'rinishdagi, gumonli","apparent, seeming, alleged","The ostensible purpose was charity."],
["ostentatious","ko'z-ko'z qiladigan, maqtanchoq","showy, flashy, pretentious","His ostentatious lifestyle was criticized."],
["oust","ag'darmoq, haydab chiqarmoq","remove, expel, overthrow","The CEO was ousted by the board."],
["outburst","portlash, to'satdan chiqish","explosion, eruption, outbreak","His outburst surprised everyone."],
["outcome","natija, oqibat","result, consequence, effect","The outcome exceeded expectations."],
["outlaw","qonundan tashqari, taqiqlamoq","ban, prohibit, criminal","The practice was outlawed in 2010."],
["outrage","g'azab, dahshat","anger, fury, indignation","The decision caused public outrage."],
["outskirts","shahar chekkasi, atrofi","suburbs, periphery, edge","They live on the outskirts of the city."],
["outstanding","ajoyib, to'lanmagan","excellent, remarkable, unpaid","She did outstanding work."],
["overcome","yengmoq, engmoq","defeat, conquer, surmount","She overcame many challenges."],
["overlook","e'tiborsiz qoldirmoq, ko'rinish","ignore, miss, view","Do not overlook the small details."],
["oversee","nazorat qilmoq, boshqarmoq","supervise, manage, monitor","She oversees the entire project."],
["overt","ochiq, yashirilmagan","open, public, visible","There was no overt hostility."],
["overthrow","ag'darmoq, to'ntarish","topple, oust, depose","The regime was overthrown."],
["overwhelm","bosib olmoq, ortiqcha bo'lmoq","overpower, swamp, engulf","She was overwhelmed by emotions."],
["pacify","tinchitmoq, xotirjam qilmoq","calm, soothe, appease","The government tried to pacify the protesters."],
["pact","shartnoma, bitim","agreement, treaty, deal","The countries signed a peace pact."],
["painstaking","puxta, sinchkov","careful, meticulous, thorough","The research involved painstaking work."],
["palatable","mazali, qabul qilinadigan","tasty, acceptable, agreeable","The proposal was palatable to both sides."],
["palpable","sezilarli, aniq","obvious, noticeable, tangible","Tension in the room was palpable."],
["panacea","har dardga davo","cure-all, remedy, solution","There is no panacea for poverty."],
["pandemic","pandemiya, umumjahon tarqalish","epidemic, outbreak, plague","The pandemic affected every country."],
["paradigm","paradigma, namuna","model, pattern, example","A paradigm shift occurred in science."],
["paramount","eng muhim, ustun","supreme, chief, foremost","Safety is of paramount importance."],
["paraphrase","boshqacha ifodalash","restate, rephrase, reword","Paraphrase the author's argument."],
["parcel","posilka, qism","package, portion, plot","She received a parcel in the mail."],
["pardon","kechirim, avf etmoq","forgiveness, amnesty, excuse","The governor granted a pardon."],
["partisan","tarafdor, partiyachi","biased, one-sided, supporter","The report was highly partisan."],
["patronize","homiylik qilmoq, kamsitmoq","support, condescend, sponsor","Do not patronize your colleagues."],
["peculiar","g'alati, o'ziga xos","strange, odd, unique","There was something peculiar about him."],
["pedagogy","pedagogika, o'qitish ilmi","teaching, education, instruction","Progressive pedagogy encourages creativity."],
["peer","tengdosh, teng","equal, colleague, contemporary","She is respected by her peers."],
["penalize","jazolamoq, jarima solmoq","punish, fine, discipline","Students are penalized for late submissions."],
["pending","kutilayotgan, hal etilmagan","awaiting, outstanding, undecided","Several cases are still pending."],
["penetrate","ichiga kirmoq, singmoq","enter, pierce, permeate","The bullet penetrated the wall."],
["perceive","sezmoq, idrok etmoq","notice, sense, understand","How do you perceive the situation?"],
["perennial","doimiy, ko'p yillik","constant, enduring, recurring","Poverty is a perennial problem."],
["peril","xavf, xatar","danger, risk, jeopardy","The expedition was fraught with peril."],
["periphery","chekka, atrofi","edge, outskirts, margin","People on the periphery of society."],
["permeate","singib kirmoq, tarqalmoq","spread, infiltrate, pervade","The smell permeated the room."],
["perpetrate","sodir etmoq (jinoyat)","commit, carry out, execute","Who perpetrated this crime?"],
["perpetuate","davom ettirmoq, saqlab qolmoq","maintain, preserve, prolong","Stereotypes perpetuate inequality."],
["perplexing","gangituvchi, hayratlanarli","confusing, puzzling, baffling","The results were perplexing."],
["persecute","ta'qib qilmoq, azob bermoq","oppress, torment, harass","Minorities were persecuted under the regime."],
["persevere","qat'iyat bilan davom etmoq","persist, continue, endure","She persevered despite difficulties."],
["perspective","nuqtai nazar, istiqbol","viewpoint, outlook, angle","Try to see things from a different perspective."],
["persuade","ko'ndirmoq, ishontirmoq","convince, influence, sway","She persuaded him to stay."],
["pertain","tegishli bo'lmoq, aloqador","relate, concern, apply","The rules pertain to all students."],
["pervasive","keng tarqalgan, hamma joyda","widespread, prevalent, ubiquitous","Technology is pervasive in modern life."],
["pessimism","pessimizm, badbin","negativity, despair, gloom","Pessimism about the economy grew."],
["petition","ariza, murojaat","appeal, request, plea","They signed a petition for reform."],
["philanthropist","xayriyachi, saxovatli odam","donor, benefactor, patron","The philanthropist donated millions."],
["pillar","ustun, tayanch","column, support, foundation","Education is a pillar of society."],
["pinnacle","cho'qqi, eng yuqori nuqta","peak, summit, apex","She reached the pinnacle of her career."],
["pioneer","kashshof, birinchi bo'lmoq","innovator, trailblazer, founder","She pioneered new teaching methods."],
["pious","taqvodor, dindor","religious, devout, faithful","He leads a pious life."],
["pivotal","hal qiluvchi, muhim","crucial, key, central","It was a pivotal moment in history."],
["placate","tinchitmoq, xotirjam qilmoq","calm, soothe, appease","He tried to placate the angry crowd."],
["plagiarism","plagiat, ko'chirmachilik","copying, theft, fraud","Plagiarism is unacceptable in academia."],
["plausible","ishonchli, mantiqiy","believable, credible, reasonable","The explanation was plausible."],
["plead","yolvormoq, iltimos qilmoq","beg, appeal, implore","He pleaded for mercy."],
["pledge","va'da bermoq, qasamyod","promise, vow, commit","She pledged to support the cause."],
["plethora","ko'pchilik, ortiqchalik","excess, abundance, surplus","There is a plethora of choices."],
["plight","qiyin ahvol, og'ir vaziyat","predicament, trouble, difficulty","The plight of refugees is heartbreaking."],
["plunge","sho'ng'imoq, keskin tushmoq","dive, fall, drop","Stock prices plunged suddenly."],
["poignant","ta'sirli, yurakni ezuvchi","moving, touching, emotional","She told a poignant story."],
["polarize","bo'linish, qarama-qarshi qilmoq","divide, split, separate","The issue polarized the country."],
["polemic","munozara, ziddiyatli bahsь","argument, debate, controversy","The article was a polemic against the government."],
["ponder","o'ylamoq, mulohaza qilmoq","think, consider, contemplate","She pondered the question carefully."],
["populace","aholi, xalq","population, public, citizens","The populace demanded change."],
["portray","tasvirlamoq, ifodalash","depict, represent, describe","The film portrays wartime life."],
["posterity","avlodlar, kelajak","future generations, descendants","We must preserve nature for posterity."],
["postpone","kechiktirmoq, qoldirmoq","delay, defer, put off","The concert was postponed."],
["potent","kuchli, ta'sirli","powerful, strong, effective","The drug is very potent."],
["pragmatic","amaliy, real","practical, realistic, sensible","A pragmatic approach is needed."],
["precaution","ehtiyot chorasi","safety measure, prevention","Take precautions against the cold."],
["precedent","oldingi misol, pretsedent","example, standard, model","The ruling set a legal precedent."],
["precipitate","tezlashtirmoq, sabab bo'lmoq","hasten, trigger, cause","The crisis precipitated his resignation."],
["precise","aniq, to'g'ri","exact, accurate, specific","The measurements must be precise."],
["preclude","oldini olmoq, to'sqinlik qilmoq","prevent, exclude, hinder","Heavy rain precluded outdoor activities."],
["predecessor","oldingi, avvalgi shaxs","forerunner, antecedent, precursor","Her predecessor served for ten years."],
["predicament","qiyin vaziyat","dilemma, difficulty, trouble","He found himself in a predicament."],
["predominant","ustun, asosiy","dominant, main, prevailing","English is the predominant language."],
["preeminent","eng yaxshi, eng ustun","outstanding, supreme, leading","She is preeminent in her field."],
["premise","asos, binolar","basis, foundation, assumption","The argument rests on a false premise."],
["premium","mukofot, sifatli","reward, high-quality, bonus","Customers pay a premium for quality."],
["preoccupation","band bo'lish, fikrdan ketmaslik","obsession, concern, distraction","His preoccupation with work worried his family."],
["prerequisite","oldindan shart","requirement, condition, necessity","Experience is a prerequisite for the job."],
["prescribe","buyurmoq, belgilamoq","order, recommend, dictate","The doctor prescribed medication."],
["prevalent","keng tarqalgan","common, widespread, frequent","The disease is prevalent in tropical areas."],
["prevent","oldini olmoq, to'xtatmoq","stop, avoid, hinder","Vaccines prevent diseases."],
["primitive","ibtidoiy, oddiy","basic, early, rudimentary","Primitive tools were made of stone."],
["principle","tamoyil, qoida","rule, law, standard","Freedom of speech is a basic principle."],
["priority","ustuvorlik, birinchi darajalilik","precedence, importance, preference","Safety is our top priority."],
["privilege","imtiyoz, afzallik","advantage, benefit, right","Education is a privilege."],
["probe","tekshirmoq, zondlamoq","investigate, examine, explore","Police probed the crime scene."],
["procrastinate","kechiktirmoq, sudrash","delay, postpone, defer","Stop procrastinating and start working."],
["prodigious","ulkan, ajoyib","enormous, impressive, remarkable","She has prodigious talent."],
["profound","chuqur, ta'sirli","deep, intense, significant","The book had a profound impact."],
["prohibit","taqiqlamoq, man qilmoq","ban, forbid, prevent","Smoking is prohibited indoors."],
["proliferate","ko'paymoq, tez tarqalmoq","increase, multiply, spread","Fake news proliferates online."],
["prolific","serhosil, ko'p yaratuvchi","productive, fertile, creative","She is a prolific writer."],
["prolong","uzaytirmoq, cho'zmoq","extend, lengthen, stretch","Do not prolong the meeting unnecessarily."],
["prominent","taniqli, ko'zga tashlanadigan","famous, notable, distinguished","She is a prominent scientist."],
["promote","rag'batlantirmoq, targ'ib qilmoq","encourage, advance, advertise","The campaign promotes healthy eating."],
["prompt","tezkor, undamoq","quick, immediate, motivate","Prompt action prevented the disaster."],
["prone","moyil, yuz tuban","inclined, susceptible, likely","The area is prone to flooding."],
["propaganda","tashviqot, propaganda","publicity, misinformation, promotion","Propaganda shaped public opinion."],
["propel","harakatga keltirmoq, undamoq","drive, push, motivate","Ambition propelled her forward."],
["proponent","tarafdor, himoyachi","supporter, advocate, champion","He is a proponent of free trade."],
["proposition","taklif, fikr","proposal, suggestion, idea","The proposition was debated."],
["propriety","odob, muvofiiqlik","decency, correctness, etiquette","She acted with propriety."],
["prosecute","sudga bermoq, ayblamoq","charge, indict, try","The state decided to prosecute."],
["prosperity","farovonlik, boylik","wealth, success, affluence","Peace brings prosperity."],
["protagonist","bosh qahramon","hero, lead, main character","The protagonist overcomes many challenges."],
["protest","norozilik, e'tiroz","objection, demonstration, opposition","Thousands joined the protest."],
["protocol","bayonnoma, tartib-qoida","procedure, rules, etiquette","Follow the safety protocol."],
["provenance","kelib chiqishi, asl joyi","origin, source, history","The provenance of the painting is uncertain."],
["provoke","g'azablantirmoq, sabab bo'lmoq","irritate, incite, trigger","His words provoked an angry reaction."],
["proximity","yaqinlik","nearness, closeness, vicinity","The school is in close proximity to the park."],
["prudent","ehtiyotkor, oqilona","wise, cautious, sensible","A prudent investor diversifies."],
["pseudonym","taxallus, soxta ism","alias, pen name, nickname","She wrote under a pseudonym."],
["purport","da'vo qilmoq, maqsad","claim, allege, profess","The document purports to be genuine."],
["pursue","quvmoq, izlamoq","follow, chase, seek","She pursued a career in medicine."],
["qualitative","sifatiy, miqdoriy emas","quality-based, subjective, descriptive","Qualitative research explores experiences."],
["quantify","miqdorini aniqlash","measure, calculate, count","It is hard to quantify happiness."],
["quarantine","karantin, ajratish","isolation, lockdown, seclusion","The city was placed under quarantine."],
["quest","izlanish, qidiruv","search, pursuit, mission","The quest for knowledge continues."],
["quota","kvota, belgilangan miqdor","limit, share, allocation","Each country has an import quota."],
["radical","tubdan, radikal","extreme, fundamental, drastic","Radical reforms are needed."],
["ramification","oqibat, natija","consequence, implication, effect","The ramifications of the decision were serious."],
["rampant","keng tarqalgan, jilovlanmas","widespread, uncontrolled, rife","Corruption was rampant."],
["rationale","asos, sabab","reason, logic, justification","What is the rationale behind the decision?"],
["realm","soha, mamlakat","domain, kingdom, sphere","She is an expert in the realm of finance."],
["rebuke","tanbeh bermoq, koyimoq","scold, reprimand, criticize","The manager rebuked him for the error."],
["reckon","hisoblash, o'ylamoq","calculate, think, estimate","I reckon the project will take a month."],
["reconcile","yarashmoq, moslash","settle, resolve, harmonize","They reconciled after the argument."],
["redundant","ortiqcha, keraksiz","unnecessary, surplus, superfluous","Some positions were made redundant."],
["refute","rad etmoq, inkor qilmoq","disprove, counter, deny","She refuted the allegations."],
["regime","rejim, tuzum","government, system, administration","The new regime introduced reforms."],
["rehabilitate","tiklamoq, qayta tarbiyalamoq","restore, recover, reform","The program rehabilitates offenders."],
["reimburse","qaytarib bermoq, tovon to'lamoq","repay, compensate, refund","The company reimbursed travel costs."],
["reinstate","qayta tiklamoq, lavozimga qaytarmoq","restore, return, reestablish","He was reinstated after the investigation."],
["reiterate","takrorlamoq, qayta ta'kidlamoq","repeat, restate, emphasize","Let me reiterate the main point."],
["relegate","pasaytirmoq, chetga surib qo'ymoq","demote, downgrade, assign","The issue was relegated to a footnote."],
["relinquish","voz kechmoq, bo'shatmoq","surrender, give up, abandon","She relinquished her position."],
["reluctant","istamaydigan, ikkilanuvchi","unwilling, hesitant, resistant","He was reluctant to change."],
["remedy","davo, yechim","cure, solution, fix","Exercise is a good remedy for stress."],
["remorse","pushaymonlik, afsus","regret, guilt, sorrow","He felt deep remorse for his actions."],
["renaissance","uyg'onish, qayta tiklash","rebirth, revival, renewal","The city is experiencing a cultural renaissance."],
["renounce","voz kechmoq, rad etmoq","give up, abandon, reject","He renounced his claim to the throne."],
["renovate","ta'mirlamoq, yangilamoq","restore, refurbish, repair","They renovated the old house."],
["renowned","mashhur, taniqli","famous, celebrated, distinguished","He is a renowned scientist."],
["repeal","bekor qilmoq (qonun)","revoke, cancel, annul","The law was repealed."],
["repercussion","oqibat, ta'sir","consequence, result, effect","The decision had serious repercussions."],
["replenish","to'ldirmoq, yangilamoq","refill, restock, restore","We need to replenish our supplies."],
["replicate","takrorlamoq, nusxa olmoq","copy, duplicate, reproduce","The experiment was replicated successfully."],
["repository","saqlash joyi, ombor","storage, archive, vault","The library is a repository of knowledge."],
["repression","bostiruv, qatag'on","suppression, oppression, control","Political repression increased."],
["reproach","ta'na qilmoq, ayblamoq","blame, criticize, scold","She reproached him for being late."],
["reproduce","ko'paytirmoq, qayta ishlab chiqarmoq","copy, replicate, breed","The results could not be reproduced."],
["repudiate","rad etmoq, inkor qilmoq","reject, deny, disown","She repudiated the accusations."],
["reputable","obro'li, ishonchli","respected, trustworthy, reliable","Buy from a reputable company."],
["requisite","zaruriy, kerakli","required, necessary, essential","The requisite skills were listed."],
["rescind","bekor qilmoq, qaytarib olmoq","cancel, revoke, annul","The order was rescinded."],
["resemble","o'xshamoq","look like, be similar to","She resembles her mother."],
["resent","ranjish, xafa bo'lmoq","dislike, begrudge, object to","He resented the criticism."],
["residual","qoldiq, ortiqcha","remaining, leftover, surplus","Residual effects lasted for months."],
["resign","iste'foga chiqmoq","quit, leave, step down","She resigned from her position."],
];

async function seed() {
    const SQL = await initSqlJs();
    let db;
    if (fs.existsSync(DB_PATH)) {
        const buffer = fs.readFileSync(DB_PATH);
        db = new SQL.Database(buffer);
    } else {
        db = new SQL.Database();
        db.run(`CREATE TABLE IF NOT EXISTS words (id INTEGER PRIMARY KEY AUTOINCREMENT, english TEXT NOT NULL, uzbek TEXT NOT NULL, synonyms TEXT DEFAULT '', example TEXT DEFAULT '', score INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
    }
    const existing = new Set();
    const rows = db.exec('SELECT english FROM words');
    if (rows.length > 0) rows[0].values.forEach(r => existing.add(r[0].toLowerCase()));
    let added = 0;
    const stmt = db.prepare('INSERT INTO words (english, uzbek, synonyms, example) VALUES (?, ?, ?, ?)');
    for (const [eng, uzb, syn, ex] of words) {
        if (!existing.has(eng.toLowerCase())) {
            stmt.run([eng, uzb, syn || '', ex || '']);
            existing.add(eng.toLowerCase());
            added++;
        }
    }
    stmt.free();
    const data = db.export();
    fs.writeFileSync(DB_PATH, Buffer.from(data));
    const total = db.exec('SELECT COUNT(*) FROM words');
    console.log(`${added} ta yangi so'z qo'shildi. Jami: ${total[0].values[0][0]} ta so'z.`);
    db.close();
}
seed().catch(console.error);
