const path = require('path');
const initSqlJs = require('sql.js');
const fs = require('fs');

const DB_PATH = path.join(__dirname, 'words.db');

const words = [
// ===== ADVANCED ACADEMIC =====
["laborious","mashaqqatli, qiyin","difficult, hard, strenuous","The laborious task took weeks to complete."],
["lament","qayg'urmoq, motam tutmoq","mourn, grieve, regret","She lamented the loss of her old home."],
["latitude","erkinlik, kenglik","freedom, leeway, scope","Teachers are given latitude in choosing methods."],
["laudable","maqtovga loyiq","praiseworthy, commendable, admirable","The charity's work is highly laudable."],
["legacy","meros, qoldiriq","heritage, inheritance, bequest","His legacy continues to inspire people."],
["lenient","yumshoq, kechimli","mild, tolerant, merciful","The judge was lenient with the first offender."],
["leverage","ta'sir kuchi, vosita","influence, power, advantage","She used her contacts as leverage."],
["liaison","aloqa, bog'lovchi","connection, link, intermediary","He serves as a liaison between the departments."],
["liberate","ozod qilmoq","free, release, emancipate","The country was liberated from colonial rule."],
["linger","qolmoq, kechikmoq","remain, stay, persist","The smell of cooking lingered in the air."],
["literacy","savodxonlik","reading ability, education, learning","Adult literacy programs help many people."],
["litigate","sudlashmoq","sue, prosecute, take to court","She decided to litigate the matter."],
["locomotion","harakatlanish","movement, motion, travel","Legs are used for locomotion."],
["lofty","baland, ulug'","high, elevated, grand","He has lofty ambitions."],
["longevity","umr davomiyligi","long life, durability","Good health contributes to longevity."],
["loophole","bo'shliq, nuqson","gap, flaw, weakness","Lawyers found a loophole in the contract."],
["lucid","ravshan, aniq","clear, coherent, rational","She gave a lucid explanation."],
["magnify","kattalashtirmoq","enlarge, amplify, increase","The microscope magnifies objects 100 times."],
["malicious","yomon niyatli, zararli","harmful, spiteful, malevolent","The malicious software damaged the computer."],
["mandate","mandat, buyruq","order, directive, authorization","The president has a mandate to reform."],
["manifest","namoyon bo'lmoq, aniq ko'rinadigan","show, display, evident","Her talent was manifest from an early age."],
["marginalize","chetga surib qo'ymoq","exclude, sideline, ignore","Minority groups are often marginalized."],
["meager","oz, yetarli bo'lmagan","scanty, insufficient, sparse","His meager salary barely covered expenses."],
["mediate","vositachilik qilmoq","negotiate, arbitrate, intercede","She mediated between the two parties."],
["memoir","xotira, esdalik","autobiography, recollection, journal","Her memoir became a bestseller."],
["menace","tahdid, xavf","threat, danger, hazard","Pollution is a menace to public health."],
["mentor","ustoz, murabbiy","guide, teacher, advisor","She found a mentor in her professor."],
["mercenary","yollanma askar, pulga ishlaydigan","hired soldier, greedy, money-driven","He was accused of having mercenary motives."],
["meticulous","puxta, sinchkov","careful, precise, thorough","She kept meticulous records."],
["militant","jangari, kurashchi","aggressive, combative, radical","Militant groups opposed the government."],
["mitigate","yumshatmoq, kamaytirmoq","alleviate, reduce, lessen","Measures were taken to mitigate the damage."],
["mobilize","safarbar qilmoq","organize, rally, assemble","The community mobilized to help flood victims."],
["momentum","tezlik, kuch","force, drive, impetus","The campaign gained momentum."],
["monopolize","monopollashtirmoq","dominate, control, corner","One company monopolized the industry."],
["moratorium","moratoriy, to'xtash","ban, freeze, suspension","A moratorium on nuclear testing was declared."],
["mundane","oddiy, zerikarli","ordinary, boring, routine","She was tired of mundane tasks."],
["nascent","yangi paydo bo'layotgan","emerging, budding, developing","The nascent industry shows great promise."],
["negate","inkor qilmoq","deny, invalidate, cancel","The new evidence negated his claim."],
["negligent","e'tiborsiz, beparvo","careless, irresponsible, lax","The doctor was negligent in his duties."],
["nominal","nominal, juda oz","minimal, token, symbolic","He paid a nominal fee for the service."],
["nonchalant","befarq, loqayd","casual, indifferent, relaxed","She remained nonchalant about the criticism."],
["nostalgia","sog'inch, o'tmishni sog'inish","longing, homesickness, wistfulness","He felt nostalgia for his childhood home."],
["novice","yangi boshlovchi","beginner, newcomer, amateur","She is a novice at cooking."],
["noxious","zararli, zaharli","harmful, toxic, poisonous","Noxious fumes filled the factory."],
["nullify","bekor qilmoq","invalidate, cancel, annul","The court nullified the contract."],
["nurture","tarbiyalamoq, parvarish qilmoq","raise, foster, cultivate","Parents nurture their children's growth."],
["oblivious","bexabar, befahr","unaware, ignorant, unconscious","He was oblivious to the danger around him."],
["obscure","noaniq, yashirin","unclear, hidden, vague","The meaning of the text is obscure."],
["obsolete","eskirgan, foydalanilmaydigan","outdated, old, defunct","Typewriters have become obsolete."],
["obstruct","to'sib qo'ymoq","block, hinder, impede","The fallen tree obstructed the road."],
["omnipresent","hamma joyda mavjud","ubiquitous, everywhere, pervasive","Technology is omnipresent in modern life."],
["onset","boshlanish","start, beginning, commencement","The onset of winter brought cold weather."],
["opaque","noshaffof, tushunarsiz","cloudy, unclear, impenetrable","The glass was opaque."],
["optimism","optimizm, nikbinlik","hope, positivity, confidence","There is growing optimism about the economy."],
["orchestrate","tashkil etmoq, boshqarmoq","organize, arrange, coordinate","She orchestrated the entire event."],
["ordeal","og'ir sinov","trial, hardship, suffering","The hostages went through a terrible ordeal."],
["orthodox","an'anaviy, ortodoks","traditional, conventional, established","He has orthodox views on education."],
["ostensible","ko'rinishda, gumonli","apparent, seeming, professed","The ostensible reason for his visit was business."],
["outweigh","ustun kelmoq, og'ir bo'lmoq","exceed, surpass, override","The benefits outweigh the risks."],
["overt","ochiq, yashirilmagan","open, obvious, public","There was overt hostility between them."],
["overwhelm","bosib olmoq, bostirmoq","overpower, engulf, swamp","The task overwhelmed her."],

// ===== IELTS SPEAKING/WRITING USEFUL WORDS =====
["abandon","tark etmoq","leave, forsake, desert","He abandoned his old habits."],
["abet","yordam bermoq (yomon ishga)","assist, aid, encourage","She was charged with abetting the crime."],
["abolition","bekor qilish, tugatish","ending, elimination, cancellation","The abolition of slavery was a turning point."],
["abound","mo'l bo'lmoq, ko'p bo'lmoq","overflow, teem, flourish","Fish abound in the lake."],
["abrasive","qo'pol, dag'al","rough, harsh, coarse","His abrasive manner upset colleagues."],
["abridge","qisqartirmoq","shorten, condense, summarize","The book was abridged for young readers."],
["absolve","gunohini kechirmoq","forgive, pardon, clear","The court absolved him of all charges."],
["abstinence","o'zini tiyish","self-denial, restraint, temperance","Abstinence from alcohol improved his health."],
["accentuate","ta'kidlamoq, kuchaytirmoq","emphasize, highlight, stress","The lighting accentuated the painting's colors."],
["acclaim","e'tirof etmoq, maqtamoq","praise, applaud, honor","The film received critical acclaim."],
["acclimatize","iqlimga moslashmoq","adapt, adjust, get used to","It takes time to acclimatize to the altitude."],
["accomplice","sherik (jinoyatda)","partner, associate, accessory","He was identified as the accomplice."],
["accrue","to'planmoq, yig'ilmoq","accumulate, build up, gather","Benefits accrue over time."],
["adamant","qat'iy, o'zgarmas","firm, insistent, unyielding","She is adamant about her decision."],
["adequate","yetarlicha","sufficient, enough, satisfactory","The salary was barely adequate."],
["adhere","yopishmoq, rioya qilmoq","stick, follow, comply","Please adhere to the guidelines."],
["adjacent","yondosh, yaqin","next to, near, bordering","The park is adjacent to the library."],
["adjunct","qo'shimcha, yordamchi","addition, supplement, accessory","The course is an adjunct to the main program."],
["admonish","ogohlantirmoq, tanbeh bermoq","warn, caution, reprimand","The teacher admonished the student for being late."],
["adversarial","dushmаnona, qarama-qarshi","hostile, opposing, antagonistic","The adversarial system ensures fair trials."],
["affable","xushmuomala, ochiq","friendly, amiable, warm","The host was affable and welcoming."],
["affiliation","a'zolik, bog'liqlik","association, connection, membership","His affiliation with the party is well known."],
["agglomeration","to'planish, yig'ilish","cluster, collection, accumulation","The city is an agglomeration of diverse neighborhoods."],
["aggregate","umumiy, jami","total, combined, collective","The aggregate data shows improvement."],
["aggrieved","xafa, ranjigan","offended, hurt, wronged","The aggrieved party filed a complaint."],
["allegation","ayblov, da'vo","accusation, claim, charge","The allegations were investigated thoroughly."],
["allocate","taqsimlamoq, ajratmoq","distribute, assign, allot","Funds were allocated for research."],
["aloof","uzoq, sovuqqon","distant, detached, remote","He remained aloof from the group."],
["altercation","janjal, tortishuv","quarrel, dispute, argument","An altercation broke out in the street."],
["amalgamation","birlashuv, qo'shilish","merger, union, combination","The amalgamation of the two firms was announced."],
["ambiguity","noaniqlik, ikki xillik","uncertainty, vagueness, doubt","The ambiguity of the law caused confusion."],
["amicable","do'stona, tinchlik bilan","friendly, cordial, harmonious","They reached an amicable agreement."],
["amplify","kuchaytirmoq, kengaytirmoq","increase, boost, magnify","The speaker amplified her voice with a microphone."],
["analogous","o'xshash, analogik","similar, comparable, parallel","The two situations are analogous."],
["annex","qo'shib olmoq, ilova","attach, add, incorporate","The country annexed the disputed territory."],
["annihilate","butunlay yo'q qilmoq","destroy, eliminate, wipe out","The disease annihilated the population."],
["annotate","izoh yozmoq, sharh bermoq","note, comment, explain","She annotated the margins of the book."],
["anomalous","g'ayrioddiy, normadan chetga chiqqan","abnormal, unusual, irregular","The results were anomalous."],
["antagonize","dushmanlik qilmoq, g'azablantirmoq","provoke, irritate, anger","His remarks antagonized the audience."],
["antithesis","qarama-qarshilik, antonim","opposite, contrast, reverse","War is the antithesis of peace."],
["apathetic","befarq, loqayd","indifferent, unconcerned, passive","The public was apathetic about the election."],
["apportion","taqsimlamoq, bo'lib bermoq","divide, distribute, allocate","Blame was apportioned equally."],
["appraise","baholamoq","evaluate, assess, value","The house was appraised at $500,000."],
["apprehensive","xavotirli, tashvishli","anxious, worried, nervous","She was apprehensive about the exam results."],
["arbitrary","ixtiyoriy, asossiz","random, capricious, subjective","The decision was completely arbitrary."],
["articulate","aniq gapirmoq","express, enunciate, verbalize","He articulated his views clearly."],
["ascendancy","ustunlik, hukmronlik","dominance, supremacy, control","The party gained ascendancy over its rivals."],
["aspiration","intilish, orzu","ambition, goal, dream","Her aspiration is to become a lawyer."],
["assimilate","singdirmoq, o'zlashmoq","absorb, integrate, adapt","Newcomers gradually assimilate into the culture."],
["atone","gunohini yuvmoq","compensate, make amends, repent","He tried to atone for his mistakes."],
["attenuate","kuchsizlantirmoq, kamaytirmoq","weaken, reduce, diminish","The signal attenuates over distance."],
["audacity","jasurlik, surbet","boldness, daring, nerve","She had the audacity to challenge the boss."],
["augment","oshirmoq, kuchaytirmoq","increase, supplement, boost","Technology augments human capabilities."],
["auspicious","omadli, qulay","favorable, promising, good","The meeting had an auspicious beginning."],
["authentic","haqiqiy, asl","genuine, real, true","The document is authentic."],
["authoritarian","avtoritar, diktatorlik","dictatorial, oppressive, strict","The authoritarian regime silenced opposition."],
["autonomous","mustaqil, avtonom","independent, self-governing, free","The region became autonomous."],
["avert","oldini olmoq, yo'naltirmoq","prevent, avoid, deflect","Disaster was narrowly averted."],
["avid","ishtiyoqli, jon kuydiruvchi","keen, enthusiastic, passionate","She is an avid reader."],
["backlash","teskari ta'sir, qarshilik","reaction, repercussion, resistance","The policy provoked a public backlash."],
["baffle","hayratda qoldirmoq, gangitmoq","puzzle, confuse, perplex","The mystery continues to baffle scientists."],
["bane","balo, ofat","curse, plague, scourge","Corruption is the bane of development."],
["barren","hosil bermaydigan, qurg'oq","infertile, unproductive, desolate","The land was barren and dry."],
["bellicose","jangari, urushqoq","aggressive, warlike, hostile","The bellicose rhetoric alarmed the world."],
["benign","zararsiz, yumshoq","harmless, gentle, mild","The tumor was benign."],
["besiege","qamal qilmoq","surround, blockade, encircle","Reporters besieged the politician."],
["bias","noxolislik, tarafkashlik","prejudice, partiality, favoritism","The study was free from bias."],
["bland","mazasiz, oddiygina","dull, tasteless, unremarkable","The speech was bland and forgettable."],
["blatant","ochiqdan-ochiq","obvious, flagrant, brazen","It was a blatant lie."],
["bliss","baxt, saodаt","happiness, joy, ecstasy","Ignorance is bliss."],
["blunder","qo'pol xato","mistake, error, gaffe","The politician made a terrible blunder."],
["bolster","mustahkamlamoq, qo'llab-quvvatlamoq","support, strengthen, reinforce","New evidence bolstered the theory."],
["bombard","bombardimon qilmoq, bosim o'tkazmoq","attack, shell, assault","They were bombarded with questions."],
["bonanza","katta omad, boylik","windfall, fortune, jackpot","The oil discovery was a bonanza for the country."],
["bottleneck","tor joy, to'siq","obstacle, hindrance, blockage","Traffic bottlenecks cause delays."],
["bounty","saxovatlilik, mukofot","reward, generosity, premium","The bounty of nature provides for all."],
["brevity","qisqalik","shortness, conciseness, briefness","Brevity is the soul of wit."],
["brisk","tez, faol","quick, lively, energetic","Business was brisk during the holiday."],
["brittle","mo'rt, sinuvchan","fragile, breakable, delicate","The old paper was brittle."],
["broach","gapni boshlamoq","introduce, raise, mention","She broached the subject carefully."],
["budge","jilmoq, o'z fikrini o'zgartirmoq","move, shift, yield","He refused to budge on the issue."],
["buffer","bufer, himoyalovchi","cushion, shield, barrier","The forest acts as a buffer against wind."],
["bureaucratic","byurokratik","administrative, official, formal","Bureaucratic procedures slow down progress."],
["burgeon","tez o'smoq, gullamoq","flourish, grow, thrive","The tech industry is burgeoning."],
["buttress","mustahkamlamoq, qo'llab-quvvatlamoq","support, reinforce, bolster","Facts buttress the argument."],

// ===== DAILY LIFE & IELTS COMMON =====
["accustom","o'rganmoq, odatlanmoq","adapt, familiarize, habituate","He accustomed himself to the new schedule."],
["acknowledge","tan olmoq, tasdiqlash","admit, recognize, accept","She acknowledged her mistake."],
["advocate","himoya qilmoq, tarafdor bo'lmoq","support, promote, champion","He advocates for animal rights."],
["affirmative","ijobiy, tasdiqlovchi","positive, agreeing, confirming","She gave an affirmative response."],
["affordable","arzon, hamyonbop","cheap, inexpensive, reasonable","Affordable housing is hard to find."],
["alleviate","yengillashtirmoq","relieve, ease, reduce","Medication can alleviate the symptoms."],
["ambiguous","noaniq, ikki ma'noli","unclear, vague, equivocal","The instructions were ambiguous."],
["amenable","ko'nuvchan, tayyor","willing, agreeable, cooperative","She is amenable to suggestions."],
["ample","yetarli, keng","plenty, sufficient, abundant","There is ample parking available."],
["anomaly","g'ayritabiiy holat, nomuvofiqlik","irregularity, abnormality, exception","The test revealed an anomaly."],
["apathy","befarqlik","indifference, unconcern, disinterest","Public apathy towards politics is worrying."],
["appreciable","sezilarli","noticeable, significant, considerable","There was an appreciable difference."],
["apprise","xabar bermoq, ma'lum qilmoq","inform, notify, tell","Please apprise me of any changes."],
["arbitrary","asossiz, o'zboshimcha","random, capricious, unjustified","Arbitrary rules frustrate employees."],
["ardent","ishtiyoqli, otashin","passionate, fervent, enthusiastic","He is an ardent fan of jazz music."],
["articulate","ravon, aniq","eloquent, fluent, clear","She is an articulate speaker."],
["aspire","intilmoq","aim, strive, hope","Many students aspire to attend top universities."],
["astute","zukko, aqlli","shrewd, sharp, clever","An astute businessman sees opportunity everywhere."],
["attest","guvohlik bermoq, tasdiqlash","confirm, verify, certify","The results attest to the program's success."],
["audacious","jasur, dovyurak","bold, daring, fearless","The audacious rescue mission succeeded."],
["augment","oshirmoq","increase, boost, enhance","She augmented her skills with online courses."],
["auspicious","qulay, muborak","favorable, fortunate, promising","It was an auspicious day for the launch."],
["austere","oddiy, qat'iy","plain, strict, severe","The room was austere with minimal furniture."],
["authentic","haqiqiy, chin","genuine, real, original","The artifact was confirmed as authentic."],
["avarice","tamah, ochko'zlik","greed, cupidity, acquisitiveness","Avarice led to his downfall."],
["averse","qarshi, yoqtirmaydigan","opposed, reluctant, unwilling","She is averse to taking risks."],
["avid","ishtiyoqli","eager, keen, enthusiastic","He is an avid collector of rare books."],
["belie","yashirmoq, noto'g'ri ko'rsatmoq","contradict, misrepresent, disguise","Her calm demeanor belied her nervousness."],
["belittle","kamsitmoq, kichraytirmoq","undermine, disparage, minimize","Do not belittle others' achievements."],
["benchmark","standart, mezon","standard, reference point, criterion","The exam is a benchmark for progress."],
["benefactor","homiy, xayriya qiluvchi","patron, donor, sponsor","The anonymous benefactor donated millions."],
["benevolent","xayrixoh, saxiy","kind, generous, charitable","A benevolent leader cares for all citizens."],
["berate","koyimoq, so'kmoq","scold, criticize, reprimand","The manager berated the team for poor results."],
["bestow","bermoq, in'om qilmoq","give, award, grant","The university bestowed an honorary degree."],
["bewildering","gangituvchi, hayratlanarli","confusing, puzzling, baffling","The number of choices was bewildering."],
["bigotry","mutaassiblik, tor fikrlilik","intolerance, prejudice, discrimination","Bigotry has no place in modern society."],
["boon","ne'mat, foyda","blessing, benefit, advantage","The internet has been a boon for education."],
["boycott","boykot, rad etish","ban, reject, shun","Consumers boycotted the company."],
["breach","buzish, yorilish","violation, break, infringement","The breach of contract led to a lawsuit."],
["bureaucracy","byurokratiya, idorabozlik","red tape, administration, officialdom","Excessive bureaucracy delays decision-making."],
["caliber","sifat, daraja","quality, standard, level","We need candidates of the highest caliber."],
["candid","ochiq, samimiy","honest, frank, direct","She gave a candid assessment."],
["capacity","quvvat, sig'im","ability, volume, capability","The stadium has a capacity of 80,000."],
["captivate","maftun qilmoq","charm, fascinate, enchant","The speaker captivated the audience."],
["catalyst","turtki, sabab","trigger, stimulus, impetus","The event was a catalyst for change."],
["catastrophe","falokat, halokat","disaster, calamity, tragedy","The oil spill was an environmental catastrophe."],
["cautious","ehtiyotkor, ziyrak","careful, wary, prudent","She was cautious about making promises."],
["cease","to'xtatmoq, tugatmoq","stop, halt, end","Hostilities ceased at midnight."],
["celestial","osmoniy, samoviy","heavenly, cosmic, stellar","The telescope revealed celestial objects."],
["certify","tasdiqlash, sertifikat bermoq","confirm, verify, accredit","The document was certified by a notary."],
["chronicle","yilnoma, qayd etmoq","record, document, log","The book chronicles the history of the region."],
["circumscribe","chegaralamoq, cheklamoq","limit, restrict, confine","His authority was circumscribed by law."],
["clandestine","yashirin, maxfiy","secret, covert, underground","The clandestine meeting took place at night."],
["clergy","ruhoniylar","priests, ministers, religious leaders","The clergy played a role in the community."],
["clientele","mijozlar, xaridorlar","customers, patrons, clients","The restaurant has a loyal clientele."],
["coalesce","birlashmoq, qo'shilmoq","merge, combine, unite","The two groups coalesced into one organization."],
["coerce","majbur qilmoq","force, compel, pressure","Workers were coerced into signing the agreement."],
["coherent","izchil, mantiqiy","logical, consistent, clear","Her argument was coherent and convincing."],
["coincide","mos kelmoq, to'g'ri kelmoq","correspond, match, agree","The events coincided with the holiday."],
["collateral","garovnoma, qo'shimcha","security, guarantee, secondary","He offered his house as collateral."],
["commemorate","xotirlash, yodga olmoq","remember, honor, celebrate","The monument commemorates the fallen soldiers."],
["commensurate","teng, munosib","proportional, equivalent, matching","The salary is commensurate with experience."],
["compelling","ishonchli, kuchli","convincing, persuasive, powerful","She made a compelling argument."],
["compensate","qoplash, tovon to'lamoq","reimburse, offset, repay","The company compensated for the loss."],
["competence","malaka, qobiliyat","skill, ability, proficiency","Her competence in the job is undeniable."],
["compliance","rioya, muvofiqlik","obedience, adherence, conformity","Compliance with safety rules is essential."],
["complicit","sherik, aybdor","involved, guilty, colluding","He was complicit in the fraud."],
["component","tarkibiy qism, element","part, element, constituent","Each component was tested individually."],
["compound","birikma, kuchaytirmoq","mixture, combination, worsen","The problems were compounded by delays."],
["compulsory","majburiy, shart","mandatory, required, obligatory","The test is compulsory for all students."],
["concede","tan olmoq, yon bermoq","admit, acknowledge, yield","He conceded that he was wrong."],
["conceivable","tasavvur qilish mumkin","possible, imaginable, thinkable","Every conceivable option was considered."],
["concession","imtiyoz, yon berish","compromise, allowance, privilege","The workers won several concessions."],
["concise","qisqa, lo'nda","brief, short, succinct","Write a concise summary."],
["conclusive","yakuniy, qat'iy","decisive, definitive, final","The evidence was conclusive."],
["condemn","qoralash, hukm qilmoq","criticize, denounce, sentence","The attack was condemned internationally."],
["condone","ko'z yummoq","tolerate, excuse, accept","The school does not condone cheating."],
["conducive","qulay, yordam beruvchi","favorable, helpful, beneficial","A quiet environment is conducive to studying."],
["confiscate","musodara qilmoq, tortib olmoq","seize, impound, take","Phones were confiscated during the exam."],
["congestion","tiqilinch, siqilish","overcrowding, blockage, jam","Traffic congestion is a daily problem."],
["conjecture","taxmin, faraz","guess, speculation, theory","His theory is pure conjecture."],
["conscience","vijdon, imon","morality, principles, ethics","Let your conscience guide you."],
["consensus","kelishuv, umumiy fikr","agreement, accord, unanimity","We reached a consensus on the plan."],
["conservation","saqlash, muhofaza","preservation, protection, saving","Wildlife conservation is urgent."],
["conspicuous","ko'zga ko'ringan, yaqqol","noticeable, obvious, visible","Her absence was conspicuous."],
["constraint","cheklov, to'siq","restriction, limitation, barrier","Time constraints limited the research."],
["contemplate","fikr yuritmoq","think, consider, ponder","She contemplated quitting her job."],
["contemporary","zamonaviy, hozirgi zamon","modern, current, present","Contemporary music is diverse."],
["contempt","nafrat, tahqir","disdain, scorn, disrespect","He showed contempt for the rules."],
["contend","kurashmoq, ta'kidlamoq","compete, argue, assert","Several teams contend for the title."],
["contentious","bahsli, tortishuvli","controversial, debatable, disputed","Immigration is a contentious topic."],
["contradict","zid bo'lmoq, inkor qilmoq","oppose, deny, challenge","The evidence contradicts his statement."],
["controversial","munozarali, bahsli","debatable, contentious, divisive","The decision was highly controversial."],
["convene","yig'ilmoq, chaqirmoq","assemble, meet, gather","The committee convened for an emergency meeting."],
["conventional","an'anaviy, oddiy","traditional, standard, typical","Conventional methods are still widely used."],
["converge","birlashmoq, to'planmoq","meet, join, merge","All roads converge at the city center."],
["conviction","ishonch, hukm","belief, certainty, sentence","She spoke with deep conviction."],
["cooperative","hamkorlikdagi, sheriklik","collaborative, joint, mutual","The project was a cooperative effort."],
["coordinate","muvofiqlashtirmoq","organize, synchronize, arrange","She coordinated the entire campaign."],
["copyright","mualliflik huquqi","intellectual property, patent","Copyright protects creative works."],
["corporate","korporativ, kompaniya","business, organizational, company","Corporate governance is evolving."],
["correlate","bog'liq bo'lmoq","connect, relate, correspond","Exercise correlates with better health."],
["corruption","korrupsiya, buzilish","dishonesty, fraud, bribery","Corruption weakens democratic institutions."],
["counterfeit","soxta, qalbaki","fake, forged, fraudulent","Counterfeit goods are illegal."],
["covert","yashirin, maxfiy","secret, hidden, undercover","A covert operation was carried out."],
["credential","guvohnoma, hujjat","qualification, certificate, proof","She presented her credentials."],
["criterion","mezon, standart","standard, measure, benchmark","Safety is the main criterion."],
["crucial","hal qiluvchi","critical, vital, essential","Timing is crucial for success."],
["culminate","cho'qqiga chiqmoq, yakunlanmoq","climax, peak, end","Years of work culminated in success."],
["cumulative","yig'ma, jamlovchi","accumulated, collective, total","The cumulative effect was significant."],
["curriculum","o'quv dasturi, reja","syllabus, program, course","The curriculum was revised last year."],
["curtail","qisqartirmoq, cheklamoq","reduce, cut, limit","Spending was curtailed due to the deficit."],
["customary","odatiy, an'anaviy","usual, traditional, habitual","It is customary to tip waiters."],
["cynicism","kinoyachilik, ishonchsizlik","skepticism, pessimism, distrust","Cynicism about politics is widespread."],
["debacle","halokat, mag'lubiyat","disaster, fiasco, failure","The project ended in a debacle."],
["debris","qoldiq, vayronalar","wreckage, rubble, fragments","Workers cleared the debris after the storm."],
["debut","birinchi chiqish","first appearance, premiere, launch","The singer made her debut at age 16."],
["decadence","tanazzul, buzilish","decline, corruption, deterioration","The decadence of the empire led to its fall."],
["deception","aldov, firibgarlik","fraud, dishonesty, trickery","The deception was eventually uncovered."],
["decisive","hal qiluvchi, qat'iy","determined, conclusive, resolute","The battle was decisive."],
["dedicate","bag'ishlamoq, ajratmoq","devote, commit, allocate","She dedicated her life to research."],
["defame","obro'sizlantirmoq, tuhmat qilmoq","slander, libel, smear","The article defamed the politician."],
["default","standart, bajarmaslik","failure, standard, preset","He defaulted on his loan payments."],
["defer","kechiktirmoq, hurmаt ko'rsatmoq","postpone, delay, respect","The decision was deferred to next month."],
["defiant","itoatsiz, bo'ysunmaydigan","rebellious, resistant, bold","The defiant protesters refused to leave."],
["degenerate","yomonlashmoq, buzilmoq","deteriorate, decline, worsen","The situation degenerated rapidly."],
["delegate","vakil, topshirmoq","representative, assign, entrust","He delegated responsibilities to his team."],
["deliberate","qasddan, o'ylab qilingan","intentional, planned, careful","It was a deliberate choice."],
["demeanor","xulq, tutish","behavior, manner, attitude","Her calm demeanor impressed everyone."],
["democracy","demokratiya, xalq hokimiyati","self-governance, republic, freedom","Democracy ensures equal rights for all."],
["demographic","demografik","population-related, statistical","Demographic shifts affect the workforce."],
["demolish","buzmoq, vayron qilmoq","destroy, raze, dismantle","The old factory was demolished."],
["depict","tasvirlamoq, ko'rsatmoq","portray, illustrate, represent","The mural depicts scenes from history."],
["deplete","tamom qilmoq, tugallash","exhaust, drain, use up","Natural resources are being depleted."],
["deport","deportatsiya qilmoq","expel, banish, exile","Illegal immigrants were deported."],
["deprecate","qoralash, yoqtirmaslik","disapprove, criticize, condemn","She deprecated the use of violence."],
["deprive","mahrum qilmoq","deny, strip, rob","Children should not be deprived of education."],
["deregulate","tartibsizlantirmoq, erkinlashtirmoq","liberalize, free, loosen","The government deregulated the industry."],
["derive","olmoq, kelib chiqmoq","obtain, stem, originate","The word derives from Latin."],
["designate","belgilamoq, tayinlamoq","name, appoint, assign","The area was designated a national park."],
["desolate","xarobа, huvillab qolgan","barren, deserted, bleak","The landscape was desolate."],
["despair","umidsizlik, noumidlik","hopelessness, dejection, misery","She was filled with despair."],
["destabilize","beqarorlashtirmoq","upset, undermine, weaken","The conflict destabilized the region."],
["deter","qaytarmoq, to'xtatmoq","discourage, prevent, dissuade","Security cameras deter criminals."],
["deteriorate","yomonlashmoq","decline, worsen, degrade","Air quality has deteriorated."],
["detrimental","zararli","harmful, damaging, injurious","Pollution is detrimental to health."],
["deviate","chetga chiqmoq","diverge, stray, depart","Do not deviate from the plan."],
["devise","o'ylab topmoq, ixtiro qilmoq","invent, create, design","She devised an innovative solution."],
["devout","taqvodor, sodiq","pious, religious, faithful","He is a devout believer."],
["dilemma","ikkilanish, tanlash qiyinligi","predicament, quandary, problem","She faced a difficult dilemma."],
["diminish","kamaymoq, ozaymoq","decrease, reduce, lessen","His influence has diminished over time."],
["discern","ajratmoq, ko'rmoq","perceive, detect, recognize","She could discern the truth from lies."],
["discourse","suhbat, nutq","discussion, dialogue, conversation","Academic discourse requires formal language."],
["discretion","ehtiyotkorlik, ixtiyoriylik","caution, judgment, prudence","Use your own discretion."],
["disdain","nafrat, mensimaslik","contempt, scorn, disrespect","She viewed the offer with disdain."],
["disenfranchise","huquqdan mahrum qilmoq","deprive, exclude, marginalize","Millions of voters were disenfranchised."],
["disillusion","ko'zini ochmoq, umidini yo'qotmoq","disappoint, disenchant, let down","Many people were disillusioned with politics."],
["disparage","kamsitmoq, past qilmoq","belittle, criticize, undervalue","She disparaged her competitor's work."],
["disparity","tengsizlik, nomuvofiqlik","inequality, difference, gap","The disparity between rich and poor is growing."],
["disposable","bir martali, tashlash mumkin","throwaway, single-use, expendable","Reduce the use of disposable plastics."],
["disrupt","buzmoq, halaqit bermoq","disturb, interrupt, upset","The protest disrupted traffic."],
["dissent","norozilik, qarshilik","disagreement, opposition, objection","Political dissent was suppressed."],
["distinguish","ajratmoq, farqlamoq","differentiate, recognize, identify","She can distinguish between the two dialects."],
["diverse","xilma-xil, turli","varied, different, assorted","The country has a diverse culture."],
["doctrine","doktrina, ta'limot","belief, teaching, principle","The doctrine shaped military strategy."],
["domestic","ichki, maishiy","home, national, household","Domestic violence is a serious problem."],
["dominant","ustun, hukmron","prevailing, leading, principal","English is the dominant language online."],
["dormant","faoliyatsiz, tinch","inactive, sleeping, latent","The volcano has been dormant for years."],
["dubious","shubhali, ishonchsiz","doubtful, questionable, uncertain","His claims are dubious at best."],
["durable","bardoshli, mustahkam","lasting, sturdy, resilient","The material is extremely durable."],
["dynamic","dinamik, faol","energetic, active, vibrant","The city has a dynamic economy."],
["eccentric","g'alati, o'ziga xos","quirky, odd, unconventional","He has an eccentric personality."],
["eclipse","tutilish, soya solmoq","overshadow, block, surpass","Her achievements eclipsed those of her peers."],
["elaborate","batafsil, murakkab","detailed, complex, ornate","She gave an elaborate explanation."],
["elapse","o'tmoq (vaqt)","pass, go by, expire","Several years elapsed before they met again."],
["elevate","ko'tarmoq, oshirmoq","raise, lift, promote","The news elevated her spirits."],
["eligible","huquqli, layoq","qualified, entitled, suitable","Only members are eligible to vote."],
["eliminate","yo'q qilmoq, bartaraf etmoq","remove, eradicate, get rid of","The team eliminated all errors."],
["eloquent","notiq, fasih","articulate, fluent, persuasive","She delivered an eloquent speech."],
["elucidate","tushuntirmoq, aniqlash","explain, clarify, illuminate","The professor elucidated the concept."],
["elusive","qo'lga tushmaydigan, noaniq","evasive, hard to find, slippery","The answer remained elusive."],
["emanate","chiqmoq, tarqalmoq","emerge, originate, radiate","Light emanates from the sun."],
["embargo","embargo, taqiq","ban, prohibition, blockade","The oil embargo raised prices worldwide."],
["embark","kirishmoq, yo'lga chiqmoq","begin, start, set out","She embarked on a new adventure."],
["embody","mujassam etmoq","represent, personify, encompass","The law embodies the principle of equality."],
["embrace","quchoqlamoq, qabul qilmoq","accept, adopt, welcome","The company embraced innovation."],
["emerge","paydo bo'lmoq, chiqqan","appear, arise, surface","A new leader emerged from the crisis."],
["eminent","mashhur, taniqli","distinguished, prominent, renowned","She is an eminent professor."],
["emit","chiqarmoq, tarqatmoq","release, discharge, produce","The factory emits harmful gases."],
["empathy","hamdardlik, tushunish","compassion, understanding, sensitivity","Empathy is essential for good leadership."],
["empirical","tajribaga asoslangan","experimental, practical, observed","The theory lacks empirical support."],
["empower","kuch bermoq, huquq bermoq","enable, authorize, strengthen","Education empowers individuals."],
["enact","qabul qilmoq, ijro etmoq","pass, legislate, implement","New safety laws were enacted."],
["encompass","qamrab olmoq","include, embrace, cover","The plan encompasses all departments."],
["endeavor","harakat qilmoq, intilmoq","try, attempt, strive","She endeavored to improve the system."],
["endorse","ma'qullamoq, tasdiqlash","support, approve, recommend","The board endorsed the proposal."],
["engender","sabab bo'lmoq, keltirib chiqarmoq","cause, produce, create","Poverty engenders crime."],
["enhance","yaxshilamoq, kuchaytirmoq","improve, boost, augment","Technology enhances productivity."],
["enormous","ulkan, katta","huge, vast, immense","The project requires enormous resources."],
["enrich","boyitmoq, to'ldirmoq","improve, enhance, supplement","Travel enriches one's perspective."],
["enterprise","korxona, tashabbuskorlik","business, venture, initiative","She started her own enterprise."],
["entitle","huquq bermoq, nom bermoq","authorize, qualify, name","The ticket entitles you to free parking."],
["entity","sub'ekt, tashkilot","body, organization, being","The company is a legal entity."],
["envision","ko'z oldiga keltirmoq","imagine, foresee, picture","She envisioned a brighter future."],
["ephemeral","vaqtinchalik, o'tkinchi","temporary, fleeting, brief","Fame can be ephemeral."],
["equitable","adolatli, teng","fair, just, impartial","An equitable distribution of resources is needed."],
["eradicate","butunlay yo'q qilmoq","eliminate, destroy, wipe out","The program aims to eradicate malaria."],
["erosion","yemirilish, buzilish","wear, deterioration, corrosion","Coastal erosion is a serious issue."],
["erratic","tartibsiz, o'zgaruvchan","unpredictable, inconsistent, irregular","The weather has been erratic lately."],
["escalate","kuchaymoq, og'irlashmoq","intensify, increase, worsen","The conflict escalated quickly."],
["espouse","qo'llab-quvvatlamoq, himoya qilmoq","support, advocate, champion","She espoused the cause of equality."],
["essential","zarur, muhim","vital, crucial, necessary","Clean water is essential for life."],
["estrange","begona bo'lmoq, uzoqlashmoq","alienate, separate, distance","He became estranged from his family."],
["ethical","axloqiy, odobli","moral, principled, virtuous","Ethical behavior is expected in business."],
["ethnic","etnik, milliy","racial, cultural, national","Ethnic diversity enriches the community."],
["evacuate","evakuatsiya qilmoq","remove, clear, empty","Residents were evacuated before the hurricane."],
["evaluate","baholamoq","assess, judge, appraise","The team evaluated the results."],
["evaporate","bug'lanmoq, yo'qolmoq","vaporize, disappear, vanish","The water evaporated in the heat."],
["evident","aniq, ko'rinib turgan","clear, obvious, apparent","It was evident that changes were needed."],
["evolve","rivojlanmoq, takomillashmoq","develop, progress, advance","Technology continues to evolve rapidly."],
["exacerbate","og'irlashtirmoq","worsen, aggravate, intensify","Pollution exacerbates respiratory problems."],
["exaggerate","bo'rttirib ko'rsatmoq","overstate, inflate, magnify","He tends to exaggerate his problems."],
];

async function seed() {
    const SQL = await initSqlJs();
    let db;

    if (fs.existsSync(DB_PATH)) {
        const buffer = fs.readFileSync(DB_PATH);
        db = new SQL.Database(buffer);
    } else {
        db = new SQL.Database();
        db.run(`CREATE TABLE IF NOT EXISTS words (id INTEGER PRIMARY KEY AUTOINCREMENT, english TEXT NOT NULL, uzbek TEXT NOT NULL, synonyms TEXT DEFAULT '', example TEXT DEFAULT '', score INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
    }

    const existing = new Set();
    const rows = db.exec('SELECT english FROM words');
    if (rows.length > 0) {
        rows[0].values.forEach(r => existing.add(r[0].toLowerCase()));
    }

    let added = 0;
    const stmt = db.prepare('INSERT INTO words (english, uzbek, synonyms, example) VALUES (?, ?, ?, ?)');

    for (const [eng, uzb, syn, ex] of words) {
        if (!existing.has(eng.toLowerCase())) {
            stmt.run([eng, uzb, syn || '', ex || '']);
            existing.add(eng.toLowerCase());
            added++;
        }
    }
    stmt.free();

    const data = db.export();
    fs.writeFileSync(DB_PATH, Buffer.from(data));

    const total = db.exec('SELECT COUNT(*) FROM words');
    console.log(`${added} ta yangi so'z qo'shildi. Jami: ${total[0].values[0][0]} ta so'z.`);
    db.close();
}

seed().catch(console.error);
