const path = require('path');
const initSqlJs = require('sql.js');
const fs = require('fs');
const DB_PATH = path.join(__dirname, 'words.db');

const words = [
["disdain","nafrat, mensimaslik","contempt, scorn, disrespect","She viewed the offer with disdain."],
["disenchant","ko'zini ochmoq, umidini yo'qotmoq","disillusion, disappoint","Many voters are disenchanted with politics."],
["disfigure","buzmoq, ko'rinishini o'zgartirmoq","deform, mar, damage","The fire disfigured the building."],
["disgruntled","norozi, xafa","unhappy, dissatisfied, annoyed","Disgruntled employees filed a complaint."],
["disguise","niqob, yashirmoq","mask, camouflage, conceal","He attended in disguise."],
["dismantle","demontaj qilmoq, buzmoq","take apart, disassemble","They dismantled the old bridge."],
["dismay","dahshat, hayrat","alarm, distress, concern","The news filled them with dismay."],
["dispatch","jo'natmoq, yubormoq","send, ship, forward","The goods were dispatched immediately."],
["dispel","yo'q qilmoq, tarqatmoq","dismiss, eliminate, banish","She dispelled the rumors quickly."],
["displace","joy almashmoq, siljitmoq","move, replace, relocate","The flood displaced thousands of families."],
["disposition","xarakter, moyillik","temperament, nature, tendency","She has a cheerful disposition."],
["disproportionate","nomutanosib, haddan tashqari","unequal, excessive, uneven","The punishment was disproportionate to the crime."],
["dispute","bahs, tortishuv","argument, disagreement, conflict","The land dispute lasted years."],
["disrupt","buzmoq, halaqit bermoq","disturb, interrupt, upset","The protest disrupted traffic for hours."],
["disseminate","tarqatmoq, yoymoq","spread, distribute, broadcast","Information was disseminated through social media."],
["dissent","norozilik, qarshi fikr","disagreement, opposition, protest","Political dissent was not tolerated."],
["dissipate","tarqalmoq, isrof qilmoq","disperse, waste, scatter","The fog dissipated by noon."],
["dissolve","eritmoq, tugatmoq","melt, disband, terminate","Parliament was dissolved before elections."],
["dissuade","ko'ndirmoq, qaytarmoq","discourage, deter, talk out of","She dissuaded him from quitting."],
["distinct","alohida, aniq","separate, different, clear","There are two distinct categories."],
["distinguish","farqlamoq, ajratmoq","differentiate, tell apart","She can distinguish subtle differences."],
["distort","buzmoq, noto'g'ri ko'rsatmoq","twist, warp, misrepresent","The media distorted the facts."],
["distress","azob, qayg'u","anguish, suffering, pain","The family was in great distress."],
["distribute","tarqatmoq, taqsimlamoq","hand out, share, deliver","Food was distributed to the refugees."],
["diverge","tarqalmoq, farq qilmoq","separate, differ, deviate","Our opinions diverge on this issue."],
["diverse","xilma-xil, har xil","varied, different, assorted","A diverse workforce brings new ideas."],
["divest","mahrum qilmoq, sotib yubormoq","strip, dispose, sell off","The company divested its overseas assets."],
["divine","ilohiy, mukammal","holy, sacred, heavenly","The temple is a place of divine worship."],
["docile","itoatkor, yumshoq","obedient, submissive, gentle","The dog was docile and friendly."],
["doctrine","doktrina, ta'limot","teaching, principle, belief","Military doctrine guides strategy."],
["dogmatic","dogmatik, o'zgarmas","rigid, inflexible, opinionated","He was dogmatic in his beliefs."],
["doldrums","tushkunlik, sustlik","depression, stagnation, slump","The economy is in the doldrums."],
["domain","soha, hudud","field, area, territory","She is an expert in her domain."],
["domicile","turar joy, yashash joyi","home, residence, dwelling","His domicile is in the capital."],
["dormant","uxlab yotgan, faoliyatsiz","inactive, sleeping, latent","The volcano has been dormant for centuries."],
["dosage","doza, miqdor","amount, quantity, dose","Do not exceed the recommended dosage."],
["dossier","ma'lumotlar papkasi","file, record, portfolio","The police compiled a dossier on the suspect."],
["draconian","shafqatsiz, qattiq","harsh, severe, strict","Draconian laws were imposed."],
["drastic","keskin, tubdan","extreme, severe, radical","Drastic measures are needed."],
["drawback","kamchilik, salbiy tomon","disadvantage, flaw, shortcoming","The main drawback is the high cost."],
["drought","qurg'oqchilik","dry spell, arid period","The drought destroyed crops."],
["dubious","shubhali","doubtful, questionable","The claim is dubious."],
["duel","duel, bellashuv","contest, fight, battle","The candidates engaged in a verbal duel."],
["durable","chidamli, mustahkam","lasting, sturdy, resilient","The material is highly durable."],
["duress","bosim, majburlash","coercion, force, pressure","He signed under duress."],
["dutiful","itoatkor, burchini biluvchi","obedient, responsible, loyal","She was a dutiful daughter."],
["dwindle","kamaymoq, so'nmoq","decrease, shrink, diminish","Supplies dwindled rapidly."],
["dysfunction","buzilish, ishlamay qolish","malfunction, disorder, failure","The dysfunction of the system caused chaos."],
["dystopia","distopiya, yomon jamiyat","nightmare society, anti-utopia","The novel describes a terrifying dystopia."],
["eagerness","ishtiyoq, intilish","enthusiasm, keenness, desire","Her eagerness impressed the interviewer."],
["eclipse","tutilish, ustidan o'tish","overshadow, surpass, block","Her talent eclipsed everyone else."],
["ecology","ekologiya, muhit ilmi","environmental science, nature study","Marine ecology studies ocean life."],
["efficacy","samaradorlik, ta'sir kuchi","effectiveness, potency, success","The efficacy of the vaccine was proven."],
["efficient","samarali, unumli","productive, effective, capable","Energy-efficient buildings save costs."],
["egalitarian","tenglik tarafdori","equal, democratic, fair","The policy promotes egalitarian values."],
["elaborate","batafsil, murakkab","detailed, complex, ornate","He provided an elaborate explanation."],
["elastic","elastik, egiluvchan","flexible, stretchy, resilient","The material is highly elastic."],
["elate","xursand qilmoq, xushhal qilmoq","delight, thrill, excite","The victory elated the team."],
["elevate","ko'tarmoq, oshirmoq","raise, lift, promote","Reading elevates the mind."],
["elicit","olmoq, undamoq","draw out, provoke, extract","The question elicited a strong response."],
["elite","eng yaxshilari, elita","top, cream, best","Only the elite athletes compete."],
["elongate","cho'zmoq, uzaytirmoq","extend, stretch, lengthen","Heat elongates metal."],
["elude","qochmoq, qo'lga tushmaslik","escape, avoid, evade","The answer eluded her."],
["emaciate","ozib ketmoq, holsizlanmoq","waste away, weaken, thin","The prisoners were emaciated."],
["emancipate","ozod qilmoq, erkin qilmoq","free, liberate, release","The law emancipated the slaves."],
["embed","joylash, singdirmoq","implant, insert, fix","Technology is embedded in daily life."],
["embellish","bezamoq, bo'rttirmoq","decorate, adorn, exaggerate","She embellished the story."],
["embezzle","o'zlashtirib olmoq","steal, misappropriate, defraud","The accountant embezzled company funds."],
["emblem","belgi, ramz","symbol, badge, insignia","The eagle is the national emblem."],
["embrace","quchoqlamoq, qabul qilmoq","hug, accept, adopt","She embraced the new opportunity."],
["embroil","aralashmoq, chigallashmoq","involve, entangle, implicate","He was embroiled in a scandal."],
["emerge","paydo bo'lmoq, chiqmoq","appear, arise, surface","New facts emerged during the trial."],
["emigrate","ko'chib ketmoq","leave, migrate, relocate","Many people emigrated during the war."],
["eminent","taniqli, mashhur","distinguished, prominent, renowned","She is an eminent scholar."],
["emit","chiqarmoq, tarqatmoq","release, discharge, produce","The factory emits toxic gases."],
["empathy","hamdardlik, tushunish","compassion, understanding, sympathy","Empathy is key to good communication."],
["empirical","tajribaga asoslangan","experimental, observed, practical","The study provides empirical evidence."],
["empower","kuch bermoq, huquq bermoq","enable, authorize, strengthen","Education empowers communities."],
["emulate","taqlid qilmoq, intilmoq","imitate, copy, follow","Young people emulate their role models."],
["enact","qonun qabul qilmoq","pass, legislate, implement","Parliament enacted the reform."],
["encompass","qamrab olmoq, o'z ichiga olmoq","include, contain, cover","The study encompasses many topics."],
["encounter","duch kelmoq, uchrashuv","meet, face, experience","We encountered unexpected problems."],
["encrypt","shifrlash, kodlash","encode, protect, secure","Messages should be encrypted for safety."],
["endanger","xavf ostiga qo'ymoq","threaten, jeopardize, risk","Pollution endangers marine life."],
["endemic","mahalliy, o'sha joyga xos","native, local, indigenous","Malaria is endemic in tropical regions."],
["endorse","ma'qullamoq, qo'llab-quvvatlamoq","support, approve, back","The committee endorsed the plan."],
["endow","in'om qilmoq, bermoq","provide, bestow, grant","Nature endowed her with talent."],
["endure","chidamoq, davom etmoq","withstand, bear, tolerate","She endured great hardship."],
["engender","keltirib chiqarmoq","cause, produce, create","Trust engenders cooperation."],
["engross","chalg'itmoq, diqqatni tortmoq","absorb, captivate, immerse","The book engrossed her completely."],
["engulf","yutmoq, qamrab olmoq","swallow, overwhelm, surround","Flames engulfed the building."],
["enhance","yaxshilamoq, kuchaytirmoq","improve, boost, augment","Good lighting enhances the room."],
["enigma","jumboq, sir","mystery, puzzle, riddle","The case remains an enigma."],
["enlighten","ma'rifatlamoq, tushuntirmoq","educate, inform, illuminate","The lecture enlightened the audience."],
["enmity","dushmanlik, adovat","hostility, hatred, antagonism","There was deep enmity between the families."],
["enormous","ulkan, bahaybat","huge, vast, immense","The project cost an enormous amount."],
["enrich","boyitmoq","improve, enhance, supplement","Travel enriches your perspective."],
["enshroud","yashirmoq, o'ramoq","conceal, cover, veil","Fog enshrouded the city."],
["ensure","ta'minlamoq, kafolat bermoq","guarantee, secure, assure","Please ensure all doors are locked."],
["enterprise","korxona, tashabbuskorlik","business, company, venture","Free enterprise drives innovation."],
["enthusiasm","ishtiyoq, zavq","excitement, passion, eagerness","She showed great enthusiasm for the project."],
["entice","jalb qilmoq, vasvasaga solmoq","lure, attract, tempt","The offer enticed many applicants."],
["entity","sub'ekt, mavjudot","being, body, organization","Each country is a sovereign entity."],
["entrench","mustahkamlamoq, chuqur o'rnashmoq","establish, embed, fix","Corruption is deeply entrenched."],
["enumerate","sanab o'tmoq","list, count, itemize","She enumerated the main points."],
["envisage","ko'z oldiga keltirmoq","imagine, foresee, visualize","We envisage a better future."],
["envoy","elchi, vakil","ambassador, representative, diplomat","The envoy delivered the message."],
["ephemeral","o'tkinchi, vaqtinchalik","temporary, fleeting, brief","Social media trends are ephemeral."],
["epitome","timsol, namuna","embodiment, model, example","She is the epitome of grace."],
["equitable","adolatli, teng","fair, just, impartial","An equitable solution was found."],
["eradicate","tugatmoq, yo'q qilmoq","eliminate, destroy, exterminate","We must eradicate poverty."],
["erode","yemirilmoq, buzilmoq","wear away, deteriorate","Trust has been eroded by scandal."],
["erratic","tartibsiz, beqaror","unpredictable, irregular, inconsistent","His behavior was increasingly erratic."],
["erudite","bilimdon, o'qimishli","scholarly, learned, knowledgeable","She is an erudite professor."],
["escalate","kuchaymoq, oshmoq","intensify, increase, grow","Tensions escalated between the two nations."],
["espionage","josuslik","spying, intelligence, surveillance","Industrial espionage is a crime."],
["essay","insho, maqola","composition, article, paper","She wrote an essay on climate change."],
["essence","mohiyat, asl ma'no","core, nature, substance","The essence of the argument is simple."],
["establish","tashkil etmoq, o'rnatmoq","create, found, set up","The company was established in 1950."],
["esteem","hurmat, e'tibor","respect, regard, admiration","She is held in high esteem."],
["eternal","abadiy, mangu","everlasting, permanent, endless","The search for eternal youth continues."],
["ethical","axloqiy, ma'naviy","moral, principled, virtuous","Ethical standards guide research."],
["ethnic","etnik, milliy","racial, cultural, national","Ethnic diversity enriches society."],
["etymology","etimologiya, so'z tarixi","word origin, word history, derivation","The etymology of the word is interesting."],
["euphemism","evfemizm, yumshoq ifoda","polite term, indirect expression","Senior citizen is a euphemism for old person."],
["euphoria","zavq, hayajon","elation, joy, ecstasy","There was euphoria after the victory."],
["evacuate","evakuatsiya qilmoq, bo'shatmoq","remove, clear, empty","Residents were evacuated before the storm."],
["evaluate","baholamoq, aniqlash","assess, judge, appraise","We need to evaluate the results."],
["evaporate","bug'lanmoq, yo'qolmoq","vaporize, disappear, vanish","Puddles evaporate quickly in the sun."],
["evasion","qochish, chetga surilish","avoidance, dodging, escape","Tax evasion is illegal."],
["evident","aniq, ravshan","clear, obvious, apparent","It was evident that he was lying."],
["evil","yovuzlik, yomonlik","wickedness, malice, sin","Good must triumph over evil."],
["evolve","rivojlanmoq, o'zgarmoq","develop, change, progress","Species evolve over millions of years."],
["exacerbate","og'irlashtirmoq, yomonlashtirmoq","worsen, aggravate, intensify","The drought exacerbated the food crisis."],
["exaggerate","mubolag'a qilmoq","overstate, inflate, magnify","Do not exaggerate the problem."],
["exalt","ulug'lamoq, maqtamoq","praise, glorify, elevate","The hero was exalted by the people."],
["excavate","qazmoq, ochmoq","dig, unearth, uncover","Archaeologists excavated the ancient city."],
["exceed","oshib ketmoq","surpass, go beyond, outdo","Sales exceeded expectations."],
["excel","a'lo bo'lmoq, ustun turmoq","surpass, outperform, shine","She excels in mathematics."],
["excerpt","parcha, ko'chirma","extract, passage, selection","An excerpt from the book was read."],
["excess","ortiqcha, haddan tashqari","surplus, extra, too much","Excess sugar is bad for health."],
["exclaim","xitob qilmoq, hayqirmoq","shout, cry out, declare","She exclaimed in surprise."],
["exclude","chiqarib tashlamoq, istisno qilmoq","omit, eliminate, bar","Women were excluded from voting."],
["exclusive","eksklyuziv, faqat","sole, limited, restricted","The hotel offers exclusive services."],
["exempt","ozod qilmoq, istisno","free, excuse, release","Children are exempt from the tax."],
["exert","kuch sarflamoq, ta'sir ko'rsatmoq","apply, exercise, wield","She exerted great influence."],
["exhaust","charchash, tugamoq","tire, drain, deplete","The marathon exhausted all runners."],
["exhibit","ko'rsatmoq, namoyish qilmoq","display, show, demonstrate","The gallery exhibits local art."],
["exhilarate","ruhlantirmoq, xursand qilmoq","thrill, excite, delight","The ride exhilarated the children."],
["exile","surgun, badarg'a","banishment, expulsion, deportation","The poet lived in exile for ten years."],
["exodus","ommaviy ko'chish","departure, migration, evacuation","The war caused a mass exodus."],
["exonerate","oqlash, tozalamoq","clear, acquit, vindicate","New evidence exonerated the prisoner."],
["exotic","ekzotik, g'ayrioddiy","foreign, unusual, rare","The island has exotic wildlife."],
["expand","kengaymoq, kengaytirmoq","grow, extend, enlarge","The company plans to expand globally."],
["expatriate","chet elda yashovchi","emigrant, exile, foreigner","Many expatriates live in Dubai."],
["expedient","foydali, qulay","practical, advantageous, convenient","The expedient solution was chosen."],
["expedite","tezlashtirmoq","hasten, accelerate, speed up","We need to expedite the process."],
["expel","haydash, chiqarish","eject, dismiss, banish","The student was expelled for cheating."],
["expenditure","xarajat, sarf","spending, cost, expense","Government expenditure has risen."],
["expertise","tajriba, mahorat","skill, knowledge, proficiency","Her expertise is highly valued."],
["explicit","aniq, ochiq-oydin","clear, specific, direct","The instructions are explicit."],
["exploit","foydalanmoq, ekspluatatsiya qilmoq","utilize, use, take advantage of","Do not exploit vulnerable people."],
["exponential","tez o'suvchi, eksponensial","rapid, dramatic, steep","Population growth was exponential."],
["exponent","tarafdor, ko'rsatkich","advocate, supporter, index","She is a leading exponent of the theory."],
["export","eksport qilmoq, tashqi savdo","sell abroad, ship out, trade","The country exports oil and gas."],
["expose","fosh qilmoq, ochmoq","reveal, uncover, disclose","The journalist exposed the scandal."],
["expressive","ifodali, ta'sirli","eloquent, meaningful, vivid","Her eyes were very expressive."],
["expropriate","musodara qilmoq","seize, confiscate, take","The government expropriated the land."],
["expulsion","haydash, chiqarib yuborish","removal, ejection, banishment","His expulsion from school shocked everyone."],
["exquisite","nafis, go'zal","beautiful, elegant, fine","The jewelry was exquisite."],
["extant","mavjud, saqlanib qolgan","existing, surviving, remaining","Few copies of the manuscript are extant."],
["extenuating","yengillashtiruvchi","mitigating, justifying, excusing","Extenuating circumstances were considered."],
["exterior","tashqi tomon, tashqi ko'rinish","outside, outer, external","The exterior of the building was renovated."],
["exterminate","qirmoq, yo'q qilmoq","destroy, eliminate, wipe out","Efforts to exterminate pests failed."],
["extort","tovlamoq, majbur qilmoq","blackmail, coerce, squeeze","The gang extorted money from businesses."],
["extravagant","isrofgar, dabdabali","lavish, excessive, wasteful","The wedding was extravagant."],
["extricate","chiqarib olmoq, ozod qilmoq","free, release, extract","He extricated himself from the difficult situation."],
["exuberant","jo'shqin, hayajonli","enthusiastic, energetic, lively","The crowd was exuberant after the win."],
["fabricate","yasamoq, to'qib chiqarmoq","make, invent, forge","He fabricated the evidence."],
["facet","qirra, jihat","aspect, side, dimension","We must examine every facet of the issue."],
["facilitate","osonlashtirmoq, yordam bermoq","help, enable, assist","Technology facilitates learning."],
["faction","guruh, fraksiya","group, party, sect","Rival factions competed for power."],
["fallacy","xato fikr, yolg'on tushuncha","misconception, error, myth","The idea is based on a fallacy."],
["fallible","xato qilishi mumkin","imperfect, erring, flawed","All humans are fallible."],
["falsify","soxtalashtirmoq, o'zgartirmoq","forge, fake, distort","He was accused of falsifying records."],
["fanatic","mutaassib, fanatik","extremist, zealot, radical","Religious fanatics pose a threat."],
["fathom","tushunmoq, anglash","understand, comprehend, grasp","I cannot fathom his reasoning."],
["fatigue","charchoq, holsizlik","tiredness, exhaustion, weariness","Mental fatigue affects performance."],
["feasible","amalga oshiriladigan","possible, practical, viable","The plan is financially feasible."],
["feeble","kuchsiz, zaif","weak, frail, delicate","The feeble argument was easily dismissed."],
["feign","o'zini ... qilib ko'rsatmoq","pretend, fake, simulate","She feigned illness to skip work."],
["felicity","baxt, saodаt, mos kelish","happiness, joy, aptness","She expressed herself with felicity."],
["ferment","bijg'ish, hayajon","unrest, agitation, turmoil","Social ferment led to revolution."],
["ferocious","yirtqich, shafqatsiz","fierce, savage, violent","The ferocious storm destroyed homes."],
["fertile","hosildor, unumdor","productive, rich, fruitful","The fertile land yields good crops."],
["fervent","otashin, jo'shqin","passionate, ardent, intense","She is a fervent supporter."],
["festive","bayramona, shod","celebratory, joyful, merry","The festive atmosphere was delightful."],
["fetid","badbo'y, sassigan","smelly, foul, stinking","A fetid smell came from the sewer."],
["feud","adovat, dushmanlik","quarrel, rivalry, vendetta","The family feud lasted decades."],
["fickle","o'zgaruvchan, beqaror","changeable, capricious, inconstant","Fashion trends are fickle."],
["figurative","ko'chma ma'noli","metaphorical, symbolic","The expression is figurative, not literal."],
["fiscal","moliyaviy, byudjet","financial, monetary, budgetary","Fiscal policy affects the economy."],
["flagrant","ochiqdan-ochiq, dahshatli","blatant, obvious, outrageous","It was a flagrant violation of the law."],
["flair","iste'dod, uslub","talent, style, aptitude","She has a flair for design."],
["flaw","nuqson, kamchilik","defect, imperfection, weakness","The plan has a major flaw."],
["fleeting","tez o'tuvchi, o'tkinchi","brief, temporary, transient","The moment was fleeting."],
["flexible","egiluvchan, moslashuvchan","adaptable, versatile, elastic","A flexible schedule helps work-life balance."],
["fluctuate","o'zgarib turmoq","vary, change, oscillate","Temperatures fluctuate throughout the day."],
["fluent","ravon, erkin","proficient, smooth, flowing","She is fluent in four languages."],
["fodder","yem, ozuqa","feed, food, sustenance","The scandal provided fodder for the press."],
["foible","kichik kamchilik","weakness, flaw, quirk","Everyone has their little foibles."],
["foment","qo'zg'atmoq, undamoq","incite, provoke, stir up","The speech fomented unrest."],
["forbid","taqiqlamoq, man qilmoq","ban, prohibit, prevent","The law forbids discrimination."],
["forecast","bashorat qilmoq, prognoz","predict, project, estimate","The forecast predicts rain tomorrow."],
["forfeit","yo'qotmoq, jarimaga tortmoq","lose, surrender, sacrifice","He forfeited his right to appeal."],
["forge","yasash, soxtalash","create, fabricate, form","They forged a strong alliance."],
["formidable","kuchli, dahshatli","powerful, impressive, daunting","She is a formidable competitor."],
["forsake","tark etmoq, tashlab ketmoq","abandon, desert, leave","He forsook his old way of life."],
["fortify","mustahkamlash, kuchaytirmoq","strengthen, reinforce, protect","They fortified the city walls."],
["foster","tarbiyalamoq, rivojlantirmoq","encourage, promote, nurture","The program fosters creativity."],
["founder","asoschisi, cho'kmoq","creator, sink, fail","The founder started the company in a garage."],
["fragile","mo'rt, nozik","delicate, breakable, weak","Handle the fragile items carefully."],
["fragmented","parchalangan, bo'lingan","broken, divided, scattered","The market is highly fragmented."],
["franchise","franshiza, huquq","license, right, concession","She bought a restaurant franchise."],
["frantic","vahima, shoshqaloq","panicked, desperate, frenzied","She made a frantic search for her keys."],
["fraud","firibgarlik, soxtakor","deception, scam, cheating","Insurance fraud costs billions annually."],
["frugal","tejamkor, kamtar","thrifty, economical, careful","A frugal lifestyle helps save money."],
["fulfill","bajarmoq, amalga oshirmoq","achieve, complete, satisfy","She fulfilled her lifelong dream."],
["futile","befoyda, ma'nosiz","useless, pointless, vain","The attempt was futile."],
["galvanize","harakatga keltirmoq, undamoq","motivate, stimulate, inspire","The speech galvanized the crowd."],
["garner","to'plamoq, yig'moq","gather, collect, accumulate","She garnered support for her cause."],
["gauge","o'lchoq, o'lchamoq","measure, assess, estimate","We need to gauge public opinion."],
["genesis","boshlanishi, paydo bo'lishi","origin, beginning, creation","The genesis of the idea was accidental."],
["genocide","genotsid, qirg'in","mass murder, extermination","Genocide is a crime against humanity."],
["genre","janr, tur","type, category, style","She writes in the mystery genre."],
["genteel","nazokat, madaniyatli","refined, polite, elegant","She has genteel manners."],
["genuine","haqiqiy, samimiy","real, authentic, sincere","His apology was genuine."],
["germane","tegishli, aloqador","relevant, pertinent, applicable","The point is not germane to the discussion."],
["germinate","unmoq, o'smoq","sprout, grow, develop","The seeds germinated after a week."],
["gesticulate","qo'l harakatlari bilan tushuntirmoq","gesture, wave, signal","He gesticulated wildly while speaking."],
["glean","yig'moq, to'plamoq","gather, collect, extract","She gleaned useful information from the report."],
["glib","shippak, yuza","superficial, slick, smooth","His glib answers did not convince anyone."],
["global","global, dunyo bo'ylab","worldwide, international, universal","Global warming affects everyone."],
["glossary","lug'at, atamalar ro'yxati","vocabulary, word list, dictionary","The book includes a glossary of terms."],
["glutton","ochko'z, to'ymas","overeater, greedy person","He is a glutton for punishment."],
["govern","boshqarmoq, idora qilmoq","rule, control, manage","Laws govern society."],
["gracious","mehribon, iltifotli","kind, courteous, polite","She was a gracious host."],
["gradual","asta-sekin, bosqichma-bosqich","slow, progressive, steady","There was a gradual improvement."],
["grand","ulug'vor, buyuk","magnificent, splendid, impressive","The palace has a grand entrance."],
["gratify","mamnun qilmoq, qondirmoq","please, satisfy, delight","The results gratified everyone."],
["gratitude","minnatdorchilik","thankfulness, appreciation, thanks","She expressed gratitude for the help."],
["grave","jiddiy, qabr","serious, severe, tomb","The situation is extremely grave."],
["gravity","tortishish kuchi, jiddiylik","seriousness, weight, importance","The gravity of the situation was clear."],
["gregarious","odomlarga yaqin, ochiq","sociable, outgoing, friendly","She has a gregarious nature."],
["grief","qayg'u, motam","sorrow, sadness, mourning","He was overcome with grief."],
["grievance","shikoyat, norozilik","complaint, objection, protest","Workers raised their grievances."],
["grim","qo'rqinchli, qattiq","bleak, harsh, severe","The grim reality was hard to accept."],
["gross","yalpi, qo'pol","total, crude, vulgar","Gross income before deductions."],
["groundwork","asos, poydevor","foundation, basis, preparation","The groundwork for the project was laid."],
["guarantee","kafolat, ta'minot","assurance, warranty, promise","Quality is guaranteed."],
["guardian","vasiy, himoyachi","protector, custodian, keeper","Parents are the guardians of children."],
["guerrilla","partizan, gerilla","rebel, fighter, insurgent","Guerrilla warfare was used."],
["gullible","ishonuvchan, sodda","naive, credulous, trusting","Scammers target gullible people."],
];

async function seed() {
    const SQL = await initSqlJs();
    let db;
    if (fs.existsSync(DB_PATH)) {
        const buffer = fs.readFileSync(DB_PATH);
        db = new SQL.Database(buffer);
    } else {
        db = new SQL.Database();
        db.run(`CREATE TABLE IF NOT EXISTS words (id INTEGER PRIMARY KEY AUTOINCREMENT, english TEXT NOT NULL, uzbek TEXT NOT NULL, synonyms TEXT DEFAULT '', example TEXT DEFAULT '', score INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
    }
    const existing = new Set();
    const rows = db.exec('SELECT english FROM words');
    if (rows.length > 0) rows[0].values.forEach(r => existing.add(r[0].toLowerCase()));
    let added = 0;
    const stmt = db.prepare('INSERT INTO words (english, uzbek, synonyms, example) VALUES (?, ?, ?, ?)');
    for (const [eng, uzb, syn, ex] of words) {
        if (!existing.has(eng.toLowerCase())) {
            stmt.run([eng, uzb, syn || '', ex || '']);
            existing.add(eng.toLowerCase());
            added++;
        }
    }
    stmt.free();
    const data = db.export();
    fs.writeFileSync(DB_PATH, Buffer.from(data));
    const total = db.exec('SELECT COUNT(*) FROM words');
    console.log(`${added} ta yangi so'z qo'shildi. Jami: ${total[0].values[0][0]} ta so'z.`);
    db.close();
}
seed().catch(console.error);
