const path = require('path');
const initSqlJs = require('sql.js');
const fs = require('fs');

const DB_PATH = path.join(__dirname, 'words.db');

const words = [
// ===== ACADEMIC & FORMAL VOCABULARY (Part 2) =====
["abolish","bekor qilmoq, tugatmoq","eliminate, end, cancel","The government abolished the old tax system."],
["abrupt","to'satdan, kutilmagan","sudden, unexpected, sharp","The meeting came to an abrupt end."],
["abstain","tiyilmoq, voz kechmoq","refrain, avoid, withhold","He abstained from voting on the issue."],
["abundance","mo'llik, ko'plik","plenty, wealth, profusion","The region has an abundance of natural resources."],
["accessible","qulay, kirish mumkin","reachable, available, approachable","The building is accessible to wheelchair users."],
["acclaim","e'tirof, maqtash","praise, recognition, applause","The novel received widespread acclaim."],
["accord","kelishuv, bitim","agreement, treaty, harmony","The peace accord was signed by both leaders."],
["accountability","javobgarlik","responsibility, answerability, liability","There must be greater accountability in government."],
["accrue","yig'ilmoq, to'planmoq","accumulate, gather, build up","Interest accrues on the savings account monthly."],
["acute","o'tkir, kuchli","severe, intense, sharp","There is an acute shortage of clean water."],
["adamant","qat'iy, o'jar","firm, resolute, unyielding","She was adamant about her decision."],
["adhere","rioya qilmoq, yopishmoq","follow, stick, comply","All employees must adhere to the dress code."],
["adjacent","yondosh, tutash","next to, adjoining, bordering","The hotel is adjacent to the beach."],
["administer","boshqarmoq, bermoq","manage, govern, dispense","The nurse administered the medication."],
["admiration","hayrat, qoyillik","respect, esteem, awe","She earned the admiration of her peers."],
["advent","kelishi, paydo bo'lishi","arrival, emergence, beginning","The advent of the internet changed everything."],
["adversity","qiyinchilik, musibat","hardship, difficulty, misfortune","She overcame great adversity in her life."],
["affiliate","filial, bog'lanmoq","associate, branch, partner","The company is affiliated with a major university."],
["affluent","badavlat, boy","wealthy, rich, prosperous","The affluent neighborhood has large houses."],
["aftermath","oqibat, natija","consequence, result, repercussion","The aftermath of the war lasted for decades."],
["aggression","tajovuz, hujum","hostility, violence, attack","Military aggression was condemned by all nations."],
["agitate","bezovta qilmoq, tashviqot qilmoq","disturb, provoke, stir","The news agitated the public."],
["align","tekislamoq, moslash","adjust, arrange, agree","The company aligned its goals with market demands."],
["allegiance","sodiqlik, sadoqat","loyalty, devotion, fidelity","Citizens owe allegiance to their country."],
["allot","ajratmoq, taqsimlamoq","allocate, assign, distribute","Each student was allotted 30 minutes for the presentation."],
["allude","ishora qilmoq","hint, refer, suggest","He alluded to problems within the organization."],
["altruism","beg'arazlik, fidoyilik","selflessness, generosity, charity","Altruism is a valued trait in society."],
["amalgamate","birlashtirmoq, qo'shmoq","merge, combine, unite","The two companies amalgamated into one."],
["ambivalent","ikkilanuvchi","uncertain, undecided, mixed","She felt ambivalent about moving abroad."],
["amenity","qulaylik, sharoit","facility, convenience, service","The hotel offers many amenities."],
["amiable","do'stona, samimiy","friendly, pleasant, likeable","The teacher was amiable and approachable."],
["analogous","o'xshash, analog","similar, comparable, parallel","The situation is analogous to what happened before."],
["anecdote","latifa, kichik hikoya","story, tale, account","He told an amusing anecdote about his childhood."],
["anguish","azob, iztirob","suffering, agony, pain","The family experienced great anguish."],
["annex","qo'shib olmoq, ilova","attach, add, supplement","The country annexed the territory."],
["annotate","izoh yozmoq","comment, note, explain","Students were asked to annotate the text."],
["anomaly","anomaliya, g'ayritabiiy holat","irregularity, exception, deviation","The data showed an anomaly that needed investigation."],
["antagonist","raqib, dushman","opponent, adversary, rival","The antagonist in the story is a corrupt politician."],
["anthropology","antropologiya","study of humans, ethnology","She studied anthropology at university."],
["apathy","befarqlik, loqaydlik","indifference, disinterest, passivity","Voter apathy is a serious concern."],
["apprehend","tushunmoq, qo'lga olmoq","arrest, understand, catch","Police apprehended the suspect."],
["apprentice","shogird, o'rganuvchi","trainee, learner, novice","He started as an apprentice carpenter."],
["apt","mos, loyiq","appropriate, suitable, fitting","That is an apt description of the situation."],
["arable","ekin ekiladigan","cultivable, farmable, fertile","Arable land is becoming scarce."],
["arbitrary","ixtiyoriy, o'zboshimcha","random, subjective, capricious","The decision seemed entirely arbitrary."],
["ardent","otashin, ishtiyoqli","passionate, enthusiastic, fervent","He is an ardent supporter of the team."],
["arid","quruq, suvsiz","dry, barren, parched","The arid climate makes farming difficult."],
["aristocracy","aristokratiya, zodagonlar","nobility, elite, upper class","The aristocracy held power for centuries."],
["articulate","aniq ifodalash, ravon","express, eloquent, fluent","She is very articulate in her arguments."],
["ascertain","aniqlash, bilmoq","determine, discover, find out","We need to ascertain the facts."],
["aspire","intilmoq, orzu qilmoq","aim, hope, strive","She aspires to become a scientist."],
["assent","rozilik bermoq","agree, consent, approve","The committee gave its assent to the plan."],
["assertion","da'vo, tasdiqlash","claim, declaration, statement","His assertion was supported by evidence."],
["astute","zukko, aqlli","shrewd, clever, perceptive","She made an astute observation."],
["asylum","boshpana, panoh","refuge, shelter, sanctuary","The refugees sought asylum in neighboring countries."],
["atrocity","vahshiylik, dahshatli ish","horror, brutality, cruelty","War atrocities were documented by journalists."],
["attenuate","susaytirmoq, kuchsizlantirmoq","weaken, reduce, diminish","The walls attenuate the sound."],
["attest","guvohlik bermoq","certify, confirm, verify","The documents attest to his qualifications."],
["audacious","jasur, dovyurak","bold, daring, brave","It was an audacious plan."],
["audit","tekshiruv, audit","review, inspection, examination","The company underwent a financial audit."],
["augment","oshirmoq, ko'paytirmoq","increase, enhance, supplement","She augmented her income with freelance work."],
["austerity","tejamkorlik, qat'iylik","frugality, strictness, severity","The government introduced austerity measures."],
["authentic","haqiqiy, asl nusxa","genuine, real, original","The restaurant serves authentic Italian food."],
["autonomy","muxtoriyat, mustaqillik","independence, self-governance, freedom","The region was granted greater autonomy."],
["avant-garde","avangard, ilg'or","innovative, experimental, cutting-edge","The artist was known for her avant-garde style."],
["aversion","nafrat, yoqtirmaslik","dislike, hatred, reluctance","He has an aversion to public speaking."],

// ===== BUSINESS & ECONOMICS =====
["acquisition","sotib olish, ega bo'lish","purchase, takeover, gaining","The acquisition of the company cost millions."],
["bankruptcy","bankrotlik","insolvency, ruin, failure","The company filed for bankruptcy."],
["boom","ko'tarilish, gullab-yashnash","growth, surge, expansion","The housing boom ended suddenly."],
["brokerage","brokerlik, vositachilik","agency, mediation, dealing","The brokerage firm handles stock trading."],
["capital","kapital, poytaxt","funds, money, assets","The company raised capital for expansion."],
["commerce","savdo, tijorat","trade, business, exchange","International commerce has grown rapidly."],
["commodity","tovar, mahsulot","product, goods, merchandise","Gold is a valuable commodity."],
["consumer","iste'molchi","buyer, customer, purchaser","Consumer spending drives the economy."],
["corporation","korporatsiya","company, firm, enterprise","The corporation employs 50,000 people."],
["deficit","deficit, kamomad","shortfall, shortage, gap","The trade deficit has widened."],
["depreciation","qiymatdan tushish","decline, decrease, devaluation","The depreciation of the currency affected imports."],
["dividend","dividend, foyda ulushi","profit share, return, yield","Shareholders received a generous dividend."],
["embargo","embargo, taqiq","ban, restriction, blockade","An oil embargo was imposed on the country."],
["entrepreneur","tadbirkor, ishbilarmon","businessman, founder, innovator","The young entrepreneur started a tech company."],
["equity","tenglik, kapital ulushi","fairness, shares, ownership","The company increased shareholder equity."],
["expenditure","xarajat, sarf","spending, cost, outlay","Public expenditure on health has risen."],
["fiscal","moliyaviy, fiskal","financial, monetary, budgetary","The government announced new fiscal policies."],
["franchise","franshiza, imtiyoz","license, concession, permit","She bought a fast-food franchise."],
["gross","yalpi, umumiy","total, overall, entire","The gross domestic product increased by 3%."],
["incentive","rag'bat, undov","motivation, reward, stimulus","Tax incentives encourage investment."],
["increment","o'sish, qo'shimcha","increase, addition, rise","Employees receive an annual increment."],
["inflation","inflyatsiya","price rise, devaluation","Inflation reached 5% this year."],
["inventory","inventar, zahira","stock, supplies, merchandise","The store needs to update its inventory."],
["invoice","hisob-faktura","bill, receipt, statement","Please send the invoice to our office."],
["liability","majburiyat, javobgarlik","debt, obligation, responsibility","The company has significant liabilities."],
["liquidate","tugatmoq, sotib yubormoq","dissolve, sell off, close","The firm was forced to liquidate its assets."],
["lucrative","foydali, daromadli","profitable, rewarding, gainful","Real estate can be a lucrative investment."],
["merger","qo'shilish, birlashish","union, amalgamation, combination","The merger of the two banks created a giant."],
["monopoly","monopoliya, yakkahokimlik","dominance, exclusivity","The company has a monopoly in the market."],
["mortgage","ipoteka","loan, home loan, financing","She took out a mortgage to buy a house."],
["negotiate","muzokara qilmoq","discuss, bargain, deal","They negotiated the terms of the contract."],
["overhead","qo'shimcha xarajat","expenses, costs, outgoings","The company reduced its overhead costs."],
["procurement","xarid qilish, ta'minlash","purchasing, acquisition, buying","The procurement process follows strict rules."],
["profitable","foydali, daromadli","lucrative, rewarding, successful","The business became profitable after two years."],
["prospectus","prospekt, taklif","brochure, catalog, plan","The university sent us a prospectus."],
["quota","kvota, me'yor","limit, allocation, share","Import quotas protect domestic industries."],
["recession","tanazzul, inqiroz","downturn, slump, decline","The recession led to widespread unemployment."],
["reimburse","qaytarib bermoq","repay, compensate, refund","The company will reimburse your travel expenses."],
["retail","chakana savdo","sales, commerce, trade","Retail sales increased during the holiday season."],
["revenue","daromad, tushum","income, earnings, profit","The company's annual revenue exceeded expectations."],
["shareholder","aksiyador","investor, stockholder, owner","Shareholders approved the merger."],
["solvent","to'lovga qodir","financially stable, creditworthy","The company remains solvent despite losses."],
["subsidiary","sho'ba korxona","branch, division, affiliate","The firm has subsidiaries in ten countries."],
["surplus","ortiqcha, profitsit","excess, remainder, extra","The country had a budget surplus."],
["tariff","tarif, bojxona solig'i","duty, tax, levy","New tariffs were imposed on imported goods."],
["transaction","bitim, amaliyot","deal, exchange, operation","Online transactions are increasing rapidly."],
["turnover","aylanma, kadrlar almashinuvi","revenue, sales, staff change","The company has a high staff turnover."],
["venture","sarmoya, tavakkalchilik","enterprise, undertaking, project","The joint venture was successful."],
["wholesale","ulgurji savdo","bulk selling, trade","Wholesale prices are lower than retail."],

// ===== LAW & POLITICS =====
["acquit","oqlamoq, unvon bermoq","clear, absolve, exonerate","The jury acquitted the defendant."],
["advocate","himoyachi, tarafdor","supporter, defender, proponent","She is an advocate for children's rights."],
["amnesty","amnistiya, avf","pardon, forgiveness, clemency","The government declared an amnesty for political prisoners."],
["anarchy","anarxiya, tartibsizlik","chaos, disorder, lawlessness","The collapse of government led to anarchy."],
["ballot","ovoz berish, saylov byulleteni","vote, poll, election","Citizens cast their ballots in the election."],
["bipartisan","ikki partiyaviy","cross-party, nonpartisan","The bill received bipartisan support."],
["cabinet","vazirlar mahkamasi","council, ministry, government","The cabinet discussed the new policy."],
["censor","tsenzura qilmoq","suppress, ban, restrict","The government censored the press."],
["charter","xartiya, nizom","constitution, document, agreement","The UN Charter protects human rights."],
["clemency","rahm-shafqat","mercy, leniency, pardon","The prisoner appealed for clemency."],
["coerce","majbur qilmoq, zo'rlamoq","force, compel, pressure","He was coerced into signing the agreement."],
["compliance","rioya qilish, muvofiqlik","obedience, adherence, conformity","Compliance with the law is mandatory."],
["compulsory","majburiy","mandatory, obligatory, required","Voting is compulsory in some countries."],
["confiscate","musodara qilmoq","seize, impound, take","Police confiscated illegal goods."],
["consensus","umumiy kelishuv","agreement, unanimity, accord","The committee reached a consensus."],
["constituent","saylovchi, tarkibiy qism","voter, component, member","The politician met with her constituents."],
["contempt","haqorat, nafrat","disdain, disrespect, scorn","He was held in contempt of court."],
["convict","hukm qilmoq, mahkum","sentence, condemn, find guilty","The court convicted him of fraud."],
["decree","farmon, qaror","order, edict, ruling","The president issued a decree."],
["defamation","tuhmat, obro'sizlantirish","slander, libel, smear","She sued the newspaper for defamation."],
["defendant","javobgar, ayblanuvchi","accused, respondent, suspect","The defendant pleaded not guilty."],
["depose","hokimiyatdan ag'darmoq","overthrow, remove, oust","The dictator was deposed in a revolution."],
["detention","hibsga olish, saqlash","custody, imprisonment, confinement","He was held in detention for 48 hours."],
["diplomat","diplomat","ambassador, envoy, negotiator","The diplomat negotiated a peace treaty."],
["embargo","embargo, taqiq","ban, prohibition, restriction","The trade embargo lasted for years."],
["enact","qonun qabul qilmoq","pass, legislate, establish","Parliament enacted a new education law."],
["exile","surgun, badarg'a","banishment, deportation, expulsion","The political leader was forced into exile."],
["extradite","boshqa davlatga bermoq","deport, hand over, transfer","The suspect was extradited to face trial."],
["felony","og'ir jinoyat","crime, offense, violation","Armed robbery is a serious felony."],
["governance","boshqaruv","management, administration, rule","Good governance is essential for development."],
["grievance","shikoyat, norozilik","complaint, objection, protest","Workers filed a grievance against management."],
["immunity","immunitet, daxlsizlik","protection, exemption, resistance","Diplomatic immunity protects ambassadors."],
["impeach","javobgarlikka tortmoq","accuse, charge, indict","Congress voted to impeach the president."],
["impartial","xolis, betaraf","fair, unbiased, neutral","Judges must be impartial."],
["inaugurate","tantanali ochish, rasman boshlamoq","open, launch, commence","The president was inaugurated in January."],
["indict","ayblov e'lon qilmoq","charge, accuse, prosecute","The grand jury indicted the suspect."],
["judiciary","sud hokimiyati","courts, legal system, judges","An independent judiciary is essential."],
["jurisdiction","yurisdiksiya, vakolat","authority, power, domain","The case falls under federal jurisdiction."],
["lawsuit","sudlov, da'vo","case, litigation, claim","She filed a lawsuit against the company."],
["legislature","qonun chiqaruvchi organ","parliament, congress, assembly","The legislature passed the bill unanimously."],
["legitimate","qonuniy, to'g'ri","legal, lawful, valid","He has a legitimate claim to the property."],
["litigation","sud jarayoni","lawsuit, legal action, prosecution","The litigation lasted for three years."],
["lobby","lobbi qilmoq, ta'sir o'tkazmoq","campaign, advocate, influence","Environmental groups lobbied for stricter laws."],
["mandate","mandat, buyruq","order, command, directive","The government has a mandate to reform education."],
["mediator","vositachi","arbitrator, negotiator, go-between","A mediator was appointed to resolve the dispute."],
["municipal","shahar, munitsipal","civic, local, urban","Municipal elections are held every four years."],
["ordinance","qaror, farmoyish","regulation, decree, law","The city passed an ordinance banning plastic bags."],
["parole","shartli ozodlik","release, probation, freedom","The prisoner was granted parole."],
["partisan","tarafdor, partiyaviy","biased, supporter, factional","The media coverage was highly partisan."],
["petition","ariza, iltimos","appeal, request, plea","Thousands signed the petition against the project."],
["plaintiff","da'vogar, shikoyatchi","complainant, accuser, claimant","The plaintiff demanded compensation."],
["plebiscite","referendum, umumxalq ovoz berishi","vote, referendum, poll","A plebiscite was held on the constitutional change."],
["precedent","pretsedent, oldingi misol","example, model, standard","The court ruling set an important precedent."],
["prosecution","ayblov, sudlov","indictment, legal action, trial","The prosecution presented strong evidence."],
["ratification","ratifikatsiya, tasdiqlash","approval, confirmation, endorsement","The treaty awaits ratification."],
["repeal","bekor qilmoq","revoke, cancel, annul","The government repealed the controversial law."],
["sanction","sanktsiya, jazo","penalty, punishment, restriction","Economic sanctions were imposed on the country."],
["sovereignty","suverenitet, mustaqillik","independence, autonomy, supremacy","National sovereignty must be respected."],
["statute","qonun, nizom","law, regulation, act","The statute was passed in 2020."],
["subpoena","sud chaqiruvi","summons, court order, writ","She was served with a subpoena to testify."],
["suffrage","saylov huquqi","voting rights, franchise","Universal suffrage was achieved after years of struggle."],
["tribunal","tribunal, sud","court, panel, hearing","The war crimes tribunal convicted the general."],
["tyranny","zulm, istibdod","oppression, despotism, dictatorship","The people revolted against tyranny."],
["unconstitutional","konstitutsiyaga zid","illegal, unlawful, invalid","The court declared the law unconstitutional."],
["verdict","hukm, qaror","judgment, ruling, decision","The jury delivered a guilty verdict."],
["veto","veto, taqiqlash","reject, block, prohibit","The president vetoed the bill."],

// ===== SCIENCE & RESEARCH =====
["acceleration","tezlanish","speeding up, quickening","The acceleration of particles produces energy."],
["anatomy","anatomiya","body structure, physiology","She studied human anatomy in medical school."],
["anomaly","anomaliya, g'ayritabiiy","irregularity, deviation, abnormality","Scientists detected an anomaly in the data."],
["apparatus","asbob-uskunalar","equipment, device, instrument","The laboratory apparatus was state-of-the-art."],
["archaeology","arxeologiya","study of ancient remains","Archaeology reveals how ancient people lived."],
["astronomy","astronomiya","star science, astrophysics","Astronomy is the study of celestial bodies."],
["bacteria","bakteriya","germs, microbes, microorganisms","Bacteria can cause infections."],
["biochemistry","biokimyo","biological chemistry, molecular biology","She specializes in biochemistry."],
["botany","botanika","plant science, plant biology","Botany is the study of plants."],
["calibrate","kalibrlash, sozlamoq","adjust, fine-tune, standardize","The instruments must be calibrated regularly."],
["catalyst","katalizator, turtki","stimulus, trigger, accelerator","The discovery was a catalyst for further research."],
["cell","hujayra","unit, organism, compartment","Cells are the building blocks of life."],
["chromosome","xromosoma","genetic material, DNA carrier","Humans have 23 pairs of chromosomes."],
["clinical","klinik, amaliy","medical, practical, therapeutic","Clinical trials tested the new drug."],
["clone","klon, nusxa olmoq","copy, duplicate, replicate","Scientists cloned the sheep in 1996."],
["compound","birikmа, murakkab","mixture, combination, complex","Water is a chemical compound of hydrogen and oxygen."],
["condensation","kondensatsiya, quyuqlashish","liquefaction, compression, concentration","Condensation forms when warm air meets cold surfaces."],
["congenital","tug'ma","inborn, innate, hereditary","The child had a congenital heart defect."],
["contamination","ifloslanish","pollution, infection, corruption","Water contamination is a serious health risk."],
["correlation","korrelyatsiya, bog'liqlik","connection, relationship, association","There is a correlation between smoking and cancer."],
["decompose","chirib ketmoq, parchalanmoq","decay, rot, break down","Organic matter decomposes naturally."],
["defect","nuqson, kamchilik","flaw, fault, imperfection","The product was recalled due to a defect."],
["dehydration","suvsizlanish","drying out, water loss","Dehydration can be dangerous in hot weather."],
["density","zichlik","thickness, concentration, compactness","The density of the material determines its weight."],
["diagnosis","tashxis qo'yish","identification, detection, analysis","Early diagnosis improves treatment outcomes."],
["dilute","suyultirmoq","thin, weaken, water down","Dilute the solution with water."],
["dissect","kesib tekshirmoq","analyze, examine, cut up","Students dissected a frog in biology class."],
["dissolve","eritmoq, hal qilmoq","melt, liquefy, break down","Salt dissolves easily in water."],
["DNA","DNK","genetic code, genes, genome","DNA carries genetic information."],
["electrode","elektrod","terminal, conductor, contact","The electrode sends signals to the brain."],
["embryo","embrion, kurtak","fetus, unborn, germ","The embryo develops rapidly in the first weeks."],
["enzyme","ferment, enzim","catalyst, protein","Enzymes speed up chemical reactions in the body."],
["evaporation","bug'lanish","vaporization, drying","Evaporation is part of the water cycle."],
["evolution","evolyutsiya, rivojlanish","development, progression, growth","The theory of evolution explains species diversity."],
["experiment","tajriba, eksperiment","test, trial, investigation","The experiment produced unexpected results."],
["extinct","yo'q bo'lgan","dead, vanished, lost","Dinosaurs became extinct millions of years ago."],
["formula","formula, tarkib","equation, recipe, method","The chemical formula for water is H2O."],
["fossil","qazilma, fossil","remains, relic, trace","Fossils provide evidence of ancient life."],
["fracture","sinish, yoriq","break, crack, rupture","The X-ray revealed a fracture in the bone."],
["frequency","chastota, tezlik","rate, occurrence, regularity","The frequency of earthquakes has increased."],
["fungus","zamburug'","mold, mushroom, yeast","The fungus grows in damp conditions."],
["gene","gen","DNA unit, hereditary factor","Genes determine many physical characteristics."],
["geology","geologiya","earth science, geoscience","Geology studies the structure of the earth."],
["gravity","tortishish kuchi, jiddiylik","attraction, pull, seriousness","Gravity keeps us on the ground."],
["habitat","yashash muhiti","environment, home, territory","The forest is a habitat for many species."],
["hereditary","irsiy, nasliy","genetic, inherited, inborn","The disease is hereditary."],
["hormone","gormon","chemical messenger, secretion","Hormones regulate many body functions."],
["hybrid","gibrid, aralash","crossbreed, mixture, combination","Hybrid cars use both gas and electricity."],
["hypothesis","gipoteza, taxmin","theory, assumption, conjecture","The hypothesis was confirmed by the experiment."],
["immunity","immunitet","resistance, protection, defense","Vaccination provides immunity against diseases."],
["incubate","parvarish qilmoq, rivojlantirmoq","nurture, develop, hatch","The eggs incubate for 21 days."],
["indigenous","mahalliy, tub","native, local, aboriginal","Indigenous plants are adapted to the climate."],
["infection","infektsiya, yuqish","disease, contamination, illness","The infection spread quickly."],
["inflammation","yallig'lanish","swelling, irritation, redness","Inflammation is the body's response to injury."],
["inoculate","emlash, em qilmoq","vaccinate, immunize, inject","Children should be inoculated against measles."],
["insulate","izolyatsiya qilmoq","protect, shield, cover","The walls are insulated to keep heat in."],
["isotope","izotop","variant, form, type","Carbon-14 is a radioactive isotope."],
["kinetic","kinetik, harakatdagi","moving, dynamic, active","Kinetic energy is the energy of motion."],
["larva","lichinka","grub, caterpillar, maggot","The larva develops into a butterfly."],
["magnitude","kattalik, kuchlilik","size, extent, intensity","The earthquake had a magnitude of 7.2."],
["mammal","sutemizuvchi","warm-blooded animal","Dolphins are mammals, not fish."],
["metabolism","metabolizm, moddalar almashinuvi","body chemistry, digestion","Exercise increases your metabolism."],
["microbe","mikrob","germ, bacterium, microorganism","Microbes are everywhere in the environment."],
["molecule","molekula","particle, atom, unit","A water molecule contains two hydrogen atoms."],
["mutation","mutatsiya, o'zgarish","change, alteration, variation","Genetic mutations can cause disease."],
["neuron","neyron, asab hujayrasi","nerve cell, brain cell","Neurons transmit signals in the brain."],
["nucleus","yadro, markaz","core, center, heart","The nucleus contains the cell's DNA."],
["nutrient","ozuqa moddasi","nourishment, food, sustenance","Plants absorb nutrients from the soil."],
["organism","organizm, tirik mavjudot","living thing, creature, being","Every organism needs water to survive."],
["oxide","oksid","compound, rust, chemical","Carbon dioxide is a common oxide."],
["parasite","parazit","leech, freeloader, bloodsucker","The parasite lives inside the host organism."],
["pathogen","patogen, kasallik qo'zg'atuvchi","germ, virus, bacteria","The pathogen caused a widespread epidemic."],
["phenomenon","hodisa, fenomen","occurrence, event, marvel","Aurora borealis is a natural phenomenon."],
["photosynthesis","fotosintez","plant energy production","Photosynthesis converts sunlight into energy."],
["physiology","fiziologiya","body functions, biology","She studied human physiology."],
["plankton","plankton","microorganisms, marine life","Plankton forms the base of the ocean food chain."],
["pollinate","changlamoq","fertilize, cross-pollinate","Bees pollinate flowers as they collect nectar."],
["predator","yirtqich, bosqinchi","hunter, carnivore, aggressor","Lions are apex predators."],
["prey","o'lja","victim, target, quarry","The eagle swooped down on its prey."],
["primate","primat","ape, monkey, human","Humans are classified as primates."],
["probe","zond, tekshirmoq","investigate, examine, explore","The space probe reached Mars."],
["protein","oqsil, protein","amino acid, nutrient","Protein is essential for muscle growth."],
["radioactive","radioaktiv","nuclear, irradiated, contaminated","Radioactive waste must be stored safely."],
["receptor","retseptor","sensor, detector, receiver","Pain receptors send signals to the brain."],
["recombinant","rekombinant","genetically modified, engineered","Recombinant DNA technology revolutionized medicine."],
["reproduce","ko'paymoq, takrorlamoq","breed, multiply, replicate","Bacteria reproduce rapidly."],
["respiration","nafas olish","breathing, ventilation","Cellular respiration produces energy."],
["sediment","cho'kindi, qoldiq","deposit, residue, silt","Sediment accumulates at the bottom of rivers."],
["specimen","namuna, eksponat","sample, example, model","The scientist examined the specimen under a microscope."],
["spectrum","spektr, diapazon","range, scope, band","The visible light spectrum contains seven colors."],
["stem cell","stvol hujayra","base cell, progenitor cell","Stem cell research offers hope for many diseases."],
["stimulus","turtki, qo'zg'atuvchi","incentive, motivation, trigger","The stimulus caused an immediate reaction."],
["strain","shtamm, zo'riqish","type, stress, pressure","A new strain of the virus was discovered."],
["synthesis","sintez, birlashtirish","combination, creation, production","The synthesis of the compound took weeks."],
["taxonomy","taksonomiya, turkumlash","classification, categorization","Taxonomy organizes living things into groups."],
["terrain","yer yuzasi, hudud","landscape, ground, topography","The terrain was rugged and mountainous."],
["thermal","issiqlik, termal","heat-related, warm, hot","Thermal energy is used to generate electricity."],
["tissue","to'qima","cells, material, fabric","Muscle tissue contracts to produce movement."],
["toxic","zaharli, toksik","poisonous, harmful, noxious","Toxic chemicals were found in the water."],
["transplant","transplantatsiya, ko'chirish","transfer, implant, relocate","He received a heart transplant."],
["vaccine","vaksina, emlash","immunization, inoculation, shot","The vaccine was developed in record time."],
["variable","o'zgaruvchi","factor, element, parameter","There are many variables in the experiment."],
["vertebrate","umurtqali","backbone animal, spinal animal","Fish are vertebrates."],
["virus","virus","pathogen, infection, bug","The virus spread across continents."],
["wavelength","to'lqin uzunligi","frequency, wave, band","Different colors have different wavelengths."],
["zoology","zoologiya","animal science, biology","Zoology is the study of animals."],

// ===== ARTS & CULTURE =====
["aesthetic","estetik, go'zallik","artistic, beautiful, visual","The building has great aesthetic value."],
["allegory","allegoriya, majoziy hikoya","parable, fable, symbolism","The novel is an allegory for political corruption."],
["anthology","antologiya, to'plam","collection, compilation, selection","The anthology contains poems from various authors."],
["artifact","artefakt, buyum","object, relic, antique","The museum displays ancient artifacts."],
["biography","tarjimai hol","life story, memoir, profile","She wrote a biography of the famous scientist."],
["calligraphy","xattotlik","handwriting, lettering, penmanship","Arabic calligraphy is a beautiful art form."],
["canvas","tuval, makon","fabric, surface, painting","The artist painted on a large canvas."],
["caricature","karikatura, mubolag'ali tasvir","cartoon, parody, satire","The newspaper published a caricature of the politician."],
["choreography","xoreografiya","dance arrangement, movement design","The choreography of the ballet was stunning."],
["chronicle","solnoma, yilnoma","record, history, account","The book chronicles the history of the city."],
["civilization","sivilizatsiya, madaniyat","culture, society, development","Ancient civilizations built impressive structures."],
["comedy","komediya, kulgili","humor, farce, satire","The comedy show attracted a large audience."],
["compose","yozmoq, tuzmoq","create, write, arrange","Beethoven composed nine symphonies."],
["contemporary","zamonaviy, hozirgi","modern, current, present-day","Contemporary art challenges traditional norms."],
["craft","hunarmandchilik, mahorat","skill, trade, art","Traditional crafts are an important part of culture."],
["critique","tanqid, baholash","review, analysis, assessment","The art critique was published in a major magazine."],
["curator","kurator, mudofaachi","keeper, guardian, director","The museum curator organized the exhibition."],
["dialect","sheva, lahjа","accent, vernacular, local speech","Each region has its own dialect."],
["documentary","hujjatli film","factual film, record, report","The documentary explored climate change."],
["eloquence","notiqlik, fasohаt","fluency, rhetoric, articulacy","His eloquence impressed the audience."],
["epic","epik, ulkan","grand, heroic, monumental","The epic poem tells of ancient battles."],
["excerpt","parcha, iqtibos","extract, passage, clip","She read an excerpt from the novel."],
["exhibition","ko'rgazma, namoyish","display, show, presentation","The art exhibition attracted thousands of visitors."],
["fiction","badiiy adabiyot, to'qima","novel, story, fantasy","She enjoys reading fiction."],
["folklore","folklor, xalq og'zaki ijodi","mythology, legends, traditions","Folklore preserves cultural heritage."],
["gallery","galeriya","museum, exhibition hall, showroom","The gallery displays modern paintings."],
["genre","janr, tur","category, type, style","Science fiction is a popular genre."],
["heritage","meros, madaniy boylik","legacy, tradition, inheritance","The city's heritage sites attract tourists."],
["icon","belgi, ramz, qahramonь","symbol, idol, image","She became an icon of the feminist movement."],
["improvise","badihа go'ylik, tayyor bo'lmasdan","ad-lib, extemporize, wing it","The musician improvised a beautiful melody."],
["inscription","yozuv, bitik","engraving, text, writing","The inscription on the monument is in Latin."],
["instrument","asbob, musiqa asbobi","tool, device, implement","She plays several musical instruments."],
["interpret","izohlash, talqin qilmoq","explain, translate, perform","Each dancer interprets the music differently."],
["legend","afsona, rivoyat","myth, tale, fable","The legend of King Arthur is well known."],
["literary","adabiy","written, bookish, scholarly","She has a deep interest in literary criticism."],
["lyric","qo'shiq so'zlari, lirik","song words, poem, verse","The lyrics of the song are very poetic."],
["manuscript","qo'lyozma","document, script, text","The ancient manuscript was carefully preserved."],
["masterpiece","durdona, shoh asar","chef-d'oeuvre, magnum opus","The painting is considered a masterpiece."],
["memoir","xotira, memuarlar","autobiography, recollection, account","She published her memoir last year."],
["metaphor","metafora, ko'chma ma'no","figure of speech, analogy","Life is a journey is a common metaphor."],
["monument","yodgorlik, monument","memorial, landmark, statue","The monument honors fallen soldiers."],
["mural","devoriy rasm","wall painting, fresco","The mural depicts scenes from local history."],
["mythology","mifologiya","legends, folklore, myths","Greek mythology includes many fascinating stories."],
["narrative","hikoya, rivoyat","story, account, tale","The narrative style is engaging."],
["ode","qasida, maqtov she'r","poem, tribute, hymn","The poet wrote an ode to nature."],
["orchestra","orkestr","ensemble, band, symphony","The orchestra performed Beethoven's Fifth."],
["parable","masal, ibratli hikoya","fable, allegory, moral story","The parable teaches an important lesson."],
["patron","homiy, mijoz","sponsor, supporter, benefactor","The patron funded the art exhibition."],
["performance","ijro, ko'rsatma","show, presentation, act","The performance received a standing ovation."],
["perspective","istiqbol, nuqtai nazar","viewpoint, angle, outlook","The artist used perspective to create depth."],
["playwright","dramaturg","writer, author, scriptwriter","Shakespeare is the most famous English playwright."],
["portrait","portret, tasvir","painting, picture, depiction","The portrait captures her personality perfectly."],
["pottery","kulolchilik, sopol buyumlar","ceramics, earthenware, clay","The museum has a collection of ancient pottery."],
["prose","nasr","writing, text, literature","Her prose style is clear and elegant."],
["protagonist","bosh qahramon","hero, main character, lead","The protagonist faces many challenges."],
["recital","konsert, o'qish","performance, concert, reading","She gave a piano recital at the concert hall."],
["renaissance","uyg'onish davri","rebirth, revival, renewal","The Renaissance produced great works of art."],
["repertoire","repertuar","collection, range, set","The singer has a wide repertoire."],
["rhetoric","ritorika, notiqlik","eloquence, oratory, speech","His rhetoric was powerful and persuasive."],
["satire","satira, kinoya","parody, mockery, irony","The novel is a satire on modern society."],
["sculpture","haykal, o'ymakorlik","statue, carving, figure","The sculpture was made of marble."],
["sonnet","sonet","poem, verse, lyric","Shakespeare wrote 154 sonnets."],
["symphony","simfoniya","orchestral composition, concerto","The symphony was composed in 1808."],
["tragedy","fojia, tragediya","disaster, catastrophe, calamity","The play is a classic Greek tragedy."],
["verse","she'r, band","poetry, stanza, rhyme","The poem has four verses."],
["virtuoso","ustadon, mohir","master, expert, genius","She is a violin virtuoso."],

// ===== PSYCHOLOGY & BEHAVIOR =====
["addiction","o'rganish, qaramlik","dependence, habit, compulsion","Social media addiction is a growing concern."],
["adolescence","o'smirlik davri","teenage years, puberty, youth","Adolescence is a time of rapid change."],
["aggression","tajovuzkorlik, hujumkorlik","hostility, violence, anger","Aggression in children needs to be addressed."],
["altruism","beg'arazlik, o'zgalar uchun yashash","selflessness, charity, generosity","Altruism is a key aspect of human nature."],
["anxiety","tashvish, xavotir","worry, nervousness, unease","Anxiety disorders affect millions of people."],
["attachment","bog'liqlik, qo'shimcha","bond, connection, affection","Secure attachment is important for child development."],
["behavior","xulq-atvor, fe'l","conduct, actions, manner","Animal behavior is studied by ethologists."],
["cognition","bilish, idrok","thinking, perception, understanding","Cognition develops throughout childhood."],
["compulsion","majburiyat, ixtiyorsiz harakat","urge, obsession, drive","He felt a compulsion to check his phone."],
["conditioning","shartlash, o'rgatish","training, habituation, learning","Classical conditioning was studied by Pavlov."],
["conformity","moslashish, bo'ysunish","compliance, obedience, agreement","Social conformity can limit individual expression."],
["consciousness","ong, hushyorlik","awareness, perception, sentience","Consciousness is still a mystery in science."],
["delusion","xomxayol, aldanish","illusion, fantasy, misconception","He suffered from delusions of grandeur."],
["depression","tushkunlik, depressiya","sadness, melancholy, despair","Depression is a treatable mental illness."],
["deviance","og'ish, normadan chetlashish","abnormality, nonconformity","Social deviance challenges established norms."],
["disposition","xarakter, moyillik","temperament, nature, tendency","She has a cheerful disposition."],
["ego","ego, men","self, identity, self-esteem","A strong ego can be both helpful and harmful."],
["emotion","his-tuyg'u, hissiyot","feeling, sentiment, passion","Emotions play a key role in decision-making."],
["empathy","hamdardlik, hamfikrlik","compassion, understanding, sympathy","Empathy allows us to understand others' feelings."],
["extrovert","ekstravert, ochiq odam","outgoing person, socializer","Extroverts enjoy being around people."],
["hallucination","gallyutsinatsiya","illusion, vision, delusion","High fever can cause hallucinations."],
["identity","shaxsiyat, o'zlik","self, personality, character","Cultural identity is shaped by many factors."],
["inhibition","tormozlanish, uyalish","restraint, reserve, shyness","Social inhibition can prevent people from speaking up."],
["instinct","instinkt, tabiiy sezgi","intuition, impulse, nature","Survival instinct is powerful in all animals."],
["intelligence","aql, intellekt","brainpower, intellect, wit","Emotional intelligence is as important as IQ."],
["introvert","introvert, ichki dunyoli","reserved person, loner","Introverts prefer quiet environments."],
["mentality","tafakkur, mentalitet","mindset, attitude, thinking","A growth mentality leads to success."],
["motive","sabab, motiv","reason, purpose, incentive","What was the motive behind the crime?"],
["narcissism","narssissizm, o'zini sevish","self-love, vanity, egotism","Narcissism can damage relationships."],
["neurosis","nevroz, asab kasalligi","anxiety, phobia, disorder","Neurosis can be treated with therapy."],
["obsession","fikrdan ketmaydigan narsa","fixation, preoccupation, mania","Her obsession with perfection was exhausting."],
["paranoia","paranoya, g'ayritabiiy shubha","suspicion, distrust, fear","Paranoia made him distrust everyone."],
["perception","idrok, tushuncha","awareness, understanding, view","Our perception of reality is subjective."],
["personality","shaxsiyat, xarakter","character, temperament, nature","Personality traits develop in early childhood."],
["phobia","fobiya, qo'rquv","fear, dread, aversion","She has a phobia of spiders."],
["prejudice","oldindan hukm qilish, noxolislik","bias, discrimination, intolerance","Racial prejudice must be eliminated."],
["psyche","ruh, psixika","mind, soul, spirit","The human psyche is complex."],
["rationalize","oqlamoq, asoslamoq","justify, explain, reason","He rationalized his bad behavior."],
["resilience","chidamlilik, bardoshlilik","toughness, endurance, adaptability","Resilience helps people cope with adversity."],
["stimulus","turtki, ta'sir","trigger, motivation, incentive","The stimulus produced an immediate response."],
["subconscious","ong osti","unconscious, subliminal, hidden","The subconscious mind influences our behavior."],
["temperament","temperament, xarakter","character, disposition, nature","Each child has a different temperament."],
["therapy","terapiya, davolash","treatment, counseling, healing","Cognitive therapy helps with anxiety."],
["trait","xususiyat, belgi","characteristic, quality, feature","Honesty is an admirable trait."],
["trauma","ruhiy jarohat, travma","shock, injury, distress","Childhood trauma can have lasting effects."],

// ===== GEOGRAPHY & CLIMATE =====
["altitude","balandlik","height, elevation, level","The city is at a high altitude."],
["archipelago","arxipelag, orollar guruhi","island chain, island group","Indonesia is an archipelago."],
["avalanche","qor ko'chkisi","snowslide, landslide","The avalanche blocked the mountain road."],
["basin","havza, vodiyе","valley, depression, bowl","The Amazon basin covers a vast area."],
["canyon","kanyon, darа","gorge, ravine, valley","The Grand Canyon is a famous landmark."],
["cape","burun, o'tmoq","headland, point, promontory","The ship sailed around the cape."],
["climate","iqlim","weather pattern, conditions","The tropical climate is warm and humid."],
["coastal","qirg'oq bo'yi","seaside, shore, littoral","Coastal erosion threatens many communities."],
["continent","qit'a","landmass, mainland","Africa is the second largest continent."],
["crater","krater, chuqur","hollow, cavity, pit","The volcano's crater is very deep."],
["delta","delta, daryoning quyilish joyi","river mouth, estuary","The Nile delta is very fertile."],
["desert","cho'l, sahro","wasteland, barren land","The Sahara is the largest hot desert."],
["equator","ekvator","midline, tropics","The equator divides the earth into two hemispheres."],
["estuary","daryoning dengizga quyilish joyi","river mouth, inlet, delta","The estuary is rich in marine life."],
["expedition","ekspeditsiya, sayohat","journey, voyage, exploration","The expedition explored the Antarctic."],
["fertile","hosildor, unumdor","productive, rich, fruitful","The Nile valley has fertile soil."],
["fjord","fjord, tor qo'ltiq","inlet, bay, cove","Norwegian fjords are breathtakingly beautiful."],
["glacier","muzlik","ice sheet, ice mass","Glaciers are melting due to climate change."],
["hemisphere","yarim shar","half of earth, zone","Australia is in the southern hemisphere."],
["highland","tog'li hudud","upland, plateau, mountains","The Scottish Highlands are beautiful."],
["horizon","ufq, ko'kim","skyline, vista, outlook","The sun set below the horizon."],
["humid","nam, sernam","moist, damp, muggy","The climate is hot and humid."],
["iceberg","aysberg, muzlik","ice mass, ice mountain","Only a small part of an iceberg is visible."],
["irrigation","sug'orish","watering, water supply","Irrigation is essential for farming in dry areas."],
["island","orol","isle, atoll, landmass","The island has a tropical climate."],
["isthmus","bo'g'oz, qurg'oq bo'g'oz","narrow strip, land bridge","Panama is located on an isthmus."],
["lagoon","laguna, ko'l","lake, pond, pool","The lagoon has crystal clear water."],
["landscape","manzara, landshaft","scenery, terrain, view","The landscape was breathtaking."],
["latitude","kenglik","parallel, position, coordinate","The city is located at 40 degrees latitude."],
["longitude","uzunlik","meridian, position, coordinate","The prime meridian is at zero degrees longitude."],
["maritime","dengiz, dengizchilik","naval, oceanic, nautical","The country has a strong maritime tradition."],
["marsh","botqoq, botqoqlik","swamp, wetland, bog","The marsh is home to many bird species."],
["meadow","o'tloq, yaylov","field, grassland, pasture","Wildflowers grow in the meadow."],
["meteorology","meteorologiya","weather science, climatology","Meteorology helps predict weather patterns."],
["monsoon","musson, mavsumiy shamol","seasonal rain, downpour","The monsoon season brings heavy rains."],
["mountain","tog'","peak, summit, mount","Mount Everest is the highest mountain."],
["oasis","vohа, daraxtzor","refuge, haven, green area","The desert oasis provided water for travelers."],
["ocean","okean","sea, deep water, marine","The Pacific Ocean is the largest."],
["peninsula","yarim orol","cape, promontory, headland","Korea is a peninsula."],
["plateau","plato, yassi tog'","tableland, highland, mesa","The plateau is at 3000 meters elevation."],
["polar","qutbiy","arctic, freezing, icy","Polar ice caps are melting rapidly."],
["precipitation","yog'ingarchilik","rain, snow, moisture","Annual precipitation varies by region."],
["reef","rif, qoyatosh","coral, ridge, shelf","The Great Barrier Reef is under threat."],
["reservoir","suv ombori","lake, storage, dam","The reservoir supplies water to the city."],
["ridge","tizma, tog' tizmasi","crest, chain, range","The mountain ridge extends for miles."],
["savanna","savanna, o'tloq","grassland, plain, prairie","African savannas are home to many animals."],
["seismic","seysmik, zilzila bilan bog'liq","earthquake-related, tectonic","Seismic activity increased before the eruption."],
["strait","bo'g'oz","channel, passage, narrows","The Strait of Gibraltar connects two seas."],
["subtropical","subtropik","warm, semi-tropical, mild","The region has a subtropical climate."],
["summit","cho'qqi, sammit","peak, top, apex","They reached the summit at dawn."],
["terrain","yer yuzasi, tuproq","landscape, ground, topography","The terrain is ideal for hiking."],
["tidal","to'lqin bilan bog'liq","wave-related, oceanic","Tidal energy is a renewable resource."],
["topography","topografiya, yer yuzasi shakli","landscape, terrain, geography","The topography of the region is mostly flat."],
["tributary","irmoq, suv tarmoq","branch, stream, feeder","The river has many tributaries."],
["tropical","tropik, issiq","equatorial, hot, humid","Tropical forests are very biodiverse."],
["tsunami","tsunami, to'lqin","tidal wave, seismic wave","The tsunami caused massive destruction."],
["tundra","tundra, sovuq cho'l","frozen plain, arctic region","The tundra is too cold for trees to grow."],
["valley","vodiy, darа","dale, glen, gorge","The valley is surrounded by mountains."],
["volcano","vulqon","crater, mountain, magma vent","The volcano erupted without warning."],
["waterfall","sharshara","cascade, falls, cataract","Niagara Falls is a famous waterfall."],
["wetland","botqoqlik, suv bosgan hudud","marsh, swamp, bog","Wetlands are important for biodiversity."],

// ===== MEDIA & COMMUNICATION =====
["broadcast","eshittirish, translyatsiya","transmit, air, telecast","The news was broadcast live."],
["bulletin","byulleten, xabar","announcement, report, notice","The weather bulletin warned of storms."],
["censorship","tsenzura","suppression, restriction, control","Censorship limits freedom of expression."],
["circulation","tiraj, aylanish","distribution, spread, flow","The newspaper has a large circulation."],
["commentary","sharh, izoh","analysis, review, remarks","The expert provided commentary on the event."],
["correspondence","yozishmalar, muvofiiqlik","letters, communication, messages","She maintained correspondence with her professor."],
["coverage","yoritish, qamrov","reporting, news, exposure","The media coverage of the event was extensive."],
["credibility","ishonchlilik","trustworthiness, reliability, believability","The journalist's credibility was questioned."],
["deadline","oxirgi muddat","time limit, cutoff, due date","The deadline for submissions is next week."],
["editorial","tahririy, bosh maqola","opinion piece, commentary, column","The editorial criticized the government's policy."],
["headline","sarlavha","title, heading, banner","The headline grabbed everyone's attention."],
["journalism","jurnalistika","reporting, news writing, media","Journalism plays a vital role in democracy."],
["mainstream","asosiy oqim, ommaviy","popular, conventional, dominant","The idea entered mainstream media."],
["medium","vosita, o'rtacha","channel, means, method","Television is a powerful medium."],
["newsletter","axborotnoma","bulletin, circular, update","The company sends a monthly newsletter."],
["objectivity","xolislik, ob'ektivlik","impartiality, fairness, neutrality","Objectivity is essential in journalism."],
["podcast","podkast","audio show, broadcast, webcast","She hosts a popular science podcast."],
["propaganda","targ'ibot, propaganda","publicity, misinformation, promotion","The regime used propaganda to control opinion."],
["sensation","sensatsiya, hayajon","excitement, thrill, spectacle","The news created a sensation."],
["slogan","shior, da'vat","motto, catchphrase, tagline","The campaign slogan was very effective."],
["subscription","obuna","membership, enrollment, registration","The magazine offers an annual subscription."],
["tabloid","tabloid, kichik gazeta","newspaper, press, gossip paper","Tabloid newspapers focus on celebrity news."],
["transparency","shaffoflik, ochiqlik","openness, clarity, honesty","Transparency in government builds public trust."],

// ===== ADDITIONAL ACADEMIC WORDS =====
["abbreviation","qisqartma","acronym, shortening, contraction","The abbreviation for United Nations is UN."],
["abstraction","abstraktsiya, mavhumlik","concept, idea, generalization","Mathematics involves high levels of abstraction."],
["acumen","zukkolik, tuyg'u","insight, sharpness, shrewdness","Her business acumen helped the company grow."],
["adept","mohir, usta","skilled, proficient, expert","She is adept at solving complex problems."],
["adorn","bezamoq, pardozlamoq","decorate, embellish, ornament","The hall was adorned with flowers."],
["adversary","dushman, raqib","opponent, enemy, rival","He faced a formidable adversary."],
["affinity","moyillik, yaqinlik","attraction, connection, fondness","She has an affinity for languages."],
["aggrandize","ulug'lamoq, kattalashmoq","enlarge, exaggerate, magnify","He tried to aggrandize his role in the project."],
["alacrity","tezlik, ishtiyoq","eagerness, willingness, speed","She accepted the offer with alacrity."],
["albeit","garchi, bo'lsa ham","although, even though, though","The plan, albeit risky, was approved."],
["allegiance","sodiqlik, bag'ishlash","loyalty, devotion, fidelity","Soldiers swear allegiance to the nation."],
["allusion","ishora, yashirin ma'no","reference, hint, suggestion","The poem contains an allusion to Greek mythology."],
["ameliorate","yaxshilamoq","improve, enhance, better","The new law aims to ameliorate working conditions."],
["amiable","iltifotli, yoqimli","friendly, kind, pleasant","She has an amiable personality."],
["amnesia","amneziya, xotirasizlik","memory loss, forgetfulness","The accident caused temporary amnesia."],
["ample","yetarli, keng","enough, abundant, plentiful","There was ample time to prepare."],
["anarchy","anarxiya, boshboshdoqlik","chaos, disorder, lawlessness","Without leadership, the group fell into anarchy."],
["anatomy","anatomiya, tuzilish","structure, body, framework","The anatomy of the human heart is complex."],
["ancestry","ajdodlar, kelib chiqish","lineage, heritage, descent","She traced her ancestry back to the 1700s."],
["anecdotal","rivoyatga asoslangan","informal, unverified, hearsay","The evidence is purely anecdotal."],
["animate","jonlantirmoq, tirik","enliven, energize, living","The teacher used stories to animate the lesson."],
["annihilate","yo'q qilmoq, butunlay qirmoq","destroy, eliminate, obliterate","The bomb annihilated the entire building."],
["anomalous","g'ayrioddiy, nostandart","abnormal, irregular, unusual","The anomalous data was investigated."],
["antecedent","oldingi, sabab","predecessor, precursor, forerunner","The antecedent events led to the war."],
["antiquity","qadimiylik, qadimgi davr","ancient times, old age","The ruins date back to antiquity."],
["apex","cho'qqi, eng yuqori nuqta","peak, summit, top","She reached the apex of her career."],
["appease","tinchitmoq, ko'nglini olmoq","calm, pacify, soothe","The government tried to appease the protesters."],
["appraisal","baholash, ko'rib chiqish","assessment, evaluation, review","The annual appraisal reviewed her performance."],
["apprehension","xavotir, tushunish","anxiety, fear, understanding","There was growing apprehension about the economy."],
["aptitude","iste'dod, qobiliyat","talent, ability, skill","She showed an aptitude for mathematics."],
["arbiter","hakam, boshqaruvchi","judge, referee, mediator","The arbiter settled the dispute fairly."],
["archaic","eskirgan, qadimiy","outdated, ancient, obsolete","The language used archaic words."],
["arduous","mashaqqatli, og'ir","difficult, strenuous, tough","The journey was long and arduous."],
["aristocrat","zodagon, aristokrat","noble, elite, patrician","The aristocrat owned vast estates."],
["ascend","ko'tarilmoq","rise, climb, go up","The climbers ascended the mountain."],
["ascribe","bog'lamoq, ... deb hisoblash","attribute, assign, credit","The painting is ascribed to Rembrandt."],
["assiduous","tirishqoq, g'ayratli","diligent, industrious, hardworking","She was an assiduous student."],
["astound","hayratga solmoq","amaze, astonish, shock","The results astounded the researchers."],
["atrophy","sustlashish, so'nilish","deterioration, wasting, decline","Muscles atrophy without regular exercise."],
["augment","ko'paytirmoq, oshirmoq","increase, boost, supplement","He augmented his salary with part-time work."],
["auspicious","omadli, qulay","favorable, promising, fortunate","It was an auspicious start to the project."],
["austere","qattiq, oddiy","strict, severe, plain","The monastery had an austere atmosphere."],
["avarice","ochko'zlik, tamahkorlik","greed, cupidity, covetousness","His avarice knew no bounds."],
["awe","hayrat, dahshat","wonder, amazement, reverence","The children stared in awe at the fireworks."],
["axiom","aksioma, haqiqat","principle, truth, maxim","It is an axiom that practice makes perfect."],

// ===== GENERAL IELTS HIGH-FREQUENCY (Additional) =====
["backdrop","fon, zamin","background, setting, context","The mountains provided a beautiful backdrop."],
["backlash","keskin norozilik","reaction, repercussion, retaliation","There was a backlash against the new policy."],
["bailout","moliyaviy yordam","rescue, aid, assistance","The government provided a bailout for the banks."],
["benchmark","mezon, standart","standard, reference, yardstick","The test serves as a benchmark for students."],
["bequest","vasiyat, meros","legacy, inheritance, gift","She left a bequest to the university."],
["betray","xiyonat qilmoq","deceive, double-cross, backstab","He betrayed his friend's trust."],
["bland","oddiy, ta'msiz","mild, plain, dull","The food was rather bland."],
["blatant","ochiqdan-ochiq, yuzaga","obvious, flagrant, glaring","It was a blatant violation of the rules."],
["bleak","xira, umidsiz","grim, desolate, dismal","The economic outlook is bleak."],
["blight","kasallik, vayronagarchilik","disease, plague, curse","Urban blight affects many inner-city areas."],
["bolster","qo'llab-quvvatlamoq, mustahkamlash","support, strengthen, reinforce","The evidence bolstered her argument."],
["boycott","boykot qilmoq","refuse, ban, shun","Citizens boycotted the company's products."],
["breach","buzish, yoriq","violation, break, gap","The breach of security was alarming."],
["brink","chekka, yoqa","edge, verge, threshold","The country was on the brink of war."],
["broaden","kengaytirmoq","widen, expand, extend","Travel broadens the mind."],
["candid","ochiq, rostgo'y","honest, frank, straightforward","She gave a candid interview."],
["capitalize","foydalamoq, bosh harf bilan yozmoq","exploit, profit, benefit","She capitalized on the opportunity."],
["catastrophic","halokatli, falоkatli","disastrous, devastating, ruinous","The earthquake was catastrophic."],
["cater","xizmat ko'rsatmoq, ta'minlamoq","provide, serve, supply","The restaurant caters for large groups."],
["chronic","surunkali, doimiy","persistent, long-term, ongoing","Chronic pollution affects the city."],
["circumvent","chetlab o'tmoq, aylanib o'tmoq","avoid, bypass, evade","They circumvented the regulations."],
["civic","fuqarolik, shahar","public, community, municipal","Civic duty includes voting."],
["clamor","shovqin, talab","uproar, outcry, demand","There was a clamor for reform."],
["coexist","birga yashash","live together, cohabit, exist together","Different cultures coexist in the city."],
["cohesion","birlik, bog'liqlik","unity, togetherness, solidarity","Social cohesion is important for stability."],
["coincidence","tasodif, mos kelish","chance, accident, fluke","It was a remarkable coincidence."],
["collaborate","hamkorlik qilmoq","cooperate, work together, partner","The scientists collaborated on the research."],
["collateral","garov, qo'shimcha","security, guarantee, pledge","The bank required collateral for the loan."],
["commemorate","xotirlash, yod etish","remember, honor, celebrate","The ceremony commemorated the war heroes."],
["commence","boshlamoq, boshlash","begin, start, initiate","The concert will commence at 8 PM."],
["commend","maqtamoq, tavsiya etmoq","praise, applaud, recommend","The teacher commended her excellent work."],
["compatible","mos, muvofiiq","harmonious, suitable, matching","The two systems are fully compatible."],
["compel","majburlash","force, oblige, coerce","The situation compelled him to act."],
["complement","to'ldirmoq, mos kelmoq","complete, supplement, enhance","The dessert complements the meal perfectly."],
["comply","rioya qilmoq, bo'ysunmoq","obey, follow, conform","All members must comply with the rules."],
["compound","birikmа, kuchaytirmoq","mixture, worsen, intensify","The problem was compounded by bad weather."],
["concealment","yashirish, maxfiylik","hiding, secrecy, cover-up","The concealment of evidence is a crime."],
["concession","imtiyoz, kelishuv","compromise, allowance, privilege","The government made concessions to the workers."],
["condone","ko'z yummoq, kechirilmoq","tolerate, forgive, overlook","The school does not condone bullying."],
["confound","chalkashtirib yubormoq","confuse, puzzle, bewilder","The results confounded the researchers."],
["congregate","to'planmoq, yig'ilmoq","gather, assemble, collect","People congregated in the town square."],
["conscience","vijdon","morality, ethics, inner voice","His conscience would not let him lie."],
["conscientious","vijdonli, mas'uliyatli","diligent, careful, thorough","She is a conscientious worker."],
["consolidate","mustahkamlamoq, birlashtirmoq","strengthen, unite, combine","The company consolidated its position in the market."],
["conspicuous","ko'zga tashlanadigan","noticeable, obvious, prominent","The error was conspicuous."],
["contemplate","o'ylamoq, fikrlamoq","consider, think about, ponder","She contemplated the meaning of life."],
["contention","bahs, da'vo","argument, dispute, claim","The main contention was about funding."],
["contingent","shartli, guruh","conditional, dependent, group","Success is contingent on hard work."],
["converge","birlashmoq, to'planmoq","meet, join, merge","The two roads converge at the bridge."],
["convict","mahkum qilmoq, mahkum","sentence, condemn, prisoner","He was convicted of theft."],
["cornerstone","burchak toshi, asos","foundation, basis, keystone","Education is the cornerstone of society."],
["covert","yashirin, maxfiy","secret, hidden, undercover","The covert operation was successful."],
["curtail","qisqartirmoq, cheklamoq","reduce, limit, restrict","The government curtailed spending."],
["cynical","kinoyali, shubhali","skeptical, pessimistic, distrustful","She was cynical about the promises."],
["daunting","qo'rqinchli, vahimali","intimidating, challenging, formidable","The task seemed daunting at first."],
["debris","qoldiq, parchalar","wreckage, rubble, remains","Cleanup crews removed the debris."],
["deceptive","aldamchi, yolg'on","misleading, fraudulent, dishonest","Appearances can be deceptive."],
["decimate","qirmoq, yo'q qilmoq","destroy, devastate, annihilate","The plague decimated the population."],
["decree","farmon chiqarmoq, buyruq","order, ruling, command","The king issued a royal decree."],
["deem","hisoblash, deb bilmoq","consider, regard, judge","The project was deemed a success."],
["deficit","kamomad, taqchillik","shortage, shortfall, deficiency","The country has a large trade deficit."],
["defy","qarshi chiqmoq, bo'ysunmaslik","resist, challenge, disobey","She defied the odds and succeeded."],
["delegate","vakil tayinlamoq, topshirmoq","assign, entrust, deputize","She delegated the work to her assistant."],
["deliberate","qasddan, ataylab","intentional, planned, purposeful","It was a deliberate attempt to mislead."],
["demographic","demografik, aholi bilan bog'liq","population, statistical, census","Demographic trends show an aging population."],
["demolish","buzmoq, vayron qilmoq","destroy, tear down, raze","The old building was demolished."],
["denote","anglatmoq, bildirmoq","indicate, signify, mean","The symbol denotes a warning."],
["deplete","tugallash, sarflab yubormoq","exhaust, drain, consume","Fish stocks have been depleted."],
["deploy","joylashtirmoq, ishga solmoq","use, utilize, position","The army deployed troops along the border."],
["designate","belgilash, tayinlash","appoint, assign, name","She was designated team leader."],
["destitute","qashshoq, nochor","impoverished, poor, deprived","The destitute family needed help."],
["detain","saqlash, ushlab turmoq","hold, arrest, confine","Police detained the suspect for questioning."],
["deter","to'xtatmoq, qaytarmoq","discourage, prevent, dissuade","Harsh penalties deter crime."],
["deviate","chetga chiqmoq, og'moq","diverge, stray, differ","The results deviated from expectations."],
["devise","o'ylab topmoq, ishlab chiqmoq","invent, create, plan","She devised a clever solution."],
["diagnose","tashxis qo'ymoq","identify, determine, detect","The doctor diagnosed the illness quickly."],
["diligence","tirishqoqlik, g'ayrat","effort, industriousness, care","His diligence paid off with good grades."],
["diplomatic","diplomatik, odob bilan","tactful, polite, discreet","A diplomatic response was needed."],
["discard","tashlab yubormoq","throw away, dispose, reject","Old equipment was discarded."],
["disclose","oshkor qilmoq, aytmoq","reveal, expose, divulge","The company disclosed its financial results."],
["discrepancy","nomuvofiqlik, farq","difference, inconsistency, gap","There was a discrepancy in the data."],
["discrete","alohida, ajralgan","separate, individual, distinct","The course is divided into discrete modules."],
["disparity","tengsizlik, farq","inequality, difference, gap","Income disparity is a global issue."],
["disperse","tarqatmoq, tarqalmoq","scatter, spread, distribute","The crowd dispersed after the event."],
["disrupt","buzmoq, to'xtatmoq","disturb, interrupt, upset","The strike disrupted public transport."],
["disseminate","tarqatmoq, yoymoq","spread, distribute, circulate","The report was disseminated widely."],
["divert","yo'naltirmoq, chalg'itmoq","redirect, distract, reroute","Traffic was diverted to another road."],
["doctrine","doktrina, ta'limot","belief, principle, teaching","The doctrine shaped foreign policy."],
["dormant","uxlayotgan, faoliyatsiz","inactive, sleeping, latent","The volcano has been dormant for centuries."],
["drastic","keskin, radikal","extreme, severe, harsh","Drastic action is needed to save the environment."],
["dubious","shubhali, ishonchsiz","doubtful, questionable, suspicious","The claim seems dubious."],
["durable","bardoshli, chidamli","lasting, tough, sturdy","The material is very durable."],
["dwarf","mitti, kichraytirmoq","small, miniature, overshadow","The skyscraper dwarfs the surrounding buildings."],
["dwindle","kamaymoq, so'nmoq","decrease, diminish, decline","The population dwindled over the decades."],
["eccentric","g'alati, g'ayrioddiy","odd, unusual, unconventional","The professor had eccentric habits."],
["eclipse","tutilish, soya solmoq","overshadow, outshine, surpass","The new discovery eclipsed previous findings."],
["ecology","ekologiya","environmental science, nature study","Ecology studies the relationships between organisms."],
["elaborate","batafsil bayon qilmoq","detailed, complex, expand","Could you elaborate on that point?"],
["elicit","chiqarmoq, undamoq","draw out, evoke, prompt","The question elicited a strong response."],
["elite","elita, eng yaxshilari","top, cream, best","Only the elite athletes qualify for the Olympics."],
["embark","kirishmoq, boshlamoq","begin, start, undertake","She embarked on a new career."],
["embody","mujassam bo'lmoq, o'z ichiga olmoq","represent, personify, include","The constitution embodies democratic principles."],
["empirical","tajribaviy, amaliy","experimental, observed, practical","The theory is supported by empirical evidence."],
["emulate","taqlid qilmoq, ga intilmoq","imitate, copy, follow","Young athletes emulate their heroes."],
["enact","qonun qabul qilmoq, ijro etmoq","pass, legislate, perform","The law was enacted last year."],
["encompass","qamrab olmoq, o'z ichiga olmoq","include, cover, embrace","The course encompasses many topics."],
["endorse","qo'llab-quvvatlamoq, ma'qullamoq","support, approve, back","The organization endorsed the candidate."],
["engender","keltirib chiqarmoq, sabab bo'lmoq","cause, create, produce","The policy engendered much debate."],
["enigma","jumboq, sir","mystery, puzzle, riddle","The disappearance remains an enigma."],
["enlighten","ong ochmoq, ma'rifat bermoq","inform, educate, illuminate","The documentary enlightened viewers on the issue."],
["enrich","boyitmoq","improve, enhance, fortify","Reading enriches the mind."],
["ensue","keyin sodir bo'lmoq","follow, result, occur","A heated debate ensued."],
["entail","talab qilmoq, o'z ichiga olmoq","involve, require, necessitate","The project entails a lot of research."],
["entity","sub'ekt, mavjudot","being, organization, body","Each entity has its own rules."],
["envision","tasavvur qilmoq, ko'z oldiga keltirmoq","imagine, foresee, visualize","She envisioned a better future."],
["erratic","beqaror, o'zgaruvchan","unpredictable, irregular, inconsistent","His behavior was erratic."],
["espionage","josuslik","spying, intelligence, surveillance","Espionage was common during the Cold War."],
["esteem","hurmat, e'tibor","respect, regard, admiration","She is held in high esteem by her colleagues."],
["etiquette","odobnamоlik, etiket","manners, protocol, courtesy","Business etiquette varies by culture."],
["exacerbate","og'irlashtirmoq, kuchaytirmoq","worsen, aggravate, intensify","The drought exacerbated the food crisis."],
["excerpt","parcha, ko'chirma","extract, passage, selection","An excerpt from the speech was published."],
["exemplify","misol bo'lmoq, ko'rsatmoq","illustrate, demonstrate, represent","This case exemplifies the problem."],
["exempt","ozod qilmoq, istisno","free, excuse, release","Students are exempt from the fee."],
["exert","kuch sarflamoq, ta'sir o'tkazmoq","apply, exercise, use","She exerted pressure on the committee."],
["exodus","ommaviy ko'chish, chiqib ketish","departure, migration, evacuation","The war caused an exodus of refugees."],
["expedite","tezlashtirmoq","accelerate, hasten, speed up","We need to expedite the approval process."],
["expel","haydab chiqarmoq, chiqarib yubormoq","eject, banish, dismiss","The student was expelled for cheating."],
["expertise","tajriba, mahorat","skill, knowledge, proficiency","His expertise in the field is well known."],
["explicit","aniq, ochiq","clear, direct, unambiguous","The rules are quite explicit."],
["exponential","keskin o'suvchi","rapid, dramatic, steep","The company experienced exponential growth."],
["extravagant","isrofgar, haddan tashqari","lavish, excessive, wasteful","The wedding was extravagant."],
["fabricate","yasamoq, to'qib chiqarmoq","make, invent, falsify","He fabricated the evidence."],
["fallacy","xato fikr, yolg'on","misconception, error, myth","The idea is based on a common fallacy."],
["famine","ocharchilik, qahatchilik","starvation, hunger, drought","The famine killed thousands."],
["feasibility","amalga oshirilish imkoniyati","viability, practicality, possibility","A feasibility study was conducted."],
["fervent","otashin, jo'shqin","passionate, intense, ardent","She is a fervent supporter of education."],
["fiscal","moliyaviy, fiskal","financial, monetary, budgetary","Fiscal policy affects economic growth."],
["flaw","nuqson, kamchilik","defect, fault, weakness","The plan has a fundamental flaw."],
["foment","qo'zg'atmoq, undamoq","incite, provoke, stir up","The speech fomented unrest."],
["forge","yasamoq, soxtalash","create, fake, fabricate","They forged a strong alliance."],
["forthright","ochiq, to'g'ri","direct, honest, candid","She gave a forthright answer."],
["foster","rivojlantirmoq, qo'llab-quvvatlamoq","encourage, promote, nurture","The program fosters creativity in children."],
["frugal","tejamkor, kamtar","thrifty, economical, careful","She lives a frugal lifestyle."],
["futile","befoyda, ma'nosiz","useless, pointless, vain","The rescue attempt proved futile."],
["garner","to'plamoq, yig'moq","collect, gather, accumulate","The project garnered widespread support."],
["genocide","genotsid, qirg'in","mass killing, extermination, massacre","Genocide is the worst crime against humanity."],
["gist","asosiy ma'no, mohiyat","essence, core, point","What is the gist of the argument?"],
["glaring","ko'zga tashlanadigan, yorqin","obvious, blatant, conspicuous","There was a glaring error in the report."],
["gloomy","xira, tushkun","dark, depressing, pessimistic","The economic forecast is gloomy."],
["governance","boshqaruv, idora qilish","management, administration, rule","Good governance ensures public welfare."],
["grasp","ushlamoq, tushunmoq","grip, understand, comprehend","She quickly grasped the concept."],
["groundbreaking","inqilobiy, yangilikka asos soladigan","innovative, pioneering, revolutionary","The research was groundbreaking."],
["grudge","adovat, g'azab","resentment, bitterness, animosity","He holds a grudge against his former boss."],
["hamper","to'sqinlik qilmoq","hinder, obstruct, impede","Bad weather hampered rescue efforts."],
["harness","jilovlamoq, foydalanmoq","utilize, exploit, control","We need to harness solar energy."],
["havoc","vayronagarchilik, tartibsizlik","chaos, destruction, devastation","The storm wreaked havoc on the coast."],
["hegemony","hegemoniya, ustunlik","dominance, supremacy, leadership","The country seeks hegemony in the region."],
["herald","e'lon qilmoq, xabardor qilmoq","announce, signal, proclaim","The discovery heralded a new era in medicine."],
["hierarchy","ierarxiya, daraja tizimi","ranking, order, pecking order","The corporate hierarchy is rigid."],
["hinder","to'sqinlik qilmoq","obstruct, impede, hamper","Lack of funds hindered the project."],
["holistic","yaxlit, umumiy","comprehensive, whole, integrated","A holistic approach considers all aspects."],
["homogeneous","bir xil, bir jinsli","uniform, identical, similar","The population is relatively homogeneous."],
["humanitarian","insonparvar","charitable, compassionate, altruistic","Humanitarian aid reached the victims."],
["hypothetical","faraziy, nazariy","theoretical, speculative, assumed","Let us consider a hypothetical situation."],
["imminent","yaqinlashayotgan, bo'lajak","impending, approaching, near","A storm is imminent."],
["impair","buzmoq, zaiflashtirmoq","damage, weaken, harm","Alcohol impairs your ability to drive."],
["imperative","zaruriy, majburiy","essential, vital, crucial","It is imperative that we act now."],
["implement","amalga oshirmoq, asbob","execute, apply, tool","The new policy was implemented immediately."],
["implicit","yashirin, anglab olinadigan","implied, understood, tacit","Trust was implicit in the agreement."],
["improvise","badihа qilmoq, tayyor bo'lmay qilmoq","ad-lib, extemporize, create","She had to improvise when her notes were lost."],
["inaugurate","ochmoq, boshlamoq","open, launch, initiate","The president inaugurated the new bridge."],
["incite","qo'zg'atmoq, undamoq","provoke, encourage, stir","The speech incited violence."],
["inclusive","qamrovli, hamma uchun","comprehensive, all-embracing","The policy aims to be more inclusive."],
["incoherent","bog'lanmagan, mantiqsiz","unclear, disjointed, rambling","His argument was incoherent."],
["incumbent","lavozim egasi, majburiy","current holder, obligatory","The incumbent president won reelection."],
["indifference","befarqlik, loqaydlik","apathy, unconcern, disinterest","Public indifference to the issue was alarming."],
["indignation","g'azab, norozilik","anger, outrage, resentment","The injustice caused widespread indignation."],
["induce","sabab bo'lmoq, undamoq","cause, trigger, prompt","Stress can induce insomnia."],
["inept","noqulay, noo'rin","incompetent, clumsy, unskilled","The handling of the crisis was inept."],
["infer","xulosa chiqarmoq, tushunmoq","deduce, conclude, gather","We can infer the result from the data."],
["inflate","shishirmoq, oshirmoq","expand, increase, exaggerate","The figures were inflated."],
["influx","oqib kelish, kirib kelish","inflow, stream, arrival","The influx of tourists boosted the economy."],
["ingenious","zukko, topqir","clever, inventive, creative","She found an ingenious solution."],
["inherent","tabiiy, xos","intrinsic, innate, built-in","Risk is inherent in all investments."],
["inhibit","to'xtatmoq, oldini olmoq","prevent, hinder, restrain","Shyness can inhibit communication."],
["injunction","buyruq, taqiq","order, command, directive","The court issued an injunction."],
["innate","tug'ma, tabiiy","inborn, natural, inherent","She has an innate talent for music."],
["innocuous","zararsiz, bexatar","harmless, safe, inoffensive","The substance is innocuous."],
["instigate","qo'zg'atmoq, boshlamoq","incite, provoke, initiate","She instigated the investigation."],
["integrate","birlashtirmoq, integratsiya","combine, merge, unify","The company integrated new technology."],
["interim","vaqtinchalik, oraliq","temporary, provisional, stopgap","An interim solution was implemented."],
["intermittent","vaqti-vaqti bilan, uzuq-uzuq","sporadic, irregular, occasional","Intermittent rain continued all day."],
["intricate","murakkab, chigal","complex, elaborate, detailed","The design is very intricate."],
["invoke","murojaat qilmoq, chaqirmoq","cite, call upon, appeal","She invoked her right to silence."],
["ironic","kinoyali, istehzoli","sarcastic, paradoxical, wry","It is ironic that the fire station burned down."],
["irreversible","qaytarib bo'lmaydigan","permanent, unalterable, final","Climate change may have irreversible effects."],
["itinerary","sayohat rejasi, marshrut","route, schedule, plan","The itinerary includes visits to five cities."],
["jargon","jargon, kasb so'zlari","terminology, slang, lingo","Medical jargon can be confusing."],
["juxtapose","yonma-yon qo'ymoq","compare, contrast, place side by side","The artist juxtaposed old and new styles."],
["kinship","qarindoshlik, yaqinlik","relationship, bond, affinity","There is a strong kinship between the two families."],
];

async function seed() {
    const SQL = await initSqlJs();
    let db;

    if (fs.existsSync(DB_PATH)) {
        const buffer = fs.readFileSync(DB_PATH);
        db = new SQL.Database(buffer);
    } else {
        db = new SQL.Database();
        db.run(`
            CREATE TABLE IF NOT EXISTS words (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                english TEXT NOT NULL,
                uzbek TEXT NOT NULL,
                synonyms TEXT DEFAULT '',
                example TEXT DEFAULT '',
                score INTEGER DEFAULT 0,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            )
        `);
    }

    const existing = new Set();
    const rows = db.exec('SELECT english FROM words');
    if (rows.length > 0) {
        rows[0].values.forEach(r => existing.add(r[0].toLowerCase()));
    }

    let added = 0;
    const stmt = db.prepare('INSERT INTO words (english, uzbek, synonyms, example) VALUES (?, ?, ?, ?)');

    for (const [eng, uzb, syn, ex] of words) {
        if (!existing.has(eng.toLowerCase())) {
            stmt.run([eng, uzb, syn || '', ex || '']);
            existing.add(eng.toLowerCase());
            added++;
        }
    }
    stmt.free();

    const data = db.export();
    fs.writeFileSync(DB_PATH, Buffer.from(data));

    const total = db.exec('SELECT COUNT(*) FROM words');
    console.log(`${added} ta yangi so'z qo'shildi. Jami: ${total[0].values[0][0]} ta so'z.`);
    db.close();
}

seed().catch(console.error);
