const path = require('path');
const initSqlJs = require('sql.js');
const fs = require('fs');
const DB_PATH = path.join(__dirname, 'words.db');

const words = [
["cabal","yashirin guruh, fitna","conspiracy, plot, faction","A cabal of rebels plotted against the king."],
["cache","yashirin joy, zaxira","store, reserve, stockpile","The hikers found a cache of supplies."],
["cadence","ohang, ritm","rhythm, tempo, beat","The cadence of her voice was soothing."],
["calamity","ofat, balo","disaster, catastrophe, tragedy","The earthquake was a terrible calamity."],
["calibrate","kalibrlash, aniq sozlash","adjust, standardize, fine-tune","Instruments must be calibrated regularly."],
["callous","berahm, shafqatsiz","heartless, cruel, insensitive","His callous remarks hurt everyone."],
["calumny","tuhmat, bo'hton","slander, defamation, libel","She was the victim of calumny."],
["camouflage","niqob, yashirish","disguise, concealment, cover","The soldiers wore camouflage."],
["canopy","soyabon, daraxt qoplami","cover, shade, awning","The forest canopy blocks sunlight."],
["capitulate","taslim bo'lmoq","surrender, yield, give in","The army capitulated after heavy losses."],
["caprice","injiqlik, o'zgaruvchanlik","whim, impulse, fancy","She acted on a caprice."],
["captive","asir, qo'lga tushgan","prisoner, hostage, detainee","The captives were eventually released."],
["cardinal","asosiy, muhim","fundamental, chief, principal","Trust is a cardinal virtue."],
["caricature","karikatura, bo'rttirma tasvir","cartoon, parody, satire","The caricature exaggerated his features."],
["carnage","qirg'in, qon to'kilish","slaughter, massacre, bloodshed","The battle resulted in terrible carnage."],
["cascade","sharshara, oqim","waterfall, flow, torrent","A cascade of water flowed down the rocks."],
["catalyst","turtki beruvchi, katalizator","trigger, stimulus, spark","The event was a catalyst for reform."],
["catastrophe","halokat, fojia","disaster, calamity, tragedy","The oil spill was an environmental catastrophe."],
["caveat","ogohlantirish, shart","warning, caution, condition","There is one caveat to the agreement."],
["celibacy","bo'ydoqlik","abstinence, chastity, singleness","He chose a life of celibacy."],
["censure","qoralamoq, tanbeh bermoq","criticize, condemn, rebuke","The politician was censured by colleagues."],
["cerebral","aqliy, miyaga oid","intellectual, mental, cognitive","She enjoys cerebral activities like chess."],
["certitude","ishonch, aniqlik","certainty, confidence, assurance","He spoke with great certitude."],
["charisma","xarizma, jozibadorlik","charm, appeal, magnetism","The leader has great charisma."],
["charlatan","sharlatan, firibgar","fraud, imposter, quack","The doctor turned out to be a charlatan."],
["chasm","jarlik, chuqur farq","gap, abyss, gulf","There is a chasm between rich and poor."],
["chastise","jazolamoq, tanbeh bermoq","punish, scold, discipline","The teacher chastised the misbehaving student."],
["chimera","xayoliy narsa, illyuziya","illusion, fantasy, dream","World peace seems like a chimera."],
["chronic","surunkali, uzoq muddatli","persistent, ongoing, long-term","Chronic diseases require lifelong management."],
["chronicle","yilnoma, voqealar qaydnomasi","record, history, account","The chronicle describes medieval life."],
["chronology","xronologiya, vaqt tartibi","timeline, sequence, order","The chronology of events was established."],
["circuitous","uzun, to'g'ri bo'lmagan","indirect, roundabout, winding","We took a circuitous route."],
["circumscribe","cheklamoq, chegaralamoq","limit, restrict, confine","His power was circumscribed by law."],
["circumspect","ehtiyotkor, hushyor","cautious, prudent, careful","She was circumspect in her dealings."],
["circumvent","chetlab o'tmoq, aylanib o'tmoq","bypass, avoid, evade","They tried to circumvent the rules."],
["clandestine","yashirin, sir","secret, covert, undercover","The clandestine meeting was discovered."],
["clairvoyant","bashoratchi, ko'ruvchi","psychic, prophet, fortune-teller","She claimed to be clairvoyant."],
["clemency","rahm-shafqat, avf","mercy, leniency, compassion","The prisoner appealed for clemency."],
["cliche","klishe, eskirgan ibora","stereotype, platitude, banality","Avoid cliches in your writing."],
["clientele","doimiy mijozlar","customers, patrons, clients","The shop has a loyal clientele."],
["clique","tor doira, guruhbozlik","group, circle, faction","The school had several cliques."],
["coalesce","birlashmoq, qo'shilmoq","merge, unite, combine","The parties coalesced into one movement."],
["codify","qonunlashtirmoq, tartibga solmoq","systematize, organize, classify","Laws were codified in the constitution."],
["coerce","majbur qilmoq, zo'rlamoq","force, compel, pressure","He was coerced into confessing."],
["cogent","ishonchli, mantiqiy","convincing, persuasive, compelling","She made a cogent argument."],
["cognitive","bilish bilan bog'liq, aqliy","mental, intellectual, cerebral","Cognitive skills develop in early childhood."],
["cohesion","birlik, bog'liqlik","unity, solidarity, togetherness","Social cohesion promotes stability."],
["coincidence","tasodif","chance, accident, fluke","Meeting here was a coincidence."],
["collateral","garov, qo'shimcha oqibat","security, guarantee, side effect","Collateral damage was extensive."],
["colloquial","og'zaki, norasmiy","informal, everyday, conversational","Avoid colloquial language in essays."],
["collusion","til biriktirib qilish","conspiracy, scheme, collaboration","The companies acted in collusion."],
["colossal","ulkan, bahaybat","enormous, huge, immense","The project required colossal investment."],
["combatant","jangchi, urushuvchi","fighter, soldier, warrior","The combatants agreed to a ceasefire."],
["commemorate","xotirlash, yodga olmoq","remember, honor, celebrate","The statue commemorates the war heroes."],
["commend","maqtamoq, tavsiya etmoq","praise, applaud, recommend","I commend you for your hard work."],
["commensurate","munosib, teng","proportional, equivalent, matching","The salary is commensurate with experience."],
["commissar","komissar, vakolatli shaxs","official, administrator, representative","The commissar oversaw the operation."],
["communion","birlik, muloqot","fellowship, unity, connection","There was a sense of communion among the group."],
["compact","ixcham, shartnoma","small, dense, agreement","The compact car is fuel-efficient."],
["compelling","ishontiruvchi, kuchli","persuasive, convincing, gripping","The evidence was compelling."],
["compendium","qisqacha to'plam","summary, collection, handbook","The compendium covers all major topics."],
["complacent","o'zidan mamnun, beparvo","self-satisfied, smug, unconcerned","Do not become complacent about safety."],
["compliant","bo'ysunuvchi, muvofiiq","obedient, cooperative, submissive","The company is fully compliant with regulations."],
["complicity","sheriklik, aybdorlik","involvement, collusion, guilt","His complicity in the crime was proven."],
["composure","o'zini tutish, xotirjamlik","calm, poise, self-control","She maintained her composure under pressure."],
["compulsion","majburiyat, intilish","obsession, urge, obligation","He felt a compulsion to check his email."],
["conceal","yashirmoq","hide, cover, disguise","She concealed her disappointment."],
["concede","tan olmoq, yon bermoq","admit, acknowledge, yield","He conceded defeat gracefully."],
["conceive","tasavvur qilmoq, loyiha tuzmoq","imagine, create, develop","She conceived the plan while abroad."],
["concession","imtiyoz, yon berish","compromise, privilege, grant","The government made important concessions."],
["concise","qisqa, lo'nda","brief, succinct, compact","Keep your answer concise."],
["conclusive","yakuniy, qat'iy","decisive, definitive, final","The evidence was conclusive."],
["concoct","aralashma tayyorlamoq, to'qib chiqarmoq","prepare, invent, fabricate","She concocted a story to explain her absence."],
["concurrent","bir vaqtdagi, parallel","simultaneous, parallel, coexisting","The two events were concurrent."],
["condescend","o'zini past tutmoq, bosh egmoq","patronize, deign, stoop","He condescended to help."],
["conducive","qulay, yordam beruvchi","favorable, helpful, beneficial","A quiet space is conducive to study."],
["confiscate","musodara qilmoq","seize, impound, appropriate","The police confiscated the weapons."],
["confluence","to'planish joyi, birlashish","junction, convergence, meeting","The confluence of the two rivers is scenic."],
["congenial","yoqimli, qulay","pleasant, friendly, agreeable","The staff was congenial and helpful."],
["conjecture","taxmin, faraz","guess, speculation, theory","The theory remains mere conjecture."],
["connive","ko'z yummoq, sheriklik qilmoq","collude, conspire, scheme","Officials connived at the corruption."],
["connoisseur","bilimdon, tanituvchi","expert, authority, specialist","She is a connoisseur of fine wine."],
["conscientious","vijdonli, sinchkov","careful, thorough, diligent","He is a conscientious worker."],
["consecrate","muqaddas qilmoq, bag'ishlamoq","bless, sanctify, dedicate","The church was consecrated in 1900."],
["consensus","umumiy kelishuv","agreement, accord, unanimity","A consensus was reached after debate."],
["consequential","muhim, oqibatli","important, significant, resultant","The decision was highly consequential."],
["conservatory","konservatoriya, issiqxona","music school, greenhouse, academy","She studied at the conservatory."],
["consolation","tasalli, yupatish","comfort, solace, sympathy","Her kind words were a consolation."],
["consolidate","mustahkamlash, birlashtirish","strengthen, combine, unite","The company consolidated its operations."],
["conspicuous","ko'zga tashlanadigan","noticeable, obvious, prominent","His absence was conspicuous."],
["constellation","yulduz turkumi","star group, cluster, array","Orion is a well-known constellation."],
["constitutional","konstitutsiyaviy","legal, fundamental, lawful","Freedom of speech is a constitutional right."],
["construe","tushunmoq, talqin qilmoq","interpret, understand, read","Her silence was construed as agreement."],
["consummate","mukammal, tugallash","perfect, complete, accomplish","He is a consummate professional."],
["contagion","yuqish, tarqalish","infection, spread, transmission","The contagion spread rapidly."],
["contemplate","mushohada qilmoq","consider, ponder, reflect","She contemplated the offer carefully."],
["contentious","bahsli, ziddiyatli","controversial, disputed, divisive","The topic remains contentious."],
["contiguous","tutash, chegaradosh","adjacent, neighboring, bordering","The two countries are contiguous."],
["contingency","kutilmagan holat","emergency, eventuality, possibility","We need a contingency plan."],
["contrite","pushaymon, afsusda","remorseful, sorry, apologetic","He was contrite about his behavior."],
["conundrum","jumboq, qiyin masala","puzzle, riddle, dilemma","The problem is a real conundrum."],
["convalescence","tiklanish, sog'ayish","recovery, healing, recuperation","Her convalescence took several weeks."],
["convivial","xushchaqchaq, mehmon do'st","sociable, friendly, jovial","The convivial atmosphere was enjoyable."],
["copious","mo'l, juda ko'p","abundant, plentiful, ample","She took copious notes during the lecture."],
["cordial","samimiy, iliq","warm, friendly, heartfelt","They received a cordial welcome."],
["corroborate","tasdiqlash, kuchaytirmoq","confirm, verify, support","Witnesses corroborated his story."],
["corrode","yemirmoq, zanglash","rust, deteriorate, erode","Acid corrodes metal surfaces."],
["cosmopolitan","kosmopolit, xalqaro","worldly, international, diverse","London is a cosmopolitan city."],
["countenance","yuz, qo'llab-quvvatlamoq","face, expression, support","She could not countenance such behavior."],
["counterfeit","soxta, qalbaki","fake, forged, bogus","Counterfeit money was discovered."],
["coup","to'ntarish, muvaffaqiyat","overthrow, takeover, stroke","The military coup overthrew the government."],
["covenant","ahd, shartnoma","agreement, pact, contract","The covenant bound both parties."],
["covert","yashirin, sir","secret, hidden, clandestine","A covert operation was launched."],
["covet","hasad qilmoq, istamoq","desire, envy, crave","He coveted his neighbor's success."],
["craven","qo'rqoq, yuraksis","cowardly, timid, fearful","The craven retreat shocked everyone."],
["credence","ishonch","belief, trust, faith","Do not give credence to rumors."],
["crescendo","kuchayish, cho'qqi","peak, climax, height","The music reached a crescendo."],
["criterion","mezon, standart","standard, benchmark, measure","Academic merit is the main criterion."],
["cryptic","sirli, tushunarsiz","mysterious, obscure, enigmatic","She left a cryptic message."],
["culminate","cho'qqiga chiqmoq, yakunlanmoq","climax, conclude, peak","The festival culminated in a grand finale."],
["culpable","aybdor, gunohkor","guilty, blameworthy, responsible","He was found culpable for the accident."],
["cultivate","o'stirmoq, rivojlantirmoq","grow, develop, foster","She cultivated strong relationships."],
["cumbersome","noqulay, katta","awkward, bulky, unwieldy","The cumbersome equipment was hard to move."],
["curator","kurator, boshqaruvchi","keeper, custodian, director","The museum curator organized the exhibit."],
["cursory","yuzaki, shoshilinch","superficial, hasty, brief","A cursory glance revealed nothing unusual."],
["curtail","qisqartirmoq","reduce, cut, limit","Spending was curtailed to save money."],
["cynicism","kinoyachilik, pessimizm","skepticism, doubt, distrust","Political cynicism is widespread."],
["dearth","tanqislik, kamchilik","shortage, scarcity, lack","There is a dearth of affordable housing."],
["debacle","fojia, mag'lubiyat","disaster, fiasco, failure","The election was a debacle for the party."],
["debilitate","kuchsizlantirmoq","weaken, enfeeble, exhaust","The illness debilitated him for months."],
["debunk","fosh qilmoq, rad etmoq","expose, disprove, discredit","Scientists debunked the myth."],
["decadent","tanazzulga yuz tutgan","declining, corrupt, indulgent","The decadent lifestyle was unsustainable."],
["decimate","qirmoq, yo'q qilmoq","destroy, devastate, ravage","The disease decimated the population."],
["decorum","odob, xulq","propriety, etiquette, dignity","Maintain decorum in the courtroom."],
["decree","farmon, qaror","order, edict, ruling","The court issued a decree."],
["dedicate","bag'ishlamoq, ajratmoq","devote, commit, consecrate","She dedicated her life to teaching."],
["defamatory","tuhmatchi, obro'sizlantiruvchi","slanderous, libelous, malicious","The defamatory article was retracted."],
["default","qoidaga muvofiq, bajarmaslik","standard, failure, preset","He defaulted on his loan."],
["defer","kechiktirmoq, hurmat ko'rsatmoq","postpone, respect, yield","She deferred to her professor's opinion."],
["defiant","itoatsiz, qarshilik ko'rsatuvchi","rebellious, bold, resistant","The defiant crowd refused to disperse."],
["deft","mohir, chaqqon","skillful, adroit, nimble","She made a deft move to avoid the obstacle."],
["defunct","faoliyati to'xtatilgan","inactive, dead, obsolete","The company has been defunct since 2010."],
["degenerate","yomonlashmoq, buzilmoq","deteriorate, decline, worsen","Standards degenerated over the years."],
["delegate","vakil tayinlamoq","assign, entrust, authorize","She delegated tasks effectively."],
["deleterious","zararli","harmful, damaging, detrimental","Pollution has deleterious effects on health."],
["deliberate","qasddan, o'ylab","intentional, planned, considered","It was a deliberate provocation."],
["delineate","chizmoq, ta'riflamoq","outline, describe, define","The report delineates the key issues."],
["delude","aldamoq, ko'z bo'yamoq","deceive, mislead, trick","Do not delude yourself about the risks."],
["deluge","to'fon, sel","flood, downpour, torrent","The town was hit by a deluge."],
["demarcation","chegaralash, ajratish","boundary, division, separation","The demarcation line was clearly drawn."],
["demeanor","xulq-atvor, qiyofa","behavior, manner, bearing","Her professional demeanor impressed the clients."],
["demise","vafot, tugash","death, end, passing","The demise of the empire was gradual."],
["demographic","demografik, aholi statistikasi","population, statistical","Demographic changes affect policy."],
["demolish","buzmoq, yo'q qilmoq","destroy, raze, tear down","The old stadium was demolished."],
["demonize","yovuz qilib ko'rsatmoq","vilify, condemn, malign","The media demonized the opposition."],
["demote","lavozimdan tushirmoq","downgrade, lower, reduce","He was demoted for poor performance."],
["demure","uyatchan, kamtar","modest, shy, reserved","She gave a demure smile."],
["denizen","yashovchi, fuqaro","inhabitant, resident, citizen","Denizens of the forest include deer and foxes."],
["denounce","qoralamoq, ayblash","condemn, criticize, accuse","The opposition denounced the policy."],
["depict","tasvirlamoq","portray, illustrate, represent","The mural depicts local history."],
["deplete","tugallash, sarflab yubormoq","exhaust, drain, use up","Resources have been seriously depleted."],
["deplorable","achinarli, qo'rqinchli","terrible, dreadful, shameful","Living conditions were deplorable."],
["deploy","joylashtirmoq, qo'llamoq","use, station, position","New technology was deployed."],
["depose","taxtdan ag'darmoq","overthrow, remove, oust","The dictator was deposed."],
["deprecate","qoralash, yoqtirmaslik","disapprove, criticize, oppose","She deprecated the use of force."],
["depreciate","qadri tushmoq, arzonlashmoq","devalue, decrease, decline","The currency depreciated sharply."],
["deprive","mahrum qilmoq","deny, strip, rob","Children should not be deprived of play."],
["deputy","o'rinbosar, deputat","assistant, substitute, representative","The deputy managed in his absence."],
["derelict","tashlandiq, beparvo","abandoned, neglected, dilapidated","The derelict building was unsafe."],
["deride","masxara qilmoq","mock, ridicule, scoff","Critics derided the proposal."],
["derive","kelib chiqmoq, olmoq","obtain, stem, originate","Pleasure can be derived from simple things."],
["derogatory","haqoratli, kamsituvchi","insulting, offensive, disrespectful","Derogatory comments are unacceptable."],
["descend","tushmoq, pastga tushmoq","go down, drop, fall","The plane began to descend."],
["designate","belgilash, tayinlash","name, appoint, assign","The area was designated a nature reserve."],
["desolate","huvillab qolgan, xarob","barren, deserted, bleak","The desolate landscape stretched for miles."],
["despair","umidsizlik","hopelessness, dejection, misery","She was overcome with despair."],
["despot","mustabid, zolim","tyrant, dictator, autocrat","The despot ruled with an iron fist."],
["destitute","qashshoq, muhtoj","impoverished, needy, poor","The destitute family needed assistance."],
["detach","ajratmoq, uzmoq","separate, disconnect, remove","Detach the form and return it."],
["deter","qaytarmoq, oldini olmoq","discourage, prevent, dissuade","Cameras deter criminal activity."],
["detour","aylanma yo'l","diversion, roundabout, bypass","We took a detour around the construction."],
["detract","pasaytirmoq, yomonlashtirmoq","diminish, reduce, lessen","The error does not detract from his work."],
["detrimental","zararli, salbiy","harmful, damaging, injurious","Stress is detrimental to health."],
["devastate","vayron qilmoq","destroy, ruin, wreck","The hurricane devastated the coastline."],
["deviant","normadan chetga chiqqan","abnormal, irregular, atypical","Deviant behavior was studied by researchers."],
["devise","o'ylab topmoq, ixtiro qilmoq","invent, create, design","She devised a clever strategy."],
["devoid","bo'sh, yo'q","empty, lacking, without","The room was devoid of furniture."],
["devout","taqvodor, diniy","pious, religious, faithful","She is a devout Muslim."],
["dexterous","epchil, mohir","skillful, adept, nimble","The surgeon's dexterous hands saved lives."],
["diabolical","shaytonga xos, dahshatli","evil, wicked, fiendish","The plan was diabolical."],
["diagnosis","tashxis, aniqlash","detection, identification","Early diagnosis saves lives."],
["dichotomy","ikki qismga bo'linish","division, split, contrast","There is a dichotomy between theory and practice."],
["didactic","o'rgatuvchi, ta'limiy","educational, instructive, teaching","The book has a didactic purpose."],
["diffuse","tarqatmoq, tarqoq","spread, disperse, scattered","The light was diffused through the curtains."],
["digress","chetga chiqmoq, mavzudan olmoq","deviate, stray, wander","The speaker digressed from the main topic."],
["dilapidated","vayron, eskirgan","rundown, decrepit, ruined","The dilapidated building needs repair."],
["dilemma","ikkilanish, qiyin tanlov","predicament, quandary, problem","She faced a moral dilemma."],
["diligent","tirishqoq, g'ayratli","hardworking, industrious, careful","Diligent students earn the best grades."],
["diminish","kamaymoq","decrease, reduce, lessen","The pain gradually diminished."],
["din","shovqin, g'ala-g'ovur","noise, racket, clamor","The din of traffic was constant."],
["dire","dahshatli, shoshilinch","desperate, urgent, severe","The situation is dire."],
["disability","nogironlik, imkoniyati cheklangan","handicap, impairment, condition","People with disabilities deserve equal rights."],
["discard","tashlab yubormoq","throw away, reject, dispose","Discard old batteries safely."],
["discern","ajratmoq, tushunmoq","perceive, detect, recognize","She could discern the truth easily."],
["disciple","shogird, izdosh","follower, student, adherent","He was a disciple of the great philosopher."],
["disclose","oshkor qilmoq","reveal, expose, divulge","She disclosed the information to police."],
["discomfort","noqulaylik, bezovtalik","unease, pain, irritation","The patient experienced some discomfort."],
["disconcert","dovdiratmoq, gangitmoq","unsettle, disturb, confuse","The sudden question disconcerted him."],
["discord","norozilik, kelishmovchilik","conflict, disagreement, strife","Discord within the team affected performance."],
["discourse","nutq, munozara","discussion, speech, conversation","Academic discourse requires precision."],
["discretion","ehtiyot, mulohaza","caution, judgment, tact","Use your discretion when handling this."],
["discrimination","kamsitish, farqlash","prejudice, bias, distinction","Discrimination is prohibited by law."],
];

async function seed() {
    const SQL = await initSqlJs();
    let db;
    if (fs.existsSync(DB_PATH)) {
        const buffer = fs.readFileSync(DB_PATH);
        db = new SQL.Database(buffer);
    } else {
        db = new SQL.Database();
        db.run(`CREATE TABLE IF NOT EXISTS words (id INTEGER PRIMARY KEY AUTOINCREMENT, english TEXT NOT NULL, uzbek TEXT NOT NULL, synonyms TEXT DEFAULT '', example TEXT DEFAULT '', score INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
    }
    const existing = new Set();
    const rows = db.exec('SELECT english FROM words');
    if (rows.length > 0) rows[0].values.forEach(r => existing.add(r[0].toLowerCase()));
    let added = 0;
    const stmt = db.prepare('INSERT INTO words (english, uzbek, synonyms, example) VALUES (?, ?, ?, ?)');
    for (const [eng, uzb, syn, ex] of words) {
        if (!existing.has(eng.toLowerCase())) {
            stmt.run([eng, uzb, syn || '', ex || '']);
            existing.add(eng.toLowerCase());
            added++;
        }
    }
    stmt.free();
    const data = db.export();
    fs.writeFileSync(DB_PATH, Buffer.from(data));
    const total = db.exec('SELECT COUNT(*) FROM words');
    console.log(`${added} ta yangi so'z qo'shildi. Jami: ${total[0].values[0][0]} ta so'z.`);
    db.close();
}
seed().catch(console.error);
