const path = require('path');
const initSqlJs = require('sql.js');
const fs = require('fs');

const DB_PATH = path.join(__dirname, 'words.db');

const words = [
// ===== TRAVEL & TRANSPORT =====
["commute","ish joyiga borish-kelish","travel, journey, ride","She commutes to work by train."],
["congestion","tiqilinch, tirbandlik","jam, overcrowding, blockage","Rush hour causes severe congestion."],
["cruise","dengiz sayohati","voyage, sail, trip","They went on a Mediterranean cruise."],
["destination","manzil, boradigan joy","target, goal, endpoint","Paris is a popular tourist destination."],
["detour","aylanma yo'l","diversion, bypass, roundabout","We took a detour to avoid traffic."],
["embarkation","kemaga chiqish","boarding, departure, loading","Embarkation begins at noon."],
["excursion","sayohat, ekskursiya","trip, outing, tour","The students went on an excursion to the museum."],
["expedition","ekspeditsiya, ilmiy sayohat","journey, voyage, exploration","The Arctic expedition lasted three months."],
["freight","yuk, yuk tashish","cargo, shipment, goods","Freight costs have increased."],
["itinerary","sayohat rejasi","schedule, route, plan","The itinerary includes five countries."],
["locomotive","lokomotiv, teplovoz","engine, train, rail vehicle","The locomotive pulled twenty carriages."],
["navigate","yo'l topmoq, boshqarmoq","steer, guide, direct","She navigated through the city easily."],
["pedestrian","piyoda, oddiy","walker, person on foot","Pedestrian safety is a priority."],
["pilgrim","ziyoratchi, hojji","traveler, devotee, worshiper","Pilgrims visit the holy city every year."],
["souvenir","esdalik, yodgorlik","memento, keepsake, token","She bought souvenirs for her family."],
["terminal","terminal, oxirgi","station, depot, final","The flight departs from Terminal 3."],
["transit","tranzit, o'tish joyi","transport, passage, travel","Passengers waited in the transit lounge."],
["turbulence","to'lqinlanish, beqarorlik","instability, disturbance, commotion","The plane experienced severe turbulence."],
["vessel","kema, idish","ship, boat, container","The vessel sailed across the Atlantic."],
["voyage","uzoq sayohat","journey, trip, expedition","The voyage took three weeks."],

// ===== FOOD & AGRICULTURE =====
["agriculture","qishloq xo'jaligi","farming, cultivation, husbandry","Agriculture is the backbone of the economy."],
["beverage","ichimlik","drink, refreshment, liquid","Coffee is the most popular beverage."],
["calorie","kaloriya","energy unit, food energy","A balanced diet includes the right number of calories."],
["cereal","don ekin, boshli don","grain, crop, wheat","Rice is the main cereal crop in Asia."],
["cholesterol","xolesterin","fat, lipid","High cholesterol increases heart disease risk."],
["commodity","oziq-ovqat mahsuloti, tovar","product, goods, staple","Wheat is an important commodity."],
["consume","iste'mol qilmoq","eat, drink, use","We consume too much processed food."],
["contaminate","ifloslash, zaharlamoq","pollute, taint, infect","Pesticides contaminate the water supply."],
["cuisine","oshxona, taom tayyorlash uslubi","cooking, food, gastronomy","Italian cuisine is loved worldwide."],
["cultivate","etishtirmoq, yetishtirmoq","grow, farm, produce","Farmers cultivate rice in the valley."],
["delicacy","mazali taom, noziklik","treat, specialty, luxury food","Caviar is considered a delicacy."],
["dietary","ovqatlanish bilan bog'liq","nutritional, food-related","Dietary habits affect health."],
["drought","qurg'oqchilik","dry spell, arid period","The drought destroyed crops."],
["famine","ocharchilik, qahatchilik","starvation, hunger, food shortage","Famine affected millions in the region."],
["ferment","bijg'imoq, achitmoq","brew, culture, leaven","Yeast is used to ferment bread dough."],
["fertilizer","o'g'it","manure, nutrient, compost","Chemical fertilizers boost crop yields."],
["flock","poda, to'da","herd, group, crowd","A flock of sheep grazed on the hillside."],
["forage","ozuqa qidirmoq, yem","search for food, graze, browse","Animals forage for food in the wild."],
["genetically modified","genetik o'zgartirilgan","GM, bioengineered, transgenic","Genetically modified crops are controversial."],
["grain","don, g'alla","cereal, wheat, seed","Grain production has increased."],
["harvest","hosil, hosil yig'ish","crop, yield, reap","The wheat harvest begins in July."],
["horticulture","bog'dorchilik","gardening, plant cultivation","Horticulture is a growing industry."],
["irrigation","sug'orish","watering, water supply, sprinkling","Irrigation systems improved crop yields."],
["livestock","chorva mol","cattle, animals, farm animals","Livestock farming is a major industry."],
["malnourished","yetarli ovqatlanmagan","underfed, starving, undernourished","Millions of children are malnourished."],
["organic","organik, tabiiy","natural, chemical-free, biological","Organic food is increasingly popular."],
["pesticide","pestitsid, zaharli kimyoviy modda","insecticide, herbicide, chemical","Pesticide use affects the environment."],
["plantation","plantatsiya, ko'chatchilik","farm, estate, grove","The tea plantation covers 200 hectares."],
["poultry","parrandachilik, parranda go'shti","chicken, fowl, birds","Poultry is a popular source of protein."],
["preservative","konservant","additive, chemical, agent","The food contains no artificial preservatives."],
["staple","asosiy ozuqa, muhim","basic food, essential, main","Rice is a staple food in Asia."],
["subsistence","tirikchilik, minimal yashash","survival, livelihood, existence","Subsistence farming supports many families."],
["supplement","qo'shimcha ozuqa","addition, extra, vitamin","She takes vitamin supplements daily."],
["sustainable","barqaror, ekologik","eco-friendly, renewable, green","Sustainable farming protects the environment."],
["vegetation","o'simlik qoplami","plants, flora, greenery","The vegetation was lush and green."],
["yield","hosil, natija bermoq","produce, output, harvest","The farm yields tons of wheat annually."],

// ===== ARCHITECTURE & HOUSING =====
["accommodate","joy bermoq, sig'dirmoq","house, shelter, hold","The building accommodates 500 people."],
["apartment","kvartira, xonadon","flat, unit, dwelling","She rented an apartment in the city center."],
["architecture","me'morchilik","design, building style, construction","Modern architecture uses glass and steel."],
["basement","podval, yerto'la","cellar, underground floor","The basement was converted into a gym."],
["blueprint","loyiha, reja","plan, design, layout","The architect presented the blueprint."],
["demolition","buzish, vayron qilish","destruction, tearing down, razing","The demolition of the old building began."],
["dwelling","turar joy, uy","home, residence, house","Ancient dwellings were discovered."],
["elevation","balandlik, ko'tarish","height, altitude, rise","The building's elevation is 200 meters."],
["facade","fasad, tashqi ko'rinish","front, exterior, face","The facade of the building was renovated."],
["foundation","poydevor, asos","base, groundwork, footing","The foundation was laid last month."],
["infrastructure","infratuzilma","facilities, framework, systems","Urban infrastructure needs investment."],
["insulation","izolyatsiya, issiqlik saqlash","protection, padding, covering","Good insulation reduces energy costs."],
["landlord","uy egasi","owner, proprietor, lessor","The landlord increased the rent."],
["lease","ijara, ijara shartnomasi","rental agreement, contract, let","She signed a two-year lease."],
["loft","chortoq, yuqori qavat","attic, upper floor, garret","They converted the loft into a bedroom."],
["mortgage","ipoteka, garov","home loan, financing, credit","She pays a monthly mortgage."],
["penthouse","eng yuqori qavatdagi uy","luxury apartment, top floor flat","The penthouse has a rooftop terrace."],
["plumbing","santexnika, quvur tizimi","pipes, water system, drainage","The plumbing needs to be repaired."],
["premises","bino, joy","building, property, site","Smoking is not allowed on the premises."],
["refurbish","ta'mirlamoq, yangilamoq","renovate, restore, repair","The hotel was completely refurbished."],
["renovation","ta'mir, yangilash","restoration, refurbishment, makeover","The renovation cost $2 million."],
["residential","turar joy","housing, domestic, living","It is a quiet residential area."],
["scaffold","iskala, yosin","framework, platform, staging","Scaffolding surrounded the building."],
["skyscraper","osmono'par bino","high-rise, tower, tall building","The city has many modern skyscrapers."],
["sprawl","tarqalish, kengayish","spread, expand, stretch","Urban sprawl is consuming farmland."],
["structure","inshoot, tuzilma","building, construction, framework","The structure was built in the 1800s."],
["suburban","shahar atrofi","outskirts, residential area","They live in a suburban neighborhood."],
["tenant","ijarachilik, kirayachi","renter, occupant, lessee","The tenant pays rent monthly."],
["terrace","teras, ayvon","patio, balcony, deck","They had dinner on the terrace."],
["ventilation","shamollatish, havo almashinuvi","air flow, airing, circulation","Good ventilation is essential indoors."],

// ===== WORK & CAREER =====
["appraisal","baholash, ko'rib chiqish","evaluation, review, assessment","Annual appraisals motivate employees."],
["apprenticeship","shogirdlik, stajirovka","training, internship, placement","He completed a three-year apprenticeship."],
["autonomy","mustaqillik, erkinlik","independence, freedom, self-governance","Workers value autonomy in their roles."],
["bonus","mukofot, qo'shimcha","reward, incentive, premium","Employees received a year-end bonus."],
["bureaucracy","byurokratiya, idorabozlik","red tape, officialdom, administration","Bureaucracy slows down processes."],
["colleague","hamkasb, sherik","coworker, associate, peer","She discussed the project with her colleagues."],
["competence","malaka, bilim","skill, ability, proficiency","The job requires technical competence."],
["contractual","shartnomaviy","agreed, binding, legal","Contractual obligations must be fulfilled."],
["delegation","delegatsiya, topshirish","deputation, assignment, group","The delegation visited the factory."],
["dismissal","ishdan bo'shatish","firing, termination, sacking","Unfair dismissal is illegal."],
["downsizing","qisqartirish","reduction, cutback, layoff","The company announced downsizing."],
["entrepreneur","tadbirkor, biznesmen","businessman, founder, innovator","Entrepreneurs drive economic growth."],
["freelance","erkin ishchi, frilanser","independent, self-employed, contractor","She works as a freelance designer."],
["hierarchy","ierarxiya, bosqichlar","ranking, structure, pecking order","The company has a flat hierarchy."],
["human resources","inson resurslari","HR, personnel, staffing","Human resources handles recruitment."],
["increment","oshish, qo'shimcha","increase, raise, addition","Employees receive annual increments."],
["internship","stajirovka, amaliyot","placement, training, work experience","The internship lasted three months."],
["layoff","ishdan bo'shatish","redundancy, dismissal, cutback","Mass layoffs affected the industry."],
["mentor","ustoz, yo'l ko'rsatuvchi","guide, advisor, coach","Every new employee is assigned a mentor."],
["morale","ruhiy holat, kayfiyat","spirit, confidence, motivation","High morale improves productivity."],
["negotiate","muzokara qilmoq, gaplashmoq","bargain, discuss, deal","They negotiated a better salary."],
["outsource","tashqi ijrochiga topshirmoq","delegate, contract out, subcontract","The company outsourced IT services."],
["overtime","ortiqcha ish vaqti","extra hours, additional work","She worked overtime to finish the project."],
["payroll","ish haqi ro'yxati","salary list, wages, compensation","The company has 500 people on its payroll."],
["pension","pensiya, nafaqa","retirement fund, annuity, allowance","She receives a monthly pension."],
["probation","sinov muddati","trial period, testing, evaluation","New employees serve a six-month probation."],
["productivity","unumdorlik, samaradorlik","efficiency, output, performance","Technology increases productivity."],
["promotion","lavozim oshirish, targ'ibot","advancement, elevation, marketing","She received a well-deserved promotion."],
["qualification","malaka, sertifikat","credential, degree, certification","The job requires a master's qualification."],
["recruit","yollash, jalb qilmoq","hire, employ, enlist","The company recruited 50 new staff."],
["redundancy","ortiqchalik, ishdan bo'shatish","layoff, surplus, dismissal","The merger led to many redundancies."],
["remuneration","ish haqi, mukofot","payment, salary, compensation","The remuneration package is competitive."],
["resignation","iste'fo, iste'foga chiqish","quitting, departure, leaving","She submitted her resignation."],
["resume","rezyume, davom ettirmoq","CV, curriculum vitae, continue","Send your resume to the HR department."],
["sabbatical","ta'til, uzun dam olish","leave, break, time off","She took a sabbatical to write a book."],
["seminar","seminar, o'quv yig'ilishi","workshop, conference, class","The career seminar was very helpful."],
["stipend","stipendiya, nafaqa","allowance, grant, payment","The research stipend covers living expenses."],
["subordinate","bo'ysunuvchi, quyi xodim","junior, inferior, lower-ranking","She manages a team of subordinates."],
["supervise","nazorat qilmoq, boshqarmoq","oversee, manage, monitor","She supervises ten employees."],
["tenure","muddat, doimiy ish","term, period, permanent position","She was granted tenure at the university."],
["vacancy","bo'sh o'rin, ish joyi","opening, position, opportunity","There are three vacancies in the department."],
["vocational","kasbiy, hunarga oid","professional, occupational, technical","Vocational training prepares students for work."],
["workload","ish yuki, hajmi","tasks, duties, assignments","Her workload increased after the promotion."],

// ===== CRIME & JUSTICE =====
["acquittal","oqlash, ozod qilish","exoneration, clearance, discharge","The jury's acquittal surprised everyone."],
["arson","qasddan o't qo'yish","fire-setting, incendiarism","He was convicted of arson."],
["assault","hujum, zo'ravonlik","attack, battery, violence","The assault was caught on CCTV."],
["bail","kafolat, garov puli","bond, surety, guarantee","He was released on bail."],
["bribery","poraxo'rlik, rishvat","corruption, graft, payoff","Bribery is a serious criminal offense."],
["burglary","o'g'rilik (uyga kirib)","theft, robbery, break-in","There was a burglary in the neighborhood."],
["custody","hibsga olish, nazorat","detention, care, guardianship","The suspect is in police custody."],
["embezzlement","o'g'irlik (pul o'zlashmoq)","theft, fraud, misappropriation","He was charged with embezzlement of funds."],
["espionage","josuslik, razvedka","spying, intelligence, surveillance","He was arrested for espionage."],
["extortion","tovlamachilik","blackmail, coercion, shakedown","The businessman was a victim of extortion."],
["felony","og'ir jinoyat","crime, offense, serious crime","Murder is classified as a felony."],
["forensic","sud ekspertizasi, kriminalistik","investigative, crime-related, legal","Forensic evidence helped solve the case."],
["fraud","firibgarlik, qalbakichelik","deception, scam, swindle","Online fraud is increasing."],
["fugitive","qo'lga tushmaganlar, qochoq","runaway, escapee, outlaw","The fugitive was captured after three months."],
["homicide","odam o'ldirish","murder, killing, manslaughter","The homicide rate has decreased."],
["incarcerate","qamoq qilmoq","imprison, jail, confine","He was incarcerated for ten years."],
["inmate","mahkum, mahbus","prisoner, convict, detainee","The prison has 500 inmates."],
["juvenile","voyaga yetmagan, o'smir","young, minor, adolescent","Juvenile crime is a growing concern."],
["kidnapping","odam o'g'irlash","abduction, seizure, hostage-taking","The kidnapping shocked the community."],
["larceny","o'g'irlik, o'marilish","theft, stealing, robbery","He was charged with grand larceny."],
["offender","jinoyatchi, huquqbuzar","criminal, lawbreaker, culprit","Repeat offenders face harsher sentences."],
["pardon","kechirim, avf","forgiveness, amnesty, clemency","The president granted a pardon."],
["perpetrator","jinoyatchi, ish qiluvchi","criminal, offender, culprit","The perpetrator was identified by witnesses."],
["probation","shartli jazo","parole, supervision, trial","He was sentenced to two years probation."],
["prosecution","ayblov, sudga berish","legal action, indictment, trial","The prosecution rested its case."],
["recidivism","qayta jinoyat qilish","reoffending, relapse, repeat crime","Programs aim to reduce recidivism."],
["rehabilitation","qayta tarbiyalash, tiklash","recovery, reform, restoration","Rehabilitation programs help inmates reintegrate."],
["restitution","tovon, qaytarish","compensation, repayment, amends","The court ordered restitution to the victims."],
["sentence","hukm, jazo","verdict, punishment, ruling","He received a ten-year sentence."],
["surveillance","kuzatuv, nazorat","monitoring, watch, observation","The area is under constant surveillance."],
["testimony","guvohlik, ko'rsatma","evidence, statement, deposition","The witness gave compelling testimony."],
["theft","o'g'irlik","stealing, robbery, larceny","Car theft is common in the area."],
["vandalism","vandalizm, buzg'unchilik","damage, destruction, defacement","Vandalism costs the city millions annually."],
["verdict","hukm, qaror","judgment, ruling, decision","The verdict was guilty."],
["warrant","order, buyruq","authorization, court order, permit","Police obtained a search warrant."],
["witness","guvoh, shohid","observer, spectator, bystander","The witness identified the suspect."],

// ===== EMOTIONS & PERSONALITY =====
["affectionate","mehribon, samimiy","loving, warm, caring","She is very affectionate with children."],
["aggressive","tajovuzkor, hujumkor","hostile, forceful, combative","His aggressive behavior worried everyone."],
["ambitious","shuhratparast, intiluvchi","driven, determined, aspiring","She is an ambitious young professional."],
["anxious","tashvishli, bezovta","worried, nervous, concerned","He felt anxious before the interview."],
["arrogant","takabbur, mag'rur","proud, conceited, haughty","His arrogant attitude annoyed others."],
["assertive","qat'iy, o'z fikrida turuvchi","confident, firm, decisive","Be more assertive in meetings."],
["cautious","ehtiyotkor, hushyor","careful, wary, prudent","She is cautious about spending money."],
["compassionate","rahmdil, mehribon","caring, sympathetic, kind","A compassionate leader inspires trust."],
["conceited","o'zini yuqori tutuvchi, manman","arrogant, vain, egotistic","His conceited behavior was off-putting."],
["conscientious","vijdonli, mas'uliyatli","responsible, diligent, careful","She is a conscientious employee."],
["contemptuous","haqoratli, nafratli","scornful, disdainful, dismissive","He was contemptuous of the rules."],
["courageous","jasur, botir","brave, fearless, valiant","The courageous firefighter saved three lives."],
["cynical","kinoyachi, ishonchsiz","skeptical, pessimistic, distrustful","She became cynical about politics."],
["decisive","qat'iy, hal qiluvchi","determined, resolute, firm","A decisive leader acts quickly."],
["defiant","itoatsiz, bo'ysunmas","rebellious, resistant, bold","The defiant child refused to obey."],
["diligent","tirishqoq, g'ayratli","hardworking, industrious, assiduous","He is a diligent worker."],
["discreet","ehtiyotkor, sir saqlashga oid","tactful, careful, prudent","She was discreet about the matter."],
["eccentric","g'alati, o'ziga xos","quirky, unusual, odd","The eccentric professor was popular."],
["empathetic","hamdard, tushunuvchi","compassionate, understanding, sensitive","Good doctors are empathetic."],
["enthusiastic","zavqli, ishtiyoqli","eager, excited, passionate","She was enthusiastic about the project."],
["envious","hasadchi, rashkchi","jealous, covetous, resentful","He was envious of her success."],
["forthcoming","yaqinlashayotgan, ochiq","upcoming, honest, candid","She was forthcoming about her past."],
["generous","saxiy, himmatli","giving, charitable, liberal","He is generous with his time."],
["genuine","samimiy, haqiqiy","sincere, authentic, real","His concern was genuine."],
["gloomy","tushkun, ma'yus","depressed, sad, melancholy","He felt gloomy after the bad news."],
["gregarious","odamlarga yaqin, ochiq","sociable, outgoing, friendly","She has a gregarious personality."],
["gullible","ishonuvchan, sodda","naive, trusting, credulous","The gullible customer was easily deceived."],
["hostile","dushmanona, qarama-qarshi","aggressive, unfriendly, antagonistic","The crowd was hostile to the speaker."],
["humble","kamtar, oddiy","modest, unassuming, meek","Despite fame, she remained humble."],
["impulsive","shoshma-shoshar, beixtiyor","hasty, rash, spontaneous","His impulsive decisions often backfired."],
["indifferent","befarq, loqayd","apathetic, unconcerned, neutral","She was indifferent to the outcome."],
["industrious","mehnatsevar, tirishqoq","hardworking, diligent, productive","He is an industrious student."],
["insightful","chuqur fikrli","perceptive, wise, thoughtful","Her insightful comments impressed everyone."],
["intolerant","toqatsiz, sabrsiz","bigoted, narrow-minded, impatient","He is intolerant of different opinions."],
["intuitive","sezgir, intuitiv","instinctive, natural, perceptive","She has an intuitive understanding of people."],
["jovial","xushchaqchaq, quvnoq","cheerful, happy, merry","The host was jovial and welcoming."],
["meticulous","puxta, batafsillik","careful, precise, thorough","She is meticulous about details."],
["modest","kamtar, oddiy","humble, unassuming, simple","He was modest about his achievements."],
["naive","sodda, ishonuvchan","innocent, gullible, unsophisticated","She was naive to trust strangers."],
["obstinate","qaysar, o'jar","stubborn, persistent, unyielding","He was obstinate in his refusal."],
["optimistic","nikbin, umidvor","hopeful, positive, confident","She is optimistic about the future."],
["passionate","ehtirosli, ishtiyoqli","intense, fervent, zealous","He is passionate about music."],
["patient","sabr-toqatli, bemor","tolerant, calm, enduring","Good teachers are patient with students."],
["pessimistic","badbin, umidsiz","negative, gloomy, hopeless","He has a pessimistic outlook on life."],
["pragmatic","amaliy, haqiqatchi","practical, realistic, sensible","She takes a pragmatic approach."],
["prejudiced","noxolis, tarafkash","biased, bigoted, partial","A prejudiced view leads to discrimination."],
["resilient","bardoshli, moslashuvchan","tough, adaptable, strong","Children are naturally resilient."],
["sarcastic","kinoyali, piching","ironic, mocking, caustic","His sarcastic comments hurt her feelings."],
["sensitive","sezgir, nozik","delicate, emotional, perceptive","She is very sensitive to criticism."],
["skeptical","shubhali, ishonchsiz","doubtful, questioning, cynical","Scientists were skeptical of the theory."],
["spontaneous","beixtiyor, o'z-o'zidan","impulsive, natural, unplanned","Her spontaneous laughter was infectious."],
["stubborn","qaysar, o'jar","obstinate, persistent, headstrong","The stubborn child refused to eat."],
["sympathetic","hamdard, tushunuvchi","compassionate, caring, understanding","She was sympathetic to his problems."],
["tactful","nazokat bilan, ehtiyotkor","diplomatic, discreet, sensitive","She handled the situation in a tactful manner."],
["tenacious","qat'iyatli, bardoshli","persistent, determined, resolute","She is a tenacious negotiator."],
["tolerant","toqatli, kechimli","accepting, open-minded, patient","A tolerant society respects differences."],
["versatile","ko'p qirrali, moslashuvchan","adaptable, flexible, multi-talented","She is a versatile performer."],
["vindictive","o'chmanli, qasos oluvchi","vengeful, spiteful, malicious","His vindictive behavior shocked everyone."],
["vulnerable","zaif, himoyasiz","exposed, defenseless, weak","Elderly people are particularly vulnerable."],
["witty","hazilkash, aqlli","clever, humorous, funny","She is known for her witty remarks."],
["zealous","g'ayratli, fidoyi","enthusiastic, passionate, fervent","She is a zealous campaigner for justice."],

// ===== MUSIC & ENTERTAINMENT =====
["acoustic","akustik, ovozli","sound-related, audio, unplugged","The acoustic guitar has a warm sound."],
["applause","olqish, qarsak","clapping, ovation, cheering","The audience burst into applause."],
["auditorium","zalь, auditoriya","hall, theater, venue","The auditorium seats 1000 people."],
["ballad","ballada, qo'shiq","song, poem, melody","She sang a beautiful ballad."],
["celebrity","mashhur shaxs","star, famous person, personality","The celebrity attracted a large crowd."],
["cinema","kino, kinoteatr","movie theater, film, pictures","The cinema shows the latest films."],
["composer","bastakor","musician, songwriter, creator","Beethoven is a famous composer."],
["concert","konsert","performance, show, recital","The concert was sold out."],
["conductor","dirijyor, o'tkazgich","director, leader, maestro","The conductor led the orchestra brilliantly."],
["encore","yana, qayta ijro","repeat, additional performance","The audience demanded an encore."],
["ensemble","ansambbl, guruh","group, troupe, band","The jazz ensemble performed beautifully."],
["genre","janr, tur","category, type, style","Jazz is her favorite genre of music."],
["lyrics","qo'shiq matni, so'zlari","words, text, song words","The lyrics of the song are meaningful."],
["melody","ohang, kuy","tune, air, song","The melody was hauntingly beautiful."],
["premiere","premyera, birinchi namoyish","opening, debut, first showing","The film had its world premiere in London."],
["rehearsal","repetitsiya, mashq","practice, run-through, preparation","The rehearsal lasted three hours."],
["rhythm","ritm, zarb","beat, tempo, pulse","The rhythm of the music was infectious."],
["solo","yakka ijro","individual, single, alone","She performed a beautiful piano solo."],
["spectacle","tomosha, ko'rinish","show, display, sight","The fireworks were a magnificent spectacle."],
["spectator","tomoshabin","viewer, onlooker, audience member","Thousands of spectators watched the game."],
["symphony","simfoniya","orchestral work, composition","The symphony was performed flawlessly."],
["theatrical","teatr, sahnaga oid","dramatic, stagey, showy","The theatrical performance was outstanding."],
["venue","joy, makon","location, place, site","The venue for the concert was perfect."],

// ===== ADDITIONAL UNIQUE WORDS =====
["abate","pasaymoq, susaymoq","decrease, reduce, diminish","The storm finally abated."],
["abdicate","taxtdan voz kechmoq","resign, step down, renounce","The king abdicated the throne."],
["aberrant","g'ayritabiiy, normadan chetga chiqqan","abnormal, deviant, unusual","His aberrant behavior raised concerns."],
["abeyance","to'xtatilgan holat","suspension, pause, dormancy","The project is in abeyance."],
["abject","nochor, qashshoq","miserable, wretched, desperate","They lived in abject poverty."],
["ablation","olib tashlash","removal, erosion, excision","Laser ablation removes damaged tissue."],
["abnegation","voz kechish, fidoyilik","self-denial, sacrifice, renunciation","His abnegation for the cause was admirable."],
["abrogate","bekor qilmoq","cancel, revoke, annul","The government abrogated the treaty."],
["abscission","uzilish, ajralish","cutting off, separation, removal","Leaf abscission occurs in autumn."],
["absolve","oqlamoq","forgive, clear, acquit","She was absolved of blame."],
["abstraction","mavhumlik","concept, idea, theory","Art explores levels of abstraction."],
["abysmal","dahshatli yomon","terrible, awful, dreadful","The team's performance was abysmal."],
["accentuate","ta'kidlamoq","emphasize, highlight, stress","The dress accentuated her figure."],
["accession","hokimiyatga kelish, qo'shilish","joining, ascension, attainment","The accession of the new member was celebrated."],
["accolade","mukofot, taqdir","award, honor, recognition","She received numerous accolades for her research."],
["accord","kelishuv, muvofiqlik","agreement, harmony, treaty","The peace accord ended the conflict."],
["accost","qarab turish, gapirish","approach, confront, address","A stranger accosted him on the street."],
["accredit","vakolat bermoq, tasdiqlash","authorize, certify, approve","The university is accredited by the government."],
["accrete","yig'ilmoq, o'smoq","accumulate, grow, build up","Coral reefs accrete over thousands of years."],
["acerbic","achchiq, keskin","sharp, biting, caustic","His acerbic wit was legendary."],
["acquiescence","indamay rozilik","consent, agreement, compliance","Her acquiescence surprised everyone."],
["acrimony","achchiqlik, adovat","bitterness, hostility, animosity","The divorce was full of acrimony."],
["actuate","harakatga keltirmoq","motivate, drive, trigger","Greed actuated his behavior."],
["adage","maqol, naql","proverb, saying, maxim","The old adage says practice makes perfect."],
["adduce","dalil keltirmoq","cite, present, provide","She adduced evidence to support her claim."],
["adjoin","tutash bo'lmoq, chegaradosh","border, abut, neighbor","The garden adjoins the park."],
["adjunct","qo'shimcha, yordamchi","supplement, addition, accessory","The course is an adjunct to the main curriculum."],
["admonish","ogohlantirmoq","warn, rebuke, caution","The judge admonished the witness."],
["adorn","bezamoq","decorate, embellish, ornament","The room was adorned with flowers."],
["adroit","mohir, chaqqon","skillful, clever, deft","She is adroit at handling difficult situations."],
["adulation","haddan oshiq maqtov","flattery, praise, worship","The celebrity enjoyed the adulation of fans."],
["advent","kelishi, boshlanishi","arrival, beginning, emergence","The advent of social media changed communication."],
["aegis","himoya, homiylik","protection, sponsorship, support","The project was under the aegis of the UN."],
["affable","xushmuomala, samimiy","friendly, warm, amiable","The new manager is very affable."],
["affinity","yaqinlik, o'xshashlik","attraction, connection, similarity","She has a natural affinity for languages."],
["affirm","tasdiqlash, mustahkamlash","confirm, assert, declare","The court affirmed the decision."],
["afflict","azob bermoq","trouble, torment, distress","Poverty afflicts millions of people."],
["affluent","badavlat, boy","wealthy, rich, prosperous","The affluent suburb has excellent schools."],
["aggregate","yig'indi, jami","total, sum, collective","The aggregate score determines the winner."],
["aghast","dahshatga tushgan","horrified, shocked, appalled","She was aghast at the news."],
["agitate","bezovta qilmoq, tashviqot qilmoq","disturb, upset, campaign","The protesters agitated for reform."],
["ail","og'rimoq, kasallanmoq","trouble, afflict, bother","What ails the economy?"],
["akin","o'xshash, qarindosh","similar, related, comparable","The two problems are akin to each other."],
["albeit","garchi, bo'lsa ham","although, even though, though","He finished the race, albeit slowly."],
["alchemy","alkimyo, sirli o'zgarish","magic, transformation, sorcery","The alchemy of great cooking requires skill."],
["algorithm","algoritm, qoidalar ketma-ketligi","formula, process, method","The search algorithm was improved."],
["alien","begona, boshqa sayyoralik","foreign, strange, extraterrestrial","The concept was alien to her."],
["align","tekislamoq, bir qatorga qo'ymoq","arrange, adjust, synchronize","We need to align our goals."],
["allay","tinchitmoq, yupanmoq","calm, ease, relieve","She allayed their fears."],
["allege","da'vo qilmoq","claim, assert, accuse","He alleged that he was unfairly treated."],
["alleviate","engillashtirmoq, kamaytirmoq","ease, relieve, reduce","The medicine alleviated the pain."],
["allocate","ajratmoq, taqsimlamoq","assign, distribute, allot","Funds were allocated for the project."],
["allot","ajratmoq, ulush bermoq","allocate, assign, distribute","Each team was allotted an equal budget."],
["allude","ishora qilmoq, nazarda tutmoq","hint, suggest, refer","The author alluded to historical events."],
["allure","joziba, jalb qilmoq","charm, attraction, appeal","The allure of the city drew many visitors."],
["altercation","janjal, mojarо","argument, dispute, quarrel","An altercation broke out between fans."],
["ameliorate","yaxshilamoq, tuzatmoq","improve, better, enhance","Education can ameliorate social problems."],
["amiable","do'stona, xushmuomala","friendly, kind, pleasant","She has an amiable disposition."],
["amiss","noto'g'ri, xato","wrong, faulty, improper","Something seemed amiss."],
["amorphous","shakli yo'q, noaniq","shapeless, formless, vague","The plan was still amorphous."],
["ample","yetarli, keng","sufficient, plenty, abundant","There was ample space for everyone."],
["amplify","kuchaytirmoq, kengaytirmoq","increase, magnify, boost","He amplified the sound system."],
["analogy","o'xshashlik, taqqoslash","comparison, similarity, parallel","She drew an analogy between the two situations."],
["anarchy","tartibsizlik, boshboshdoqlik","chaos, disorder, lawlessness","Political instability led to anarchy."],
["anchor","langar, mustahkamlamoq","secure, fasten, fix","The ship dropped its anchor."],
["anecdote","latifa, qisqa hikoya","story, tale, account","She shared an amusing anecdote."],
["anguish","azob, iztirob","pain, suffering, torment","The anguish of losing a child is immense."],
["animosity","adovat, dushmanlik","hostility, hatred, enmity","There was deep animosity between them."],
["annex","ilova, qo'shib olmoq","attach, add, append","The library annex was opened."],
["annotate","izoh bermoq","note, comment, gloss","She annotated the text thoroughly."],
["annul","bekor qilmoq","cancel, invalidate, void","The marriage was annulled."],
["antecedent","oldingi, sabab","predecessor, forerunner, cause","What were the antecedents of the war?"],
["anthology","to'plam, antologiya","collection, compilation, selection","The anthology includes works by modern poets."],
["anticipate","kutmoq, oldindan sezmoq","expect, foresee, predict","We anticipate strong demand."],
["antidote","tiryak, davo","cure, remedy, countermeasure","Education is the antidote to ignorance."],
["antiquated","eskirgan, qadimiy","outdated, old-fashioned, obsolete","The equipment is antiquated."],
["antipathy","nafrat, yoqtirmaslik","dislike, aversion, hostility","She felt antipathy towards dishonesty."],
["apathy","befarqlik, loqaydlik","indifference, lethargy, disinterest","Apathy is the enemy of democracy."],
["apex","cho'qqi, eng yuqori daraja","peak, summit, pinnacle","She is at the apex of her career."],
["aplomb","o'ziga ishonch, vazminlik","confidence, poise, composure","She handled the crisis with aplomb."],
["appall","dahshatga solmoq","horrify, shock, dismay","The conditions in the prison appalled visitors."],
["apparatus","asbob, qurilma","equipment, device, instrument","The laboratory has modern apparatus."],
["apparel","kiyim-kechak","clothing, attire, garments","The store sells women's apparel."],
["appease","tinchitmoq, qoniqtirmoq","calm, pacify, satisfy","He tried to appease the angry customer."],
["append","qo'shmoq, biriktirmoq","add, attach, supplement","She appended a note to the letter."],
["applaud","olqishlamoq, maqtamoq","clap, praise, commend","The audience applauded loudly."],
["apposite","mos, o'rinli","appropriate, relevant, suitable","His comments were apposite."],
["appraise","baholamoq","evaluate, assess, estimate","The expert appraised the artwork."],
["apprehensive","xavotirli","anxious, worried, nervous","She was apprehensive about the results."],
["arbiter","hakam, vasiy","judge, mediator, referee","The arbiter made a fair decision."],
["ardent","otashin, jo'shqin","passionate, fervent, enthusiastic","He is an ardent advocate of free speech."],
["arduous","mashaqqatli","difficult, hard, strenuous","The arduous climb took all day."],
["arid","qurg'oq, suvsiz","dry, barren, parched","The arid desert stretches for miles."],
];

async function seed() {
    const SQL = await initSqlJs();
    let db;

    if (fs.existsSync(DB_PATH)) {
        const buffer = fs.readFileSync(DB_PATH);
        db = new SQL.Database(buffer);
    } else {
        db = new SQL.Database();
        db.run(`CREATE TABLE IF NOT EXISTS words (id INTEGER PRIMARY KEY AUTOINCREMENT, english TEXT NOT NULL, uzbek TEXT NOT NULL, synonyms TEXT DEFAULT '', example TEXT DEFAULT '', score INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
    }

    const existing = new Set();
    const rows = db.exec('SELECT english FROM words');
    if (rows.length > 0) {
        rows[0].values.forEach(r => existing.add(r[0].toLowerCase()));
    }

    let added = 0;
    const stmt = db.prepare('INSERT INTO words (english, uzbek, synonyms, example) VALUES (?, ?, ?, ?)');

    for (const [eng, uzb, syn, ex] of words) {
        if (!existing.has(eng.toLowerCase())) {
            stmt.run([eng, uzb, syn || '', ex || '']);
            existing.add(eng.toLowerCase());
            added++;
        }
    }
    stmt.free();

    const data = db.export();
    fs.writeFileSync(DB_PATH, Buffer.from(data));

    const total = db.exec('SELECT COUNT(*) FROM words');
    console.log(`${added} ta yangi so'z qo'shildi. Jami: ${total[0].values[0][0]} ta so'z.`);
    db.close();
}

seed().catch(console.error);
