name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug username
        run: echo "USER=${{ secrets.SERVER_USER }}"

      - name: Debug connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          debug: true
          port: 22
          script: |
            echo "Connecting successfully applied"

      - name: Deploy through SSH key to test server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          debug: true
          port: 22
          script: |
            set -e

            cd ${{ secrets.PROJECT_PATH }}

            echo "⬇️ Pulling latest code..."
            git pull origin main

            echo "🔨 Building new image..."
            docker compose build

            echo "🚀 Starting services..."
            docker compose restart

            echo "📦 Running migrations..."
            docker compose exec -T web python manage.py migrate --noinput

            echo "🧹 Cleaning up old images..."
            docker image prune -f

            echo "✅ Deploy complete!"
